### ISSUE TITLE
Nejasnosti v typech stran impressum, dodatek (appendix)

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#102]
Dobry den,
rad bych pozadal o ujasneni vyznamu pojmu impressum (impressum) a dodatek (appendix).
1) **impressum (impressum)** - v databazi TDKIV NK je to brano jako pojem pro vydavatelske udaje (https://aleph.nkp.cz/F/5D1KSYST8ANX65JTQ44QR6LCT2SAJJKJF87T3MIVAKGF8PSMBK-58719?func=find-acc&acc_sequence=000000867).
V odkazu na wikipedii je ale bran jako udaj spojeny s copyrightem a ISBN.
Predpokladam spravne, ze je impressum mysleno ve vyznamu vydavatelskych udaju? Pokud ano, jsou povinne i tiskarske udaje,aby slo o impressum
Stranka s pouhym uvedenim copyrightua ISBN neni impressum?

2) **dodatek (appendix)** - v databazi TDKIV NK se jedna o dva terminy s uplne jinymi vyznamy. **Dodatek** jako dokument vyrobny dodatecne a doplnujici puvodni dilo (https://aleph.nkp.cz/F/5D1KSYST8ANX65JTQ44QR6LCT2SAJJKJF87T3MIVAKGF8PSMBK-28595?func=find-acc&acc_sequence=000021256)
**appendix** jako material na konci dokumentu doplnujici hlavni text. Tedy priloha (https://aleph.nkp.cz/F/5D1KSYST8ANX65JTQ44QR6LCT2SAJJKJF87T3MIVAKGF8PSMBK-38169?func=find-acc&acc_sequence=000006651)
Ktery vyznam je myslen? Pokud je to vyznam prilohy,možná by bylo lepsi zmenit zneni ceskeho terminu

Dekuji
Ales Drahotušský

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

1. pod pojmom impressum sa myslia nakladateľské údaje, pričom informácia o autorských právach (copyright a dátum) a ISBN tam musí byť vždy. Ďalšie údaje (napr. informácie o tisku) povinné nie sú, ale obvykle sa tam vyskytujú.

2. dodatkom sa myslí vami uvedený druhý význam, tj. dodatok = príloha, materiál na konci dokumentu doplňujúci hlavný text. TDKIV vám vyhodí správne heslo, keď do neho zadáte "appendix", resp. "příloha".

**Comment by Drahotussky** [comment]
Dobry den,
mohl bych poprosit o nazor,zda se jedna o impressa?
Dekuji

![1](https://user-images.githubusercontent.com/6399737/64671274-37d67680-d468-11e9-9766-1e17a61e2fe3.jpg)
![2](https://user-images.githubusercontent.com/6399737/64671276-37d67680-d468-11e9-88da-e44b2f73baef.jpg)
![3](https://user-images.githubusercontent.com/6399737/64671277-37d67680-d468-11e9-8e22-ae67e490c8ab.jpg)
![4](https://user-images.githubusercontent.com/6399737/64671278-37d67680-d468-11e9-9b5b-f63663584d81.jpg)
