### ISSUE TITLE
Vnitřní části monografie

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#103]
Dobry den,
rad bych se zeptal, jaky typ kapitoly si mam predstavit pod pojmy:
figure
remark

Dekuji
Ales Drahotušský

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
u typu kapitoly, resp. oddílu platí, že typ "figure" používame najmä u odborných publikácii pre grafy alebo podobné grafické reprezentácie. Pod pojmom "remark" sa myslí všeobecná poznámka.

**Comment by Drahotussky** [comment]
A jaky je rozdil mezi remark a OtherNote. To je poznamka jineho typu?
Pod Contributors spada prosim co?

Dekuji

A.D.

**Comment by MirkaBenackova** [comment]
Pod contributors by som si predstavila stránku, na ktorej je zoznam ľudí, ktorí sa podieľali na obsahu danej publikácie, napr. autori príspevkov v zborníku apod. 
Ohľadne rozdielu medzi remark a otherNote sa ozvem začiatkom budúceho týždňa, potrebujem to skonzultovať.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

ospravdlňujem sa za zdržanie. Mnou uvedený výklad "contributors" platí. 
Pri "remark" ide o vydavateľskú poznámku, držíme sa výkladu podľa TDKIV, tj. "Poznámka editora publikace (popř. nakladatele nebo  vydavatele) vysvětlující původ textu, charakter a rozsah textových  úprav, vybavení knihy informačním aparátem apod. Uvádí se zejména u  kritických vydání autorských děl."
Pod otherNote si môžete predstaviť poznámku iného typu, tj. inú ako vydavateľskú poznámku, poznámku k vydaniu apod.
