### ISSUE TITLE
DMF Monografie 1.3.2 page genre

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#105]
Podle DMF (https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2 str.č.74), element genre je na stejné úrovni jako part. Podle vzorkového balíčku (odkaz na stránkách https://www.ndk.cz/standardy-digitalizace/metadata), element genre je subelementem part:

```
<mods:part>	
	<mods:detail type="pageIndex">
		<mods:number>1</mods:number>
	</mods:detail>
<mods:note>right</mods:note>
<mods:genre type="titlePage">reprePage</mods:genre>
<mods:typeOfResource>still image</mods:typeOfResource>
</mods:part>

```

Co z toho je správné?
Děkuji.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
riaďte sa prosím aktuálnym DMF. Elementy "genre" a "part" majú byť oba na rovnakej úrovni, tj. nie sú si navzájom subelementami. V prípade vzorového balíčku sa jedná o preklep.
