### ISSUE TITLE
eMonografie - strukturální mapa

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#108]
Dobrý den, 
mám dotaz. Na webu NDK pořád není žádný vzorový balíček pro eMonografie, takže bych se potřebovala ujistit o tom, jak má vypadat strukturální mapa. 

Může vypadat takto? 
![67762701-5c9da200-fa46-11e9-86c5-7edb759730a4](https://user-images.githubusercontent.com/21309201/67764934-49d99c00-fa4b-11e9-863e-7ea4de10ac71.png)

U prvního "div" elementu je type=title. Je to tak správně? Ze standardu jsem to pochopila tak, že type=title se používá pro nejvyšší úroveň vícedílné monografie.

Nebo by to měl být spíš takhle?
![67764568-8f499980-fa4a-11e9-83fa-49ad437d6b95](https://user-images.githubusercontent.com/21309201/67764976-62e24d00-fa4b-11e9-9a6a-8ab273b66d06.png)

Je to strukturální mapa pro jeden svazek jednosvazkové monografie... je to takhle správně, nebo by tam mělo být něco jinak? 

Děkuji
Jana Křížová

**Comment by PavlinaKocisova** [comment]
Dobrý den, připínám ukázku strukturální mapy.

![edeposit_structmap](https://user-images.githubusercontent.com/26895177/102837032-3d589580-43fb-11eb-8cb5-398ab6ca75aa.png)

**Comment by vjirousek** [comment]
Vzorový balíček již je na webu standardů dostupný, issue tedy uzavírám.
