### ISSUE TITLE
Pravidla pro popis periodik, nepodporovaná verze datumu vydání výtisku

### ISSUE THREAD

**Issue by isenkyr** [NLCR/Standard_NDK#109]
Dobrý den,

pro zápis data vydání výtisku se řídíme pravidly pro popis periodik verze 8.3.1
Povolené možnosti zápisu jsou 
DD.MM.RRRR
MM.RRRR
MM.-MM.RRRR
RRRR

co když je ale na fyzické předloze natišteno datum ve formátu DD.MM-DD.MM.RRRR? Jak s takovým zápisem naložit?

Děkuji za odpověď

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
s pridaním ďalšieho formátu dátumu by nemal byť problém. Táto zmena bude zohľadnená v nadchádzajúcej aktualizácii pravidiel pre popis.

**Comment by isenkyr** [comment]
Dobrý den,

děkuji za odpověď. Námi další zjištěné formáty datumu jsou

DD.MM-DD.MM.RRRR
DD.MM.RRRR-DD.MM.RRRR
MM.RRRR-MM.RRRR
DD.-DD.MM.RRRR

prosím o zohlednění v příštích pravidlech pro popis periodik.

Děkuji I.Šenkýř

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
vami zmienené formáty dátumu budú zahrnuté.

**Comment by MirkaBenackova** [comment]
Hore uvedené formáty zápisu dátumu sú zahrnuté do aktualizovaných pravidiel pre popis periodík (zverejnených 20.12.2019).

**Comment by isenkyr** [comment]
Dobrý den,

bouhužel až po aktualizaci pravidel jsme u nás přišli ještě na další formát zápisu data vydání. Jedná se o rozsah roků.
RRRR-RRRR
Bylo by možné v další verzi pravidel pro popis periodik přidat ještě tento formát zápisu datumu?

Děkuji I.Šenkýř

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujem za správu, tento formát zápisu dátumu teda zahrnieme do najbližšej stotinkovej aktualizácie.
