### ISSUE TITLE
Monografie - číslování

### ISSUE THREAD

**Issue by SeraZdenka** [NLCR/Standard_NDK#110]
Dobrý den, prosím o radu, jak správně očíslovat svazek v těchto dvou situacích:
1. Po neočíslovaném začátku (desky, ... titul ...) následuje "Obsah" očíslovaný římskými číslicemi, pak arabskými číslicemi očíslovaný vlastní text publikace. Jak dočíslovat začátek titulu - vztáhnout k římskému číslování obsahu nebo arabskému číslování "těla" publikace?
2. Titul obsahuje učebnici a slovník, přičemž každá z obou částí má vlastní arabské číslování - např. 3-120 a 3-40. Máme dodržet očíslování v podle vytištěné předlohy? Pokud ano, měly by nečíslované stránky na konci publikace navazovat na číslování slovníku (za nímž se fyzicky nacházejí) nebo na učebnici (k níž spíše patří logicky)?
Děkuji, ZŠ

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

1. Vhodnejšie by bolo očíslovať dané strany rímsky. 
2. Tu by som určite dodržiavala číslovanie ako je na stránke vytlačené, tj. najprv 3-120 a potom 3-40. U strán na konci publikácie by som potom pokračovala v číslovaní slovníku. 
Číslovanie na začiatku a konci knihy by sa malo vzťahovať k tou, ako sú číslované strany nasledujúce resp. predchádzajúce.

**Comment by SeraZdenka** [comment]
Děkuji!
