### ISSUE TITLE
Standard2019

### ISSUE THREAD

**Issue by isenkyr** [NLCR/Standard_NDK#112]
Dobrý den,

provádím implementaci nového standardu do nasšeho systému. A zjistil jsem několik nepřesností.

1) v elementu part v mods vnitřní části přibyl podelement detail. Element detail má definovaný pouze atribut @type, ale s pohledu xsd pro mods3.6 musí mít element detail ještě podlement? Strana 51 v periodikách 1.8.
2) v mods pro vnitřní části přibyl nový element part s podelementem detail a atributem @type. Ve standardu pro periodika 1.8 je tento atribut definován jako page Index (str. 51) a ve standardu pro monografie 1.4 jako pageIndex (str. 70). Já bych čekal, že hodnoty budou stejné. Pravděpodobně se jedná o překlep.

**Comment by PavlinaKocisova** [comment]
Dobrý den, ano, podle ustáleného syntaxu by podelement mít měl; analogicky jsme toto aplikovali dříve také v úrovni popisu strany. 

Děkujeme za upozornění na rozpor v zápisu pageIndex. Hodnota by měla být vepsána dohromady. Jedná se o překlep, který opravíme.

**Comment by isenkyr** [comment]
Dobrý den, předpokládám že podlementem tedy bude element <number> nebo 2 x element <number>? který bude obsahovat hodnoty z elementu <extent>/<start> a <extent>/<end>? Je moje úvaha správná?

**Comment by isenkyr** [comment]
Dobrý den, předpokládám že podlementem tedy bude element number nebo 2 x element number? který bude obsahovat hodnoty z elementu extent/start a extent/end? Je moje úvaha správná?

**Comment by krizovj** [comment]
Teď nevím, jestli už se to někde řeší, ale na úrovni strany je atribut type pro index strany "pageIndex" a pro číslo strany "page number". 
Neměla by ta podoba být konzistentní? tedy: "pageIndex" a "pageNumber"?

**Comment by PavlinaKocisova** [comment]
Jana Křížová: ano, tento poznatek už máme a bude se opravovat do podoby "pageIndex" a "pageNumber".

**Comment by vjirousek** [comment]
Opraveno v:
- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022
