### ISSUE TITLE
Pravidla pro popis periodik 8.4 - ilustrace, hřbet

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#113]
Dobry den,
v pravidlech popisu došlo pravdepodobne k prohozeni vyznamu hesel u Seznamu ilustraci a Ilustrace.
Rad bych se take zeptal:
1) co vse se rozumi jako ilustrace? Je to např. také fotografie, graf?

2) Hrbet - proc je u monografii uvedeno,ze neni nutne ho skenovat a u periodik toto uvedeno neni? U periodik je nizsi moznost,ze tam bude hrbet.
Drivejsi praxe, ze se hrbet skenoval spolu se zadnimi deskami, je jiz nevhodna?

Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

ďakujem za upozornenie; v prípade pravidiel pre popis periodík skutočne došlo k zameneniu charakteristík zmieňovaných hesiel. Nezrovnalosť bude odstránená v stotinkovej úprave. 

Ohľadom Vašich otázok:
1. V prípade, že sa bavíme o typoch strán, tak pod typom "ilustrace" by som chápala ilustráciu, fotografiu aj graf, proste akúkoľvek obrazové doplnenie textu. Konkrétne rozlišovať medzi ilustráciou/fografiou/grafom je možné len na úrovni vnitřní části, keď popisujeme konkrétny obraz ("picture"). 
2. Všetky informácie ohľadne hřbetu knihy sú zachované a formulácie sa voči verziám 2.1.2 a 8.3.1 v ničom (obsahom ani umiestnením) nezmenili. U periodík to zrejme nie je už od minulých verzii uvedené práve kvôli minimálnej možnosti výskytu. 
Prax, kedy sa hřbet skenoval spolu so zadnými doskami zostáva zachovaná; viď napr. PP pre monografie, str. 9, časť 1.3 Best practices pre popis typů stran, prípadne str. 11 Pravidla popisu desek. 

Preferovali by ste, aby sa krátka poznámka o skenovaní hřbetu doplnila aj do PP pre periodiká?

**Comment by PavlinaKocisova** [comment]
Poznámku přidáme.

**Comment by Drahotussky** [comment]
Divam se, ze je hrbet uveden u Pravidel pro popis periodik jako typ strany,ktere je nutno popsat. Bylo prevzato z pravidel pro popis monografii.
Asi by se dana cast mela aktualizovat na typy stran typicke pro periodika

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
to, že je hřbet uvedený u periodík ako typ strany, ktorý je nutné popísať, znamená, že by sa mal popísať, pokiaľ tam je (napríklad keď máte ročenku alebo zborník). Samozrejme si uvedomujeme, že hřbet sa u periodík bude vyskytovať minimálne. Ale sám ste sa vyššie dotazoval, prečo v Pravidlách pre popis periodík chýbajú pokyny k skenovaniu hřbetu - nie sú tam práve pre to, že to nie je typická strana. Prisľúbili sme pridanie poznámky. Takže si myslím, že zoznam strán typické pre periodiká nie je nutné aktualizovať.
