### ISSUE TITLE
Úroveň strany - dotaz

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#114]
Dobrý den, 
mám dotaz na mods stránky. Omlouvám se, ale není mi úplně jasný význam elementu extent v MODSu stránky: 

![ndkstranadotaz](https://user-images.githubusercontent.com/21309201/72140858-f01e1800-3391-11ea-9080-cc536a3df7a7.jpg)

Na co přesně by se měl element použít? 
Děkuji
J. Křížová

**Comment by krizovj** [comment]
Prosím o odpověď, děkuji.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
tento element slúži na zápis rozsahu; v prípade úrovne strany sa jedná len o číslo strany. Zároveň uvádza, v akých jednotkách je rozsah udávaný, v našom prípade je to "strana".

**Comment by krizovj** [comment]
Děkuji, ale asi to pořád nechápu. Můžete mi prosím dát nějaký příklad, jaký rozsah se tím dá vyjádřit? Resp. kdy konkrétně se to má použít?

**Comment by MirkaBenackova** [comment]
Keď je tento element použitý napr. na úrovni pre kapitolu, zapíše sa doňho rozsah strán, na ktorých sa daná kapitola nachádza. Napríklad: 
<mods:extent>
   <mods:start>15</mods:start>
   <mods:end>18</mods:end>
</mods:extent>

Na úrovni strany popisujeme vždy len jednu konkrétnu stranu, preto má <mods:extent> len subelement <mods:start>. Do neho sa zapíše len jedno konkrétne číslo popisovanej strany (v užšom zmysle sa teda asi nejedná úplne o rozsah). Napríklad: 
<mods:extent unit="pages">
  <mods:start>15</mods:start>
</mods:extent>

**Comment by krizovj** [comment]
Ano, u kapitol a článků je mi ten rozsah jasný, u té strany mi to právě jasné nebylo. 

Uvádí se tedy číslo strany (pageNumber)? Tedy to stejné číslo, které je v tom stejném elementu part v detail/number type=pageNumber.

**Comment by MirkaBenackova** [comment]
Áno, je to tak ako píšete.

**Comment by isenkyr** [comment]
Dobrý den,

ještě se zeptám do MODS_PAGE se v elementu detail[@type="pageNumber"]/number (extent[@unit="pages"]/start) vkládá číslo strany fyzicky vytištěné na dokumentu (dopočítáné)? Ptám se, protože ve vzorku periodika vyvešeném na stránkách NDK tyto hodnoty neodpovídají atributu ORDERLABEL ve fyzické mapě u jednotlivých dokumentů, který nese právě tuto informaci.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
do elementu detail s atribútom type "pageNumber" sa uvedie číslo strany, vyjadrujúce poradie v reprezentácii.  Do elementu detail s atribútom type "pageIndex" sa uvedie číslo strany, ako je uvedené v dokumente (alebo dopočítané). ORDERLABEL odpovedá elementu detail s atribútom "pageIndex".
Nezrovnalostí vo vzorových balíkoch sme si vedomí, v súčasnosti prebieha revízia.

**Comment by isenkyr** [comment]
Dobrý den,

číslo uváděné do elementu detail s type "pageNumber"  je spojíté přes svazek a všechny přílohy anebo začíná od 0 (1) pro každou logickou jednotku? Číslování má být od 0 nebo 1?

**Comment by krizovj** [comment]
"Dobrý deň,
do elementu detail s atribútom type "pageNumber" sa uvedie číslo strany, vyjadrujúce poradie v reprezentácii. Do elementu detail s atribútom type "pageIndex" sa uvedie číslo strany, ako je uvedené v dokumente (alebo dopočítané)."

@MirkaBenackova omlouvám se, ale není to obráceně? Tedy pageIndex je pořadí v reprezentaci a pageNumber je číslo na předloze, případně dopočítané?

**Comment by MirkaBenackova** [comment]
@isenkyr 
> Dobrý den,
> 
> číslo uváděné do elementu detail s type "pageNumber" je spojíté přes svazek a všechny přílohy anebo začíná od 0 (1) pro každou logickou jednotku? Číslování má být od 0 nebo 1?

Číslovanie v pageNumber je spojité naprieč celým dokumentom. Čo sa týka číslovania od 0 resp. od 1, táto záležitosť nie je presnejšie špecifikovaná a závisí na Vás. 
 


@krizovj 
> 
> @MirkaBenackova omlouvám se, ale není to obráceně? Tedy pageIndex je pořadí v reprezentaci a pageNumber je číslo na předloze, případně dopočítané?

V niečom máte pravdu; narazila som na isté nezrovnalosti medzi formuláciami v monografiách a periodikách; ozvem sa ohľadom tohto.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

@krizovj, mali ste pravdu. Tak, ako hovoríte vy (teda pageIndex pre poradie v reprezentácii a pageNumber pre číslo strany uvedené na konkrétnej strane/dopočítané) to je správne, na tomto princípe funguje celá produkcia NDK aj Kramerius. 
Vysvetlivky v DMF u týchto elementov sú od pridania úrovne strany identické, teda muselo dôjsť k zámene alebo k zavádzajúcej formulácii už vtedy.
V ďalšej aktualizácii túto nezrovnalosť ostránime. Zároveň pridávam novú issue upozorňujúcu na túto záležistosť.

**Comment by luckajirku** [comment]
Můžu se zeptat, k čemu přesně slouží na úrovni PAGE mods:extent unit="pages"? Když pouze kopíruje hodnotu z pagenumber (a navíc s tím matoucím popisem extent a startem bez endu)? Využívá to nějak konkrétně třeba Kramerius (a jak)? Díky.

**Comment by PavlinaKocisova** [comment]
Zdravím, problém tkví v možnostech syntaxu MODS, respektive, možnosti zaznamenání konkrétních hodnot. Potřebovali jsme do zápisu dostat dva nezávislé bloky, popisující zároveň číslo strany v předloze a číslo strany v reprezentaci, které se musí nějak rozlišit. Blok "detail" nám umožňuje zapsat, o který z těchto dvou bloků se jedná, zatímco kontejner extent nám říká, že se jedná o tuto konkrétní stranu, která začíná v tomto místě. Bohužel všechno nelze zapsat kvůli nabídce subelementů a atributů pouze pod "detail" nebo pouze pod "extent", přičemž Kramerius si bere číselný údaj pro řazení z extentu. Je to krkolomné, ale v době vzniku zápisu nebylo lepší řešení, a domnívám se, že ani dnes to nelze zapsat lépe.
