### ISSUE TITLE
Typ vydání (čísla) periodika

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#115]
Dobrý den,
rad bych se zeptal, jaky typ vydani (cisla) periodika patri vytisku, na nemz je vytisteno ** po konfiskaci druhe opravene vydani, po konfiskaci opravene vydani**?
Je to typ vydani corrected, special nebo sequence_X?

Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
je to typ vydania "special". 
Pokyny k popisu takýchto cenzurovaných vydaní boli pridané do najnovšej verzie Pravidiel pre popis periodík, časť 6.4, str. 27).

**Comment by Drahotussky** [comment]
Dobry den,
dekuji za info. V Obsahu bod 6.4 neni uveden
Ve všeobecné poznámce hlavního mets by pak u opravených vydání měla být uvedena hodnota „po cenzuře opravené vydání“ - tim je mysleno dat uvedeny text do poznamky toho vytisku nebo do poznamky titulu?
Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujem za upozornenie, neaktualizácia obsahu asi nejako unikla našej pozornosti. Bude doplnené. 
Hodnota "po cenzuře opravené vydání" sa uvedie vo všeobecnej poznámke výtisku ktorého sa to týka (úroveň issue).

**Comment by Drahotussky** [comment]
Dobrý den,
v pravidlech popisu periodik se pise: To znamená, že necenzurované vydání bude
označeno např. jako „2A“, zatímco po cenzuře opravené vydání jako „2B“
Znamená to, že ikdyž budeme mít pouze po cenzuře opravene vydání, tak bude mít označení 2B? Nebo se číslování posune a cenzurovaný výtisku bude mít označení 2A?
Děkuji

**Comment by PavlinaKocisova** [comment]
Dobrý den, myslíme si, že by bylo dobré označovat písmenem "B" cenzurovaná vydání i v případě, že by ve fondu instituce nebylo zároveň i vydání před cenzurní opravou. Počítáme s tím, že se to samozřejmě vztahuje pouze na čísla, u kterých je doloženo, že existovaly dvě verze (nebo více), jinak se předpokládá prostě číslování. 

Také to samozřejmě neznamená, že by se odteď měnila zažitá praxe číslování periodik, a veškerá necenzurovaná vydání se označovala písmenem "A". 

Formulaci v PP periodik upravíme, aby byl výklad jednoznačnější.
