### ISSUE TITLE
Články a kapitoly - rozsah stran

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#117]
Dobrý den, mám dotaz na to, jak má správně vypadat element part v záznamu článku nebo kapitoly. Podívala bych se do vzorového balíčku, ale na webu NDK bohužel není žádný s touto úrovní popisu. 
Ve standardu je element part popsáno takto:
![part](https://user-images.githubusercontent.com/21309201/73825605-8f50f680-47fc-11ea-9f7d-e4852d9e01ee.jpg)

Jak by to tedy prosím mělo vypadat? 
Takhle:
![partndkclanky](https://user-images.githubusercontent.com/21309201/73825821-f8d10500-47fc-11ea-883e-f069cb4fc328.jpg)

Nebo takhle? Ze standardu to vypadá, jako že detail má být na stejné úrovni jako extent.
![partndkclanky2](https://user-images.githubusercontent.com/21309201/73825826-fbcbf580-47fc-11ea-9145-c99a5869489d.jpg)

Není tam element detail tak trochu navíc?
Potřebovala bych znát správnou podobu kvůli úpravám ProArcu.

Děkuji

**Comment by isenkyr** [comment]
Dobrý den,

dovolím si přidat svůj poznatek, protože u této části standardu jsem zaznamenal také problém.
Nejprve k dotazu paní Křížové. Podle xsd souboru mods3.6.xsd, který definuje mods 3.6 je element part pro vnitřní části popsán ve standardu správně a tudíž je správně příklad číslo 2, který uvádíte.
Následně ovšem vznikne problém při validaci oproti mods3.6.xsd, protože podle tohoto xsd souboru musí element detail obsahovat nějaký podelement (number, caption, title). Tyto podelementy ovšem nejsou ve standardu definované.

**Comment by isenkyr** [comment]
Element detail se opravdu jeví, že je tam zbytečný. Hodnotu pageIndex (pageNumber) by šla zapsat do atributu type v elementu part. part[@type = 'pageIndex']

**Comment by krizovj** [comment]
Prosím o odpověď, jak by to mělo správně být. Děkuji

**Comment by PavlinaKocisova** [comment]
Dobrý den, pan Šenkýř má pravdu, možnost číslo dvě je správná. Bohužel v DMF pod <detail> skutečně chybí subelement <number>, který by tam pro správný syntax zápisu měl být.  Prosím tedy, abyste do úpravy proArcu tento element zahrnuli (byť zatím bez podpory v DMF), validátorem by to mělo projít. Tuto chybu opravíme v letošní aktualizaci. Děkujeme za upozornění!

**Comment by krizovj** [comment]
Dobrý den, dobře. Prosím tedy ještě o potvrzení, že takhle to má být správně: 
![part4](https://user-images.githubusercontent.com/21309201/74504497-a9718f80-4ef4-11ea-97da-1b6275171bee.jpg)

A také prosím o vysvětlení, co uvést do elementu number...
Děkuji!

**Comment by PavlinaKocisova** [comment]
Omlouvám se za opožděnou odpověď, do elementu number se vkládá stránkový rozsah kapitoly. Vkládám příklad zápisu. K elementu extent jsme přidaly ještě atribut unit=pages, aby byl syntax zápisu úplně korektní. V duchu tohoto příkladu upravíme i DMF. 

![part_kapitola](https://user-images.githubusercontent.com/26895177/75327646-0d913d80-587d-11ea-80ca-56f92241b779.png)

**Comment by krizovj** [comment]
Děkuji za odpověď

**Comment by gmelingerova** [comment]
Dobrý den,

šlo by do elementu \<mods:part> přidat atribut "type", který by měl hodnotu "pageNumber" nebo "pageIndex"?
- \<mods:part type="pageNumber"> ....... </mods:part>

Dává větší smysl se podívat na typ v nejvyšším elementu, než se zbytečně zanořovat a zjistit, že tento element mě vůbec nezajimá.
Z programátorského hlediska by se tím usnadnilo zpracování pro Krameria. Obecně by to bylo lépe čitelné a srozumitelné.
 
Ve vašem příkladu vám chybí koncové tagy </mods:extent>.

**Comment by PavlinaKocisova** [comment]
Máte pravdu. Není problém to takto předělat. A děkuji za upozornění na chybu. 
![part_kapitola_opr](https://user-images.githubusercontent.com/26895177/75957100-96315e80-5eb9-11ea-8ecc-827735b06f6a.png)

**Comment by vjirousek** [comment]
Dohodnutý způsob zápisu byl doplněn do:
- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022

![obrazek](https://user-images.githubusercontent.com/22765973/196246158-586b75a7-b835-41b6-9fb1-0c8883daaf92.png)
![obrazek](https://user-images.githubusercontent.com/22765973/196246230-b4ee6bc8-d439-467a-aa94-d0f9ac7360ae.png)
