### ISSUE TITLE
Jiný titul ve svazku

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#118]
Pokud je privazano k v jednomu rocniku titulu jen nekolik cisel jineho titulu u (patrně jako reklamni cislo), je mozne ponechat tato cisla kde jsou a popsat je jako prilohu? Nebo je radeji uplne vyradit z popisu?
Popsat je zvlast mi prijde neefektivni.
Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
pokyny k tejto situácii sú uvedené v Pravidlách pre popis periodík v časti 6.3 Jiný titul ve svazku (str. 27). Pokiaľ je to možné a takýto titul má záznam v katalógu, spracuje sa tento titul (ktorý je priviazaný k inému titulu buď omylom alebo ako reklamné číslo) osobitne.

**Comment by Drahotussky** [comment]
Dobry den,
do pravidel jsem se dival, jen mi prijde neefektivni a casove narocne zpracovat 5 cisel periodika (vychazelo nekolik let), ktere jsou prirazeny k jinemu periodiku, jako samostatne periodikum.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
prekonzultovala som túto záležitosť s kolegyňou, a obe sme presvedčené o tom, že by ste druhý titul mali spracovať osobitne podľa pokynov v PPP časti 6.3, najmä ak chcete zachovať povahu dokumentu.  
Osobitne by som druhý titul spracovávala už len kvôli tomu, že sa nejedná o ojedinelý výskyt, ale ako uvádzate, jedná sa o 5 čísel ktoré takýmto spôsobom vychádzali niekoľko rokov po sebe.

**Comment by Drahotussky** [comment]
Dobry den,
dekuji za odpoved.
My prave mame pouze 5 cisel 2. rocniku periodika, ktere jsou privazany k jinemu titulu periodika. Dalsi cisla z daneho 2. rocniku nebo jinych rocniku periodika nemame.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
PPP v zmienenej časti v tomto prípade povoľujú aj ponechanie rozhodnutia na vlastníka-zadávateľa. Dohodnite sa teda o forme spracovania so zadávateľom vašej digitalizácie.
