### ISSUE TITLE
Typ vydání (čísla) - supplement

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#119]
Dobrý den,
můžete mi prosim objasnit, co patří do tohoto typu vydání?
V pravidlech se píše, že je to příloha, která není součásní výtisku. Jde tedy např. o jiný titul periodika (viz bod 6.3)?

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
jedná sa napríklad o přívaz (napr. číslo Mladé Fronty přivázané k Lidovým novinám).

**Comment by Drahotussky** [comment]
Dobry den,
pokud tedy budu mit u periodika privazano cisla jineho titulu, podle ceho se rozhodnu, zda privazane cislo popsat jako vytisk s typem vydani supplement nebo je popsat podle bodu 6.3?
Tezko lze zjistit, zda byla cisla privazana omylem nebo zamerne, protoze slo o reklamni cislo.

Pokud by se cislo popsalo jako typ vydani supplement, napsalo by se do poznamky, ke kteremu cislu bylo privazano?

Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
rozhodla by som sa na základe konkrétnej situácie. Napríklad vyššie zmienená Mladá Fronta sa spracováva samostatne; ak ide o jeden ojedinelý výskyt, riešila by som to asi cez supplement.   
K Vašej druhej otázke; možno celkom nerozumiem, ale záznam sa vždy tvorí ku jednému konkrétnemu číslu, preto nevidím dôvod, aby sa písalo do poznámky, ku ktorému číslu je čo přivázáno. Ale ak chcete, asi to tam uviesť môžete.
