### ISSUE TITLE
Obsah elementu genre v MODS pro jednolivou stranu

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#120]
Dobrý den,

v popisu elementu genre v MODS pro jednotlivou stranu je uvedeno:

_"označuje reprezentativnost strany buď hodnotou reprePage pro reprezentativní, nebo page pro
obyčejnou stranu"._

Mohli byste dovysvětlit, co se rozumí pod reprezentativní a obyčejnou stranou?
Předem děkuji.

S pozdravem
Volodymyr Dyshchyn

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
reprezentívnou stranou sa myslí strana, ktorá dokument reprezentuje napr. pri zobrazení v náhľade. Najčastejšie sa takto označuje titulná strana monografie alebo prvá strana periodika.

**Comment by volodymyrdn** [comment]
Dobrý den,

Ještě se doptám: 
_"Najčastejšie sa takto označuje titulná strana monografie alebo prvá strana periodika."_. Řekneme že je to v 95% případu.  Jak se označuje ve zbylých 5%?

Jak se pak řídí Kramerius při zobrazení dokumentu? Používá stránku označenou jako reprePage jako náhled dokumetnu? 

Děkuji.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
vo väčšine prípadov sa za reprezentatívnu označuje titulná strana alebo prvá strana periodika, ale ak spracovávateľ uzná za vhodnejšiu na zobrazenie napríklad obálku, prípadne akúkoľvek inú stranu, môže ju označiť ako reprePage a teda sa v náhľade zobrazí ona. 
Kramerius vždy zobrazí reprePage ako náhľad dokumentu. V prípade, že žiadna strana nie je takto označená, zobrazí v náhľade stranu, ktorá je označená ako titulná.
