### ISSUE TITLE
Mezinárodní standardy 

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#121]
Dobrý den, 

Můžu se zeptat, z čeho vycházejí pravidla pro popis periodik/monografie? Existují-li nějaké mezinárodní pravidla, nebo kdo vlastně určuje tyto pravidla, zájmena typy stránek a jejich český překlad? Zkoušel jsem najít něco podobného na stránkách Kongresu (http://loc.gov), bohužel ale neúspěšně.

Předem děkuji.

**Comment by PavlinaKocisova** [comment]
Dobrý den, LOC spravuje mezinárodní standardy pro formáty metadat, pravidla pro popis (dále PP) si případně stanovuje národní instituce sama, což v našem případě je Národní knihovna ve spolupráci s MZK. Existence a potřeba pravidel popisu de facto vychází z toho, jakým způsobem má NK nastavené popisování a přijímaní balíků. 

Pravidla popisu se snaží poskytovat uživatelskou příručku, jak popisovat dokumenty, přičemž se snaží co nejvěrněji postihovat realitu materiálu. Je to do velké míry živý materiál, protože nejen v NK, ale i v jiných institucích vznikají situace, které nejsou v PP ještě popsané, a je dobré jejich řešení standardizovat. Návrhy na úpravy PP vychází tedy většinou z reálných situací, a úpravy probíhají jak z našeho vnitřního oddělení digitalizace, tak na základě třeba issues tady na Github. 

Co se týče českých překladů terminologie, většinou vychází z databáze TDKIV (Terminologická databáze knihovnictví a informační vědy, http://tdkiv.nkp.cz).
