### ISSUE TITLE
Periodika 1.8 - možné typy vnitřních části

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#122]
Dobrý den, 

v definicích MD formátů pro digitalizaci periodik na str. č. 48 je uveden seznam možných hodnot typu vnitřní části (atribut **type**, pouze pro **article**). Pak v pravidlech pro popis periodik (v8.4, 20.12.2019) na str.č. 11 je další seznam - Další možné rozšířeni typů stran pro vnitřní část dokumentu - article. 

To znamená, že seznam, uvedený ve standardech není úplný, a má se rozšířit o typy, uvedené v pravidlech? Některé typy se ale duplikují (news, advertisement, atd.).
Typ mainarticle v pravidlech je uveden jako main**A**rticle. Jaký zápis je správný? 

Předem děkuji
Volodymyr Dyshchyn

**Comment by volodymyrdn** [comment]
Dobrý den,

mohli byste odpovědět na tento dotaz? Předem děkuji.

S pozdravem
Volodymyr Dyshchyn

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ospravedlňujem sa za oneskorenie. 
V prípade, ktorý spomínate, miešate spolu dve rozdielne veci. Na str. 48 sú uvedené hodnoty atribútu type elementu mods:genre pre článok, a tieto hodnoty hovoria o type článku ako takom (napr. či je článok obsahom, hlavným článkom, alebo je jeho typ nešpecifikovaný). "Další možné rozšíření typů stran pro vnitřní čast dokumentu - article" (str.61) obsahuje zoznam typov strán, ktoré sa môžu použiť pri popise strán nejakého článku (teda či daná stránka obsahuje napr. nekrológ, rozhovor či abstrakt). V tomto druhom prípade sa zoznamy v PPP a DMF zhodujú.
