### ISSUE TITLE
Periodika 1.8 Typy strany

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#123]
Dobrý den, 

v pravidlech pro popis periodik (v8.4, 20.12.2019) na str. č. 8 je seznam typů stran, které je nutné popsat. Do toho to seznamu patři i typ strany **rejstřík**. Ale detailní popis tohoto typu strany se objevuje až v sekci dalších typů stran, které se mohou použít v závislosti na požadavku stupně rozsahu popisu (str. č. 10) Mohli byste proto upřesnit, kam patří typ strany rejstřík (do nutných, nebo do těch dalších) ?
Předem děkuji.

S pozdravem
Volodymyr Dyshchyn

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

tieto dve časti nemôžete brať ako rozdelenie na "povinné" a "nepovinné" typy strán, nikdy to tak zamýšľané nebolo. Napríklad v prvom časti zoznamu je niekoľko typov strán, ktoré nie sú označené ako povinné a naopak. Dalo by sa povedať, že tie uvedené na začiatku sú významnejšie a častejšie používané, ale ich poradie nemá nič spoločné s tým, či sú povinné alebo nie. 
Pod formuláciou "Další typy stran, které se mohou použít v závislosti na požadavku stupně rozsahu popisu" sú uvedené menej časté typy strán (niektoré z nich sa ale musiac popísať) alebo strany, u ktorých si zadávateľ napríklad môže povedať, že sa v rámci popisu strany nemusia označovať strany, na ktorých sú napr. errata apod.). 
Za bernú mincu prosím považujte to, čo je uvedené v "stranách které je nutné popsat".
