### ISSUE TITLE
Monografie 1.4 typy stran

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#124]
Dobrý den, 

v pravidlech pro popis monografii (v2.2, 20.12.2019) na str. č. 6 mezi typy stran, které je nutné popsat, je **reprezentace**.  Detailní popis ale nemá, ale je tu popis pro Reprezentativní obálku knihy. Tak že, jedná se o to samé? Tzn., reprezentace = Reprezentativní obálka knihy?

Pak je tu stejná nejasnost s typem strany **rejstřík** jako tady:  https://github.com/NLCR/Standard_NDK/issues/123

Předem děkuji. 

S pozdravem 
Volodymyr Dyshchyn

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
áno, jedná sa o ten istý typ strany.
