### ISSUE TITLE
Element TypeOfResource v monografii 

### ISSUE THREAD

**Issue by isenkyr** [NLCR/Standard_NDK#126]
Dobrý den,

aktuálně zpracováváme monografii, která má v marc záznamu uveden typeOfResource still image. Ve standardu 1.3.2 a vyšším je povolena hodnota text a komplexní validátor také tuto hodnotu vyžaduje a hlásí chybu. Chci se zeptat jak postupovat? Změnit hodnotu na text? Anebo nechat hodnotu jak je a v budoucích verzí standardu by se rozšířil výčet povolených hodnot pro element typeOfResource?

Přikládám návěští marc21 záznamu

01314nkm a2200445 i 4500

Děkuji I.Šenkýř

**Comment by MirkaBenackova** [comment]
Dobrý deň, 

môžem sa spýtať, čo je to za dokument? Úplne si totižto neviem predstaviť monografiu, ktorá má ako typeOfResource "still image".

Tak ako tak, prepíšte prosím danú hodnotu na "text". Hodnota v typeOfResource by mala vychádzať z katalogizačného záznamu, ale u monografii sa očakáva hodnota "t", tj. "text"; je to najzmysluplnejšie. Nad rozšírením povolených hodnôt v typeOfResource preto do budúcna neuvažujeme.

**Comment by isenkyr** [comment]
Dobrý den,

děkuji za odpověď. Ještě přikládám informace o dokumentu v marc21 

01314nkm a2200445 i 4500
001 0947572
003 CZ-LiKVK
005 20180924150255.0
007 ta
008 170213s1911----gw------------|||-|-ger--
020    $q (Volné listy v přebalu)
040    $a LIA001 $b cze $e rda
080    $a 741/744 $2 MRF-sel
100 1  $7 li_us_auth*p0056829 $a Führich, Joseph von, $d 1800-1876 $4 aut
245 10 $a Er ist auferstanden! : $b zehn Zeichnungen / $c von Joseph Ritter von Führich
264  1 $a Stuttgart : $b Verlag von Walter Seifert, $c [1911]
300    $a 1 soubor reprodukcí (11 listů) ; $c 27 cm
336    $a statický obraz $b sti $2 rdacontent
336    $a text $b txt $2 rdacontent
337    $a bez média $b n $2 rdamedia
338    $a list $b nb $2 rdacarrier
490 0  $a Religiöse Kunst ; $v Dritte Mappe
500    $a Volné listy ve společném papírovém přebalu
648  7 $7 li_us_auth*o0000059 $a 19. století $2 czenas
650  7 $7 li_us_auth*0435492 $a sakrální umění $y 19. stol. $2 czenas
650  7 $7 li_us_auth*h0012901 $a kresba $y 19. století $2 czenas
650  7 $7 li_us_auth*0495508 $a rakouská kresba $y 19. století $2 czenas
653 0  $a religiöse Kunst $a Zeichnungen
655  7 $7 li_us_auth*f0001238 $a soubory reprodukcí $2 czenas
910    $a LIA001

I.Šenkýř

**Comment by MirkaBenackova** [comment]
Ďakujem za odpoveď. 
Hodnotu v typeOfResource by som prepísala, nakoľko zmeniená obrazová publikácia vyšla ako monografia.
