### ISSUE TITLE
Periodika 1.8 - typy stran - duplicitní advertisement

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/Standard_NDK#127]
Dobrý den, 

v pravidlech pro popis periodik v8.4 na str.č. 8 je uveden typ strany Inzerce (**advertisement**), 
a pak na str.č. 11 je uveden typ strany reklama (**advertisement**). Není v tom nějaký překlep? 
Děkuji

S pozdravem 
Volodymyr Dyshchyn

**Comment by PavlinaKocisova** [comment]
Dobrý den, není. Tyto typy stran jsou vyjádřeny stejnou hodnotou.

**Comment by erikamirova** [comment]
Dobrý den,

koukám, že v pravidlech je pod charakteristikou reklamy také inzerce. 

Reklama je placená nebo neplacená propagace výrobku, služby, společnosti, obchodní značky
nebo myšlenky různými prostředky (např. plakáty, inzeráty, nápisy, světla aj. oznámení),
mající obvykle za cíl zvýšení prodeje. 

Nebude lepší zrušit označení typu strany inzerce a vše dát pod reklamu? Takhle to může být matoucí. Co se týče angličtiny, tak reklamu mají jako advertisement a inzerci jako classified ad, tím pádem považují reklamu za nadřazenou. Navíc u některých periodik se reklamy a inzerce vyskytují na jedné straně. 

Pěkný den

Erika Mirová

**Comment by PavlinaKocisova** [comment]
viz naše odpověď výše.

**Comment by erikamirova** [comment]
Ano, mají stejnou hodnotu, ale proč mít tedy dva výrazy v češtině a jeden v angličtině? Nebylo by lepší mít na to jeden výraz i v češtině?
