### ISSUE TITLE
Typ strany: obsah

### ISSUE THREAD

**Issue by erikamirova** [NLCR/Standard_NDK#128]
Dobrý den,

jsem ráda, že jsou v nových pravidlech doplněny charakteristiky jednotlivých stran, akorát u obsahu je to trošku nejasné. Viz:

Obsah = Výčet názvů a podnázvů částí dokumentu v pořadí, jak se v dokumentu vyskytují, s označením stránky nebo sloupce, kde příslušné části začínají. 

Dosud jsme jako obsah označovali i toto:
- Obsah s výčtem kapitol v dokumentu neodkazující na jednotlivé stránky (typicky skripta - tam jsou pouze čísla kapitol, ne stránek).
- Jakákoliv strana, která je v dokumentu označena slovem „obsah“, přestože neodkazuje na stránky (např. u výročních zpráv).

Máme to tedy přestat označovat? Myslím si, že pro uživatele je vhodné označit za obsah i strany, které neodkazují na jednotlivé stránky, protože to pomáhá v lepší orientaci v dokumentu (třeba u těch skript i výčet kapitol může pomoci). 

Děkuji za rady.

Erika Mirová

**Comment by zabak** [comment]
Souvisí to i s možností využít takové stránky pro obalkyknih.cz, protože tam nejde o to, na jaké straně se kapitola nachází, ale o to, že obsah může být volně dostupný a přístupný i přes katalogy knihoven.

**Comment by PavlinaKocisova** [comment]
Dobrý den, pokračujte v označování. Definice nemá úplně ostré okraje, takže pokud dokument obsahuje stranu, která je fakticky obsahem, označte ji tak.

**Comment by erikamirova** [comment]
Dobře, děkuji za rychlou odezvu. 

A jak je to, prosím, s upřednostňováním stran, pokud se objeví dva typy? V pravidlech není specifikován vztah mezi předními deskami a obsahem. Občas se totiž stává, že máme na předních deskách obsah. Doteď jsme upřednostnil obsah, protože dokument obsahoval i titulní stranu (skoro totožnou s předními deskami). Navíc přední desky i obsah jsou nastavovány jako veřejné.

**Comment by PavlinaKocisova** [comment]
Na tyto případy slouží element <genre> na úrovni strany, kam se jednoduše vyplní, zda je stránka reprezentativní (tj. namísto obálky) nebo ne (viz např. s. 81 v DMF pro monografie 1.4). Typ strany pak může být jakýkoliv, obsah. O tom, zda se v reprezentaci zobrazí na prvním místě, totiž rozhoduje právě hodnota výše.

**Comment by erikamirova** [comment]
Ano, tomu rozumím, takto to praktikujeme. Takže nevadí, když upřednostníme obsah před předními deskami s tím, že stranu necháme jako reprezentativní? --> Např. na předních deskách mám obsah, takže dám typ strany obsah a plus ji označím jako reprezentativní.

**Comment by erikamirova** [comment]
A teď jsme ještě narazili na periodikum, které má na obálce obsah. V tomto případě bych asi upřednostnila obálku, protože obsah je automaticky veřejný, takže bychom pak mohli omylem zveřejnit něco, co bychom neměli.

Co myslíte?

**Comment by PavlinaKocisova** [comment]
Pokud existuje u dokumentu obálka, má vždy přednost před obsahem. Pokud obálka není, lze jako reprezentativní označit kteroukoliv jinou stranu dokumentu.
