### ISSUE TITLE
Rendition + Pocet stran v epub

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/Standard_NDK#131]
Ahoj,

ako je planovane specifikovat pre prijem ebornov pole `rendition`?

je to povinne` pre-paginated`, alebo je povoleno `reflowable`? Ako sa potom specifikuje v jednotlivych pripadoch pocet stran a jeho povinnost ako metadata?

**Comment by godnat** [comment]
Jsou povolené formáty Epub2 i Epub3 a Epub2 umí jen reflowable zobrazení, takže předpokládáme, že bude fixed-layout i reflowable. V metadatech je element pro zapsání počtu stránek, plní se automatizovaně nástrojem epubcheck, ten ale nezjistí počet stránek u reflowable verze, takže u Epub formátu se vyplňuje počet znaků.  U Epubů se nepopisují jednotlivé strany ale celý dokument/soubor.
