### ISSUE TITLE
Emonografie - kapitoly

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#133]
Na schůzce pracovní skupiny k epublikacím jsme se bavili o tom, jak by se dala propojit metadata kapitoly s konkrétní stránkou v PDF v emonografii. 

Bylo by to užitečné pro případy, když je potřeba popsat emonografii, nejen na úroveň titulu, ale také na úroveň kapitol. 

Informace o propojení by měla být uvedena ve strukturální mapě, jde o to, jak přesně by to mělo vypadat. 

Kapitoly by se měly měly odkazovat na ten samý soubor, protože je jen jeden (jedno PDF, příp. epub na emonografii). Příklad, jak by to mohlo vypadat (pokud je to špatně, klidně upravte).

<mets:structMap>
      <mets:div ID="VOLUME_0001" LABEL="Simpsonovi a jejich matematická tajemství" DMDID="MODSMD_VOLUME_0001" TYPE="VOLUME">
            <mets:div ID="CHAP_0001" ORDER="0" LABEL="Název"
DMDID="MODSMD_CHAPTER_0001" TYPE="CHAPTER"/>
            <mets:div ID="CHAP_0002" ORDER="1" LABEL="Název 2"
DMDID="MODSMD_CHAPTER_0002" TYPE="CHAPTER"/>
            <mets:div ID="DOCUMENT_0001" LABEL="oc_aba007-0000co"
TYPE="DOCUMENT">
                  <mets:div ID="FILE_0001" TYPE="FILE"><mets:fptr
FILEID="oc_aba007-0000co"/>
                  </mets:div>
            </mets:div>
      </mets:div>
</mets:structMap>

Je ale potřeba vyřešit, kam uvést pořadí strany v PDF, kde konkrétní kapitola začíná. Jedna z možností je mods element part, kam by se dal přidat atribut "pageIndex" podobně jako je to u tištěných dokumentů. Další možnost je, že to číslo (pořadí) bude uvedeno přímo v té strukturální mapě, ale nevím, jak by to konkrétně mělo vypadat.

**Comment by FilipPavcik** [comment]
Dobrý deň,

nižšie posílám odkaz na danou část kapitoly v DMF pro e-monografie po zapracovaných zmenách. Na úroveň kapitoly bol pridaný kontejnerový element mods:part dvakrát: prvýkrát sa zapíše "pageNumber" a pak "pageIndex". 

https://docs.google.com/document/d/15Ad1tWCfrQlewrlYpohYEA-8IVRqrEUU/edit?usp=sharing&ouid=111634752806429404827&rtpof=true&sd=true

**Comment by FilipPavcik** [comment]
Návrh, ktorý je uvedený vyššie bol prediskutovaný na schůzke PS pro epublikace a bol pridaný do DMF pro e-monografie verze 2.4. Issue zatváram.
