### ISSUE TITLE
MODS na úrovni PAGE - problém importu do Krameria - nezapíše se číslený popis strany

### ISSUE THREAD

**Issue by MarekFiser** [NLCR/Standard_NDK#136]
Hlavní METS má dle aktuálního standardu na úrovni strany v označení čísla strany atribut **type=„page number“**. To ale nesouhlasí s podobou zápisu čísla strany v MODS Krameria, kde je atribut **type="pageNumber"**. Patrně následkem toho se veškerá data zpracovaná v aktuálním standardu zobrazují v Krameriovi bez čísla stránky (pořadí je správné, neboť podoba označení type="pageIndex" u obou souhlasí). Našel jsem, že se to řešilo v #112, ale ne v souvislosti s Krameriem.

**Comment by MarekFiser** [comment]
Tak otestováno, skutečně se po opravě atributu zindexují stránky korektně, tudíž příčinou je současná podoba specifikace.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
je to tak ako zmieňujete vyššie; aktuálne nie sú hodnoty v zmienenom atribúte type kompatibilné. Ako píšeme v issue 112, o probléme vieme, pri najbližšej aktualizácii to bude v štandarde zjednotené. Tam uvedené sa vzťahuje aj na použitie pageIndex a page number na ostatných úrovniach (viď issue #117). Ďalšie info k plneniu týchto polí je aj v #125.   
Kramerius a plnenie metadát sa v tomto prípade môžu riadiť správnou variantou uvedenou tu, nie DMF.

**Comment by vjirousek** [comment]
Dobrý den,
indexace na straně Krameria by měla být vyřešena, viz: https://github.com/ceskaexpedice/kramerius/issues/760#issuecomment-668016698
Na straně standardů bude opraveno v DMF pro periodika 1.9 a DMF pro monografie 2.0.

**Comment by vjirousek** [comment]
Opraveno v:
- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022
