### ISSUE TITLE
rozlišení RDA/AACR2 u eborn-periodika 2.3 a eborn-monografie 2.3

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#139]
V [DMF eborn-periodika 2.3](https://old.ndk.cz/standardy-digitalizace/DMF_ebornperiodika_2.3.pdf) a [DMF eborn-monografie 2.3](https://old.ndk.cz/standardy-digitalizace/DMF_ebornmonografie_2.3.pdf) v pravidlech pro bibliografická metadata často chybí požadavek na _mods:recordInfo/mods:descriptionStandard_, anebo je tento element (resp. jeho rodič) nepovinný.
Obsah elementu (hodnoty "rda", nebo "aacr") slouží k rozlišení, podle kterých pravidel je záznam katalogizován. A tedy i co pro ten konkrétní MODS platí. Konkrétně:

DMF eborn-periodika 2.3:
- title-rda: nepovinný
- title-aacr: nepovinný
- volume-rda: chybí
- volume-aacr: chybí
- issue-rda: nepovinný (i recordInfo)
- issue-aacr: nepovinný (i recordInfo)
- article-rda: chybí (i recordInfo chybí)
- article-aacr: chybí (recordInfo nepovinný)
- supplement-rda: chybí (i recordInfo chybí) 
- supplement-aacr: chybí (i recordInfo chybí) 
 
DMF eborn-monografie 2.3:
- title-rda: chybí
- title-aacr: chybí 
- volume-rda: nepovinný
- volume-aacr: nepovinný
- chapter-rda: chybí (recordInfo nepovinný)
- chapter-aacr: chybí (recordInfo nepovinný)
- supplement-rda: chybí (i recordInfo chybí)
- supplement-aacr: chybí (i recordInfo chybí) 

Nejspíš se to týká i ostatních DMF.

Pokud záznam vytvářím, tak vím, podle jakých pravidel to dělám. Ale pokud mám záznam validovat, musím vědět, podle čeho se řídit. Třeba u čísla eborn-periodika 2.3: mám se řídit tabulkou od strany 21 pro RDA a tudíž mods:name/mods:namePart je nepovinný (MA), anebo tabulkou od strany 42 pro AACR2 a tedy je mods:name/mods:namePart povinný (M)?

Přimlouval bych se za to, aby _mods:recordInfo/mods:descriptionStandard_ byl vždy povinný.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za detailné spísanie. Tejto záležitosti sme si vedomí, možný problém z toho prameniaci je spomenutý aj v #143 . Do budúcna sa to teda rozhodne bude riešiť, a povinnosť mods:descriptionStandard bude pravdepodobne zvýšená na M na všetkých úrovniach.

**Comment by FilipPavcik** [comment]
V najnovšie vydaných štandardoch pre e-publikácie boli povinnosti pre zápis elementu `descriptionStandard` upravené podľa návrhu vyššie, ktorý bol prerokovaný a odsúhlasený na schôdzke Pracovnej skupiny pre e-publikácie. To isté platí aj pre ďalšie elementy v rodičovskom elemente `mods:recordInfo`. Issue teda zatváram.
