### ISSUE TITLE
Word a Character Confidency

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#14]
```
Word a Character Confidency v ALTU - povinnost?

Abbyy dodává výsledek na úroveň stránky a to ještě odhaduje, co si 
"myslí", že rozpoznala.

Predelat na nepovinne?
```

Original issue reported on code.google.com by `pavla.svastova@gmail.com` on 17 Dec 2012 at 7:41

**Comment by vjirousek** [comment]
V návaznosti na projednání na PS skupině pro textové dokumenty issue uzavírám jako v tuto chvíli nepotřebné. V případě potřeby je možné znovuotevřít.
