### ISSUE TITLE
Zvukové dokumenty 0.4 <mods><genre>

### ISSUE THREAD

**Issue by SykoraLukas** [NLCR/Standard_NDK#141]
Ve standardu pro [zvukové dokumenty 0.4](https://old.ndk.cz/standardy-digitalizace/DMF_zvuk_gramo_0.4_final.pdf) na straně 31 je nejspíše chybně zapsán element `<issuance>` pod element `<genre>`.

![image](https://user-images.githubusercontent.com/27210823/110474871-7a6e2300-80e0-11eb-8b32-91ef0f601f25.png)

**Comment by vjirousek** [comment]
Opraveno v DMF pro gramofonové desky ve verzi 0.5 z 10. 10. 2022.
![obrazek](https://user-images.githubusercontent.com/22765973/195617424-bc3db526-5ad2-452a-acf4-0aa7069f57c5.png)
