### ISSUE TITLE
Zvukové dokumenty 0.4 <mods><originInfo><dateOther>

### ISSUE THREAD

**Issue by SykoraLukas** [NLCR/Standard_NDK#142]
Ve standardu pro [zvukové dokumenty 0.4](https://old.ndk.cz/standardy-digitalizace/DMF_zvuk_gramo_0.4_final.pdf) na straně 33 je nejspíše chybně zapsán element <dateOther><type>. Type manufacture je zde chybně zapsán do pole 264_2, ale má být 264_3.

![image](https://user-images.githubusercontent.com/27210823/110476725-9672c400-80e2-11eb-977d-8f1335f99d45.png)

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za upozornenie. Máte pravdu, jedná sa o preklep. Hodnota atribútu type "manufacture" sa u tohto elementu má použiť v prípade výskytu poľa 264_3, tak ako je to uvedené vyššie. 
Preklep bude pri najbližšej aktualizácii odstránený.

**Comment by vjirousek** [comment]
Opraveno v DMF pro gramofonové desky ve verzi 0.5 z 10. 10. 2022.
![obrazek](https://user-images.githubusercontent.com/22765973/195613906-c1b122ec-e9c2-4378-9b98-6bcb48b5de5a.png)
