### ISSUE TITLE
neprítomnosť elementu descriptionStandard na úrovni SUPPLEMENT v monografiích 1.4

### ISSUE THREAD

**Issue by MirkaBenackova** [NLCR/Standard_NDK#143]
V aktuálnom DMF 1.4 nie sú na úrovni prílohy predpísané polia pre descriptionStandard. Pokiaľ komplexný validátor toto pole nenájde, validuje danú úroveň podľa AACR2. Na úrovni SUPPLEMENT sa ale dáta môžu líšiť v RDA a AACR2 v poli mods:physicalDescription a v prípade, že dokument obsahuje v danom poli napr. hodnoty atribútu type ako „rdamedia“ a pod. typické pre RDA, validátor to kvôli chýbajúcej informácii o katalogizačnom štandarde vyhodnotí ako chybu a vypíše ERROR. 
Pri validácii preto prosím ignorujte popísaný error. Táto nezrovnalosť bude odstránená v ďalšej aktualizácii DMF.

**Comment by fremrovaK** [comment]
V DMF pro monografie 2.1 byl na úrovni SUPPLEMENT doplněn nadřazený element <recordInfo> a jeho vnořené subelementy včetně elementu <decriptionStandard>.
