### ISSUE TITLE
<mods><genre> obecně - nedochází ke konverzi pole 655

### ISSUE THREAD

**Issue by zabak** [NLCR/Standard_NDK#145]
Je to zmíněno v #141 ve vztahu ke zvukovým dokumentům ale narazili jsme na to zrovna u monografií, kde údaj o žánru v poli 655 výrazně zhoršuje možnosti vyhledávání beletrie. Prosím o opravu ve všech typech dokumentů. Toto považujeme za natolik závažný problém, že bude nutné zpětně žánr doplnit i do již digitalizovaných dokumentů.

**Comment by PavlinaKocisova** [comment]
Dobrý den, děkujeme za zpětnou vazbu. Momentálně ověřujeme, z jakého důvodu se pole nepřevádí.

**Comment by annie-cz** [comment]
Posunulo se to prosím nějak?

**Comment by vjirousek** [comment]
Z hlediska WF je řešeno v rámci https://gitlab.nkp.cz/orpa/ndk/wf/wf-supp/-/issues/294. Odpovídající rozšíření popisu DMF by mělo proběhnout v nových verzích plánovaných na začátek letošního roku.

**Comment by vjirousek** [comment]
Popis mapování z pole 655  do elementu `<mods:genre>` byl doplněn do:

- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022
