### ISSUE TITLE
originInfo/issuance u periodik 

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#148]
Při úpravách v ProArcu jsme teď narazili na to, zda v originInfo/issuance u periodik mají být tři možnosti (continuing, serial a integrating resource), nebo jen dvě (serial a integrating resource).

DMF připouští tři možnosti. 
A v Kongresovce se to liší - v Guidelines (https://www.loc.gov/standards/mods/userguide/origininfo.html) mají všechny tři možnosti vč. continuing, ve schématu tady (https://www.loc.gov/standards/mods/v3/mods-3-7.xsd) taky, ale v šablonách marc-mods je (zřejmě už od r. 2014) změna.

Tam překlápí obě hodnoty z LDR/07 s (serial) i b (serial component part) jako “serial”.

 Revision 1.94 - Leader 07 b changed mapping from continuing to serial tmee 2014/02/21

<xsl:when test="$leader7='b' or $leader7='s'">serial</xsl:when>

Můžete se na to prosím podívat, popř. i poptat v LOC, proč je tam ta nekonzistence a jak je to vlastně správně?

**Comment by PavlinaKocisova** [comment]
Dobrý den, děkuji za připomínku, řešíme to.

**Comment by luckajirku** [comment]
Nastal v tomto nějaký posun?

**Comment by PavlinaKocisova** [comment]
Dobrý den, zatím ne, nicméně, pokusíme se kontaktovat LOC a požádat o vyjádření. Děkuji za pochopení.
