### ISSUE TITLE
upresnenie pokynov k plneniu mods:recordChangeDate

### ISSUE THREAD

**Issue by MirkaBenackova** [NLCR/Standard_NDK#149]
Pri najbližšej aktualizácii všetkých DMF sa bude upresňovať pokyn k vyplňovaniu poľa mods:recordChangeDate. Teraz je v pokynoch veta, že čas sa udáva na úroveň minút - z tejto formulácie ale nie je jasné, či sa požaduje udávať čas výlučne na minúty, alebo aspoň na minúty. V dátach sa aktuálne bežne uvádza čas aj na sekundy, takže v ďalšej úprave bude formulácia upravená na "alespoň na úroveň minut", aby výklad bol naprosto jednoznačný.  

### Postup zapracování:
- [x] DMF pro periodika
- [x] DMF pro monografie
- [x] DMF pro gramodesky
- [x] DMF pro fonoválečky
- [ ] DMF pro e-monografie
- [ ] DMF pro e-periodika
- [ ] DMF pro skládaná e-periodika

**Comment by rzeh4n** [comment]
Stejná situace je u mods:recordCreationDate.

**Comment by FilipPavcik** [comment]
Upravené v najnovšie vydaných štandardoch pre e-publikácie, tj. v DMF pro e-monografie 2.4, DMF pro e-periodika 2.4 i v DMF pro skládaná periodika 1.1. Issue zatváram.
