### ISSUE TITLE
nefunkčný resolver

### ISSUE THREAD

**Issue by MirkaBenackova** [NLCR/Standard_NDK#151]
Dobrý deň, 
nakoľko kvôli nedávnym technickým problémom nefungujú niektoré systémy v rámci NK, touto cestou Vás chceme informovať, že dočasne je nedostupná služba resolver. Na náprave sa pracuje, a o návrate do plného provozu Vás tu budeme informovať. Ďakujeme sa pochopenie.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
činnosť resolveru (ako ostrého, tak testovacieho) bola obnovená. 
Ak s ním máte naďalej problémy alebo čokoľvek nefunguje, prosím, napíšte nám o tom informáciu sem, stále nám totiž nefungujú pracovné e-maily. 
Ďakujeme za pochopenie!

**Comment by isenkyr** [comment]
Dobrý den,

resolver nefunguje na adrese https://resolver.nkp.cz/api/v6/ Na adrese https://resolver.nkp.cz/api/v5/ je vše v pořádku. Že je k dispozici nové API 6 jsem zjistil před několika týdny, tak jsem se rozhodl na něj přejít. Prosím o info zda bude API v6 také v provozu?
Děkuji I.Šenkýř

**Comment by isenkyr** [comment]
Dobrý den,

ještě jsem zkoušel testovací resolver s api 6 a tam to vypadá OK. https://resolver-test.nkp.cz/api/v6/

**Comment by godnat** [comment]
Dobrý den,

ano api v6 bude na produkčním resolveru také v provozu, jen co na tento resolver nasadíme novou verzi aplikace. Nová verze aplikace je nasazena na testovacím resolveru, kde jí ještě ladíme. Nasazení na produkční resolver předpokládáme v létě, snad v první polovině léta.

**Comment by isenkyr** [comment]
Dobrý den,

to je zvláštní, protože api v6 bylo již nasazeno i na produkčním resolveru. My ho používali dokud nedošlo k výpadku z minulého týdne. Každopádně děkuji za informace.

**Comment by godnat** [comment]
Děkuji za zprávu, tak to asi bude ještě v něčem jiném,. Prověříme to, api6 se vrátí, ale zatím nedokážeme říct kdy, ale je to v pořadí.

**Comment by isenkyr** [comment]
Děkuji.

**Comment by vjirousek** [comment]
Mělo by být vyřešeno, v případě dalších problémů s Resolverem prosím nové issue zde: https://github.com/NLCR/CZIDLO/issues
