### ISSUE TITLE
Údaje o tisku

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#152]
Dobrý den,
všiml jsem si ve standardech, že u záznamu dle AACR2 není uvedeno nic o údajích o tiskaři. Je tam jen zminka v elementu publisher, ze jmeno entity,ktera dokument vydala, vytiskla odpovida poli 260 b. Tiskař by ale mel patrit do podpoli  e, f, g.
Znamená to, že se nepočítá s prevadenim tiskařských udaju do metadat? Nebo by mely byt v metadatech ve vydavatelských podpolich a, b, c, i kdyz v katalogizacnim zaznamu budou ve svych podpolich e, f, g?

Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
primárne je to dané nedokonalosťou popisu v AACR2, kedy úplne nejde explicitne udať, že sa jedná o tiskařské údaje. Podľa mappingu LOC sa polia, ktoré udávate, mapujú štandardne do placeTerm/publisher/dateOther bez bližšej špecifikácie.  
Rozhodne sa tá informácia nemá vpisovať do iných polí ako pre to určených; zároveň to určite neznamená, že sa s týmito poľami nepočíta. 
Môžem sa spýtať, či sa u vás jedná o často vyskytujúcu sa záležitosť, resp. mali by ste záujem o to, aby sa mapovanie z týchto polí v DMF explicitne udávalo?

**Comment by Drahotussky** [comment]
Dobry den, dostal jsem se k tomuto problemu,kdyz jsem narazil na tiskarske udaje v zaznamu RDA. V starsich bibliografickych zaznamech se tiskarske udaje casto nevyskytuji. Myslim, ze by bylo prinosne,kdyby standardy k zaznamu dle AACR2 presne udavaly, z kterych podpoli se tiskarske udaje berou a kam se prevadi.
Uvadite pole dateOther, to se ale vyskytuje jen u zaznamu dle RDA.

**Comment by MirkaBenackova** [comment]
Ďakujeme za návrh, zapísala som to na zoznam aktualizácii.  
U toho dateOther som hovorila o oficiálnom mappingu LOC. Pokiaľ je niečo prípustné pre LOC, NDK to akceptuje aj keď to nie je explicitne uvedené v DMF.

**Comment by vjirousek** [comment]
Možnost přebírání údajů o tiskaři z polí 260 $e, $f a $g je v nově zmíněna v:

- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022

Mapování do MODS viz LoC:

![obrazek](https://user-images.githubusercontent.com/22765973/196243389-46677825-77b9-41da-b0ce-4c3c5f8be76b.png)
(https://www.loc.gov/standards/mods/v3/mods-mapping-3-6-revised-2020.html)
