### ISSUE TITLE
titleInfo s type abbreviated u monografií

### ISSUE THREAD

**Issue by honza-rychtar** [NLCR/Standard_NDK#153]
U periodik je výčet hodnot titleInfo/@type
- abbreviated - pole 210
- alternative – pole 246
- translated – pole 242
- uniform – pole 130 resp. 240

U monografií
- alternative – pole 246
- translated – pole 242
- uniform – pole 130 resp. 240

Je to záměr, že u monografií chybí možnost **abbreviated - pole 210**?

**Comment by vjirousek** [comment]
Hodnota "abbreviated" doplněna v DMF pro monografie 2.0 z 10. 10. 2022
![obrazek](https://user-images.githubusercontent.com/22765973/195613108-77993653-5918-42b5-bb27-f97a2a39ee30.png)
