### ISSUE TITLE
mutační vydání periodik

### ISSUE THREAD

**Issue by JanHouserek** [NLCR/Standard_NDK#155]
Podle mých informací takový požadavek již padl, pokud se nepletu, v rámci projektu PerMonik. Chtěl jsem ho zapsat i sem na GitHub. Konrétní návrh realizace požadavku nemám, ale hodilo by se nám na úrovni vydání standardizovat zápis pro mutační vydání periodik. 

Pro uvedení do problematiky:

Mutační vydání se zpravidla značí různými symboly v různém počtu. Nejčastěji tečka, čvereček nebo hvězdička, ale také nic! Symboly bývají viditelně umístěny v hlavičce titulu, takže není možno je zaměnit s nějakou grafickou úpravou. Nejčastěji se objevuje dělení na mutace a dále na mutační vydání po roce 1945, a to u rozsáhlých celostátních titulů. Nejde ale o pravidlo, objevují se i mnohem dříve, ale ne s takovou pravidelností jako v 60. a 70. letech.

Ještě existuje jistý předpoklad, opět to nelze aplikovat pravidelně, ale v době největšího boomu, tedy v těch 60., 70. a vlastně až do roku 1990, lze z dílčích článků vypozorovat, že jednotlivá mutační vydání byla určená pro různé spádové oblasti, přičemž čím větší počet symbolů u daného mutačního vydání byl, tím nižší číslo vydání představoval, a byl určen pro tu nejširší oblast záběru. Tzn. třeba 5* bylo 1. vydání  a odpovídalo územní oblasti Brno-venkov.

Například: 

Metatitul:		Mladá fronta
Mutace:		Praha / Brno / Ostrava
Mutační vydání: 	objevují se různé způsoby značení  
nejčastější označení: tečky •, hvězdičky *, čtverečky ▪️

**Comment by luckajirku** [comment]
Díky moc za otevření tohohle tématu. Jen doplním, že se to vyskytuje nejen u celostátních, ale i u regionálních titulů. 
Máme tu třeba Pochodeň, která vycházela v jen v rámci VČ kraje minimálně ve dvou mutacích - z hlavičky ani tiráže se nic poznat nedá, ta je až na ty tečky/hvězdičky stejná. Procházeli jsme katalogy, bibliografické soupisy atd. a nedopátrali se ničeho, čeho bychom se mohli chytit, abychom měli jistotu. Jen se domníváme podle obsahu, že vycházela verze celokrajská + druhá pro Hradec+Pardubice (ale je možné, že jich bylo i více).
V pravidlech je teď jen toto: "Regionální mutace se skenují zvlášť jako samostatný titul, v případě, že už jsou
naskenovány spolu, řadí se abecedně (pražské vydání, severočeské vydání, západočeské…)." Což je aplikovatelné spíš u těch celostátních deníků, kde je to většinou i uvedené nebo je to jasné, co to je za mutaci. 
Ty mutace regionálních titulů pak jsou trochu složitější, protože tam to někdy můžeme fakt jen odhadovat. Když máme třeba tu Pochodeň, tak tam víme s jistotou, že existují min. dvě mutace v letech 1963-65. Ale nikdy nejde o celé strany, jen sem tam se liší článek. Např. v roce 1963 se liší NĚKTERÉ články v rubrice Sport (s. 4 nebo 8), v roce 1965 pak některé články na stranách 3 a 4. Někdy to vyžaduje pozorné hledání, může se to lišit klidně jen jedním několikařádkovým článkem v celém čísle. Dál se občas stává, že článek, který byl v jednom čísle v jedné verzi, se pak vyskytne po čase v té druhé ve stejném znění v úplně jiném čísle. 
Navíc - jak postupovat v případě, že nemáme ani jednu mutaci kompletní a hlavně opravdu nemáme jistotu, ke které mutaci ten který výtisk patří. V tomhle konkrétním případě bych asi uvítala nějakou možnost přihodit k výtisku "variantní" strany tam, kde se to liší. Až se bude standardizovat, je potřeba vzít v potaz i takové případy (a určitě nebudeme s takovým periodikem sami).

**Comment by zabak** [comment]
Bojím se, že z hlediska digitalizace bude nejlevnější způsob jak identifikovat takto malé rozdíly to, že se to celé znovu naskenuje a porovná strojově s už existujícími čísly. Podle toho jakou prioritu tomu dáme to vidím na 5-15 let, než to budeme schopni takto dělat.

**Comment by JanHouserek** [comment]
Mně v této fázi přijde užitečné mít nepovinně možnost do metadat zapsat symbol pro mutační vydání v případech, kdy to lze jednoznačně určit ("uvidím v hlavičce tituláku 2 čtverečky, tak je zapíšu").

**Comment by PavlinaKocisova** [comment]
Dobrý den, ano, tato problematika se řeší v rámci projektu PerMonik. Se standardizovaným zápisem mutačních vydání periodik do budoucna počítáme. V současné době ještě není finální podoba zatím známá, ale obecně vzato jsou dva možné přístupy, přičemž je nutné počítat s tím, že MODS nemá specifický element, který by se k tomu dal využít. 

První varianta je použít subelement v <titleInfo>-><partName>, do kterého by se příslušné znaky/symboly vložily. Nevýhodou je menší uživatelská přívětivost - zápis není dedikovaný jenom pro mutační vydání. Nicméně, řešení je snadno aplikovatelné. 

Druhá varianta počítá s tím, že by se v jednotlivých úrovních ISSUE zkopíroval celý <titleInfo> kontejner, do kterého by se pak vložil atribut otherType="mutational edition" a do elementu "partName" potom rozlišovací symboly. 
Tato varianta je asi komplikovanější, nicméně, přesněji mutační vydání odlišuje od běžných, je metadatově specifičtější. 

Je potom asi k diskusi, jaké jsou možnosti popisu i ze strany digitalizujících institucí, případně, co by kdo preferoval z hlediska užitečnosti.

**Comment by PavlinaKocisova** [comment]
Dobrý den, doplnila jsem post výše o elementy, které Github vymazal. Omlouvám se, opravovala jsem to už po publikování, ale obrázky s ukázkami kódu zmizely také, přikládám je tedy znovu. 

![mutace](https://user-images.githubusercontent.com/26895177/127458983-a4271b77-ea85-4fa0-9bb5-98bfcd79d281.png)
![mutace2](https://user-images.githubusercontent.com/26895177/127459036-f451e01a-3fcd-4cc4-adba-09d555aa96a7.png)

**Comment by zabak** [comment]
Ještě prosím o info, kam se ukládá metatitul - je to title v "mutational edition" ve druhém příkladu? Ve druhém příkladu není jasné, kde je uložen údaj o mutaci, je tam jen mutační vydání.

**Comment by PavlinaKocisova** [comment]
Dobrý den, na úrovni ISSUE jsme původně se zápisem metatitulu nepočítali vůbec. Z práce na úpravě standardu nicméně v tuto chvíli vyplývá, že zápis metatitulu bude vhodné přidat na úroveň pro TITLE. Momentálně tento nový požadavek řešíme.

**Comment by zabak** [comment]
Na dnešní schůzce jsme se bavili o tom, že řešením by mohlo být použití virtuálních sbírek K7. Vychází to z odhadu, že digitalizovaných různých regionálních mutací jednoho titulu je poměrně málo a proto je možné toto zvládnout na kurátorské úrovni. Zde by pravděpodobně mělo smysl uvažovat o úrovni ČDK, protože tam se potkají i mutace z různých Krameriů. Bude to asi klást nějaké speciální požadavky na popis takové virtuální sbírky, protože její popis se bude blížit popisu titulu periodika, resp. vícesvazkového díla.

**Comment by PavlinaKocisova** [comment]
Zdravím, připravili jsme návrh úpravy kapitoly pro úroveň čísla (ISSUE) pro zápis mutačního vydání a příslušnou úpravu Pravidel pro popis periodik. Nakonec jsme se rozhodli, že na úrovni čísla bude zápis reflektovat pouze mutační vydání, (regionální) mutace budou v souladu se současnou katalogizační praxí řešeny na úrovni TITLE.  

Úprava zápisu čísla spočívá ve zdvojení kontejneru <titleInfo> v případě, že se jedná o mutační vydání, přičemž první kontejner je obecný, druhý je určený pro specifický zápis mutačního vydání s atributem "mutational edition". Jsem přesvědčena, že toto rozdělení lépe odpovídá smyslu pravidel MODS podle LOC.

Návrhy jsou otevřené komentářům. 

Podkapitola pro mutace v Pravidlech pro popis periodik bude v rámci kapitoly 2, Popis čísla a výtisku:
https://docs.google.com/document/d/1ItZQhw5b9f0TryX1TnkLSKxJ1ZilU47mVjSr7aPfF2Y/edit?usp=sharing

Návrh úpravy stávající kapitoly pro ISSUE. Upravená část je zvýrazněná žlutě:
https://docs.google.com/document/d/1TICLEpOeCnz1nlEyQ8FdXnkKhsfDjq7ARMLGyfw6z-A/edit?usp=sharing
