### ISSUE TITLE
zásadní chyby v ukázkovém balíčku pro DMF zvuk-gramodesky 0.3

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#157]
Na stránce https://old.ndk.cz/standardy-digitalizace/metadata je v sekci **Vzorové SIP balíčky** odkaz na ukázkový balíček pro _DMF zvukové dokumenty (gramodesky)_:
https://owncloud.cesnet.cz/index.php/s/ZzQvmhivstWIuAb/download

Ten ale obsahuje zásadní chyby, které znemožňují další zpracování. Vybrané chyby jsem opravil, konkrétně:

- hlavní METS nebyl well-built xml
- spatne odkazovani na hlavni mets v souboru INFO: <mainmets>mets_1234567890.xml</mainmets> namísto <mainmets>main_mets_1234567890.xml</mainmets>
- odkazy na neexistujici adresare v hlavnim METSu v FLocat: (amdsec/usercopy/sourceaudio/usercopyaudio namisto amd_sec/user_copy/source_audio/user_copy_audio)
- v souboru INFO odkazy na soubory začínájící na "\amd_sec\amd_mets__audio" namísto "\amd_sec\amd_mets_audio"

- neplatné uuid 567o1234-g56s-23c9-ah793-7804659320 nahrazeno za b8b148ea-5060-4fe5-bf64-75069599fad9
- neplatne uuid 581j6543-n32m-84e3-g750-849768265310 nahrazeno za 620dca09-8eb6-4c89-a591-276c3c7340e3
- neplatne uuid 637i7920-n96m-23d1-g971-1356905478 nahrazeno za e3aae24d-f3e4-4ed2-829c-1c658e8645c5
- neplatne uuid 321p7654-f32d-13d5-k654-798264310000 nahrazeno za fa39bd64-c289-4e04-a7ca-c718baf69832
- neplatne uuid 263e8795-k54e-15e4-r789-824600127960 nahrazeno za 6768c7d4-3468-46e3-82d8-71f7db9b5bac
- neplatne uuid 548t3695-r45s-63a5-v258-589146302570 nahrazeno za ada188d3-fd3d-47ce-b143-173bee54207d 

Opravená verze je zde:
https://www.dropbox.com/s/oi0yjus7u5yfv78/1234567890.zip
(odkaz bude funkční minimálně měsíc)

Téměř každé UUID bylo neplatné a to buď samotnou délkou (musí být 8-4-4-4-12, někdy tam bylo 8-4-4-4-10), tak obsahem (jen hexadecimální znaky 0-9,a-f), což nesplňuje třeba 263e8795-**k**54e-15e4-**r**789-824600127960.

Také bych poprosil o úpravu popisku. Jen z verze (0.3) se dá tušit, že se jedná o vzorový balíček pro _DMF Zvuk-gramodesky 0.3_ a ne _DMF Zvuk-fonovalecky 0.3_, jelikož druhý zmíněný standard v takové verzi není zveřejněn, ačkoliv se o něm píše v textu  _DMF Zvuk-fonovalecky 0.4_.

**Comment by rzeh4n** [comment]
Mimochodem co takhle mít ty ukázkové balíčky (rozbalené) rovnou tady v gitu? Dalo by se odkazovat na nejasnosti, byla by tam historie změn apod.

**Comment by vjirousek** [comment]
Díky, opravený balíček je dostupný na webu standardů:
https://standardy.ndk.cz/ndk/standardy-digitalizace/metadata



> Mimochodem co takhle mít ty ukázkové balíčky (rozbalené) rovnou tady v gitu? Dalo by se odkazovat na nejasnosti, byla by tam historie změn apod.

Můžeme to zkusit do budoucna nějak vymyslet. Ticket ale zatím zavírám, týkal se primárně konkrétního balíčku.
