### ISSUE TITLE
Jména autorů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#16]
```
Jaký máte problém?
1.Chci se zeptat, zda a jak se nejak řeší skutečnost, kdy je na titulním 
listu knihy pseudonym autora, ale v SKC je v záznamu knihy použita autoritní 
verze autorova jména, které je jiné než pseudonym.
Do pole autora se stáhne jméno z katalogizačního záznamu. Bude se v 
nějakém poli řešit ten pseudonym? 
Jde mi o to, že čtenář bude pravděpodobně hledat knihu podle jména 
autora uvedeného v knize, nemusí se dívat do SKC. V tom případě nic 
nenajde.

Děkuji

Aleš Drahotušský, MSVK Ostrava




```

Original issue reported on code.google.com by `tolner...@gmail.com` on 2 Jan 2013 at 8:26

**Comment by PavlinaKocisova** [comment]
-	ve stávající specifikaci ani pravidlech pro popis se tento problém neřeší. Specifikace uvádí pouze odkaz na pravidla RDA (přebírání odpovědnosti z polí 1XX/ 7XX), které u pseudonymů 
-	doporučují jejich užívání v případě, že se v dílech vyskytují častěji než občanské jméno, popř. pokud pro každou knižní sérii autor používá jiný pseudonym, 
	přiřazovat odpovídající. K problematice by se možná dalo vztáhnout i doporučení o používání různých podob jména vzhledem k souboru národních autorit. 

-	Každopádně současná specifikace se přiklání k výkladu P. Švástové, přebírat jména z katalogu a pseudonymy neřešit, pokud nejsou přímo uvedeny u odpovědnosti tam.

**Comment by zabak** [comment]
Korektní postup by byl aby se záznam pro účely indexace obohatil o alternativní podoby autorova jména. Pak není potřeba záznam nijak upravovat, jen je potřeba aby v něm byla zachovaná vazba na národní autority - a samozřejmě Kramerius by národní autority musel umět pro indexaci využít.

**Comment by PavlinaKocisova** [comment]
Ano, v podstatě jediná cesta je ta, že v katalogizačním záznamu je již autorův pseudonym uveden.

**Comment by zabak** [comment]
Není nutné ho ale vkládat do záznamu ručně. Toto lze dělat i automaticky před jeho zaindexováním. Jen by se to muselo doprogramovat - v tomto případě do Krameria.

**Comment by PavlinaKocisova** [comment]
V ohlášeném upgradu mods na verzi 3.7 se tento problém bude nově řešit subelementem top elementu<name> -> <alternativeName> s možností atributu altType, ve kterém zřejmě bude možné specifikovat, zda jde o přezdívku, pseudonym, atd. Tento upgrade je zatím v připomínkovacím řízení.
