### ISSUE TITLE
DMF Monografie 1.4 - chybí povinnost pro recordChangeDate/@encoding

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#160]
V DMF mon 1.4 chybí povinnost pro recordChangeDate/@encoding, taky recordCreationDate/@encoding. Jen na vnitřní části (strana 70). 
Bylo to opraveno ve verzi 1.4, až na tohle jedno místo. Všude jinde je M, takže počítám, že i tady.

**Comment by PavlinaKocisova** [comment]
oprava bude provedena ve verzi monografie 2.0.
