### ISSUE TITLE
relatedItem@type

### ISSUE THREAD

**Issue by isenkyr** [NLCR/Standard_NDK#161]
Dobrý den,

ve standardu pro Periodika 1.8 u title úrovně a Monografie 1.4 u volume úrovně je definován atribut @type u elementu relatedItem. Povolené hodnoty @type jsou "series", "original" a "isReferencedBy". Ovšem po stažení některých záznamů z katalogu a použití konverzní šablony MARC21slim2MODS3-6-NDK.xsl dostávám hodnoty @type jako "preceding", "succeeding" atd. Moje otázka zní jak mám s těmito hodnotami naložit? Zaměnit za nějakou povolenou hodnotu podle standardu anebo hodnotu smazat?
![obrazek](https://user-images.githubusercontent.com/19608475/138224133-2314db33-5e0e-4fbe-b09f-3aefd447a246.png)

Děkuji I.Šenkýř

**Comment by PavlinaKocisova** [comment]
Dobrý den, můžete hodnoty ponechat. Seznam povolených hodnot budeme v nových verzích DMF aktualizovat podle aktuální dostupnosti mapování z marc21.

**Comment by fremrovaK** [comment]
Seznam povolených hodnot byl aktualizován a rozšířen v DMF pro periodika 2.0 a DMF pro monografie 2.1.
