### ISSUE TITLE
Elektronické publikace - překlep

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#162]
Dobrý den, 
narazila jsem na překlep v definici metadatových formátů pro elektronické publikace. Je to jak u monografií (s. 49), tak u periodik (s. 58) a je to jen detail. U elementu mix/BasicImageInformation/BasicImageCharacteristics je dvakrát uveden element imageWidth a jeden z toho by zřejmě měl být imageHeight.

**Comment by FilipPavcik** [comment]
Preklep opravený v najnovších DMF pre e-publikácie. Issue zatváram.
