### ISSUE TITLE
Elektronické publikace - opakovatelnost elementu <originInfo>

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#163]
Dobrý den,

v DMF pro elektronické publikace - [Monografie 2.3 (str. 30)](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornmonografie_2.3.pdf) i [Periodika 2.3 (str. 34)](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornperiodika_2.3.pdf) se uvádí, že 

> všechny top elementy MODS formátu jsou opakovatelné, kromě elementu `<originInfo>`

Není to chyba a nemá být tím neopakovatelným elementem spíš `<recordInfo>`?  
Dál se v textu navíc píše, že 
> Element `<originInfo>` je opakovatelný. Alespoň v jednom výskytu musí obsahovat buď hodnotu hodnota eventType=”production”
nebo eventType=”publication”...

Jak to tedy, prosím, má být?

Děkuji za objasnění :-)

**Comment by FilipPavcik** [comment]
Dobrý deň,

ďakujeme za upozornenie, jedná sa o chybu v DMF. Ako správne píšete, element <originInfo> je opakovateľný, neopakovateľný má byť element <recordInfo>. V aktualizovanej verzii DMF bude chyba opravená.

**Comment by kerschfilip** [comment]
Děkuji za rychlou odpověď!

**Comment by FilipPavcik** [comment]
V najnovších verziách DMF pre e-publikácie je chyba v popise upravená. Issue preto zatváram.
