### ISSUE TITLE
řazení výtisků - dateissued ve formátu DD.MM.-DD.MM.YYYY

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#164]
Původně jsem to dala do issues clienta Krameria (https://github.com/ceskaexpedice/kramerius-web-client/issues/439), tam je to bez odezvy, tak se zeptám z druhé strany, jestli jsou metadata takto, jak nám to dodavatel v rámci VISK7 odevzdal, v pořádku. 

Máme periodikum, kde je datum vydání výtisku jako rozsah, pro který je číslo vydáno. A ta čísla, kde se láme měsíc - čili formát DD.MM.-DD.MM.YYYY - se nám v klientovi předřazují před ta, která jsou v rámci jednoho měsíce - ve formátu DD.-DD.MM.YYYY (viz třeba https://kramerius.svkhk.cz/uuid/uuid:8fd8d056-3b98-43f1-88ba-a901abee84ae).
Popravdě nevím, kam s tím dotazem - jestli je to (jen) problém zobrazení v Krameriovi, že pracuje jen s některými formáty, které doteď připouštěl NDK standard (viz NLCR/Standard_NDK#109), nebo jestli je to problém popisu, že to takhle být nemůže (a řešit to teda na githubu NDK standardu) - protože zpracovatel nám konkrétně tady (zřejmě proto, že tam nikde číslo nebylo) dal do partnumber místo čísla znovu to datum jako v dateissued - může i tohle mít na to řazení vliv?

**Comment by FilipPavcik** [comment]
Dobrý deň,
 
skúšal som sa na to pozrieť a podľa môjho názoru v popise problém nie je. Element partNumber je vyplnený v súlade s Pravidlami pre popis (PPP v. 8.4). Na s. 16 sa tu píše že, ak „číslo výtisku není uvedeno, a pokud nelze dopočítat, zapíše se datum“. Teda dátum zapísaný do partNumber by nemal byť problém. Takisto sa v PPP v. 8.4 vyskytujú oba vami uvedené formáty – teda aj DD.MM.-DD.MM.RRRR, aj DD.-DD.MM.RRRR.

Čo sa ale týka zobrazenia v Krameriu a prečo nedokáže pracovať s oboma formátmi na to Vám bohužiaľ nateraz neviem odpovedať.
