### ISSUE TITLE
Rozšíření DMF pro monografie o grafiky

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#170]
V DMF pro monografie je potřeba specifikovat vedle textových dokumentů, hudebnin a kartografických dokumentů také bibliografický popis pro grafiky (též vícesvazkové).

**Comment by FilipPavcik** [comment]
Dobrý deň,

na linku priloženom nižšie posielam návrh rozšírenia DMF pro monografie o bibliografický popis grafických dokumentov. Týmto by som zároveň chcel požiadať o zaslanie pripomienok k návrhu, prípadne o komentáre, ktoré môžete vkladať priamo do google dokumentu.

https://docs.google.com/document/d/1pKTOxPeacgpZXnDvjWiyCtPxVj1ZI_Cn/edit?usp=sharing&ouid=111634752806429404827&rtpof=true&sd=true

**Comment by FilipPavcik** [comment]
Hore uvedený návrh na bibliografický popis grafík bol pridaný do DMF pro monografie verze 2.1. Popis vícesvazkových grafík (a pravidla pro jejich popis) sa bude riešiť v issue #169. Tento ticket zatváram.
