### ISSUE TITLE
titleid v info.xml, type uuid: nekonzistence mezi XSD a DMF

### ISSUE THREAD

**Issue by jbil7** [NLCR/Standard_NDK#172]
Zakládám toto issue kvůli nalezené nekonzistenci mezi XSD a DMF v elementu `titleid`, konkrétně v rozsahu možných typů identifikátorů.

V [XSD pro soubor info.xml](https://standardy.ndk.cz/ndk/spec2014/info1_1.xsd) je uvedeno následující:

> Typ identifikátoru UUID využít pouze v případě, kdy není možné pracovat s ostatními, výše jmenovanými identifikátory: isbn, issn, ccnb a urnnbn (např. na úrovni TITLE u zahraničního periodika bez přiřazeného ISSN a čČNB)

V souvislosti s tím jsou v XSD povoleny následující hodnoty (vč. uuid):
```
<xs:element name="titleid" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                	<xs:simpleType>
                		<xs:restriction base="xs:string">
    						<xs:enumeration value="isbn"/>
    						<xs:enumeration value="issn"/>
   						<xs:enumeration value="ccnb"/>
   						<xs:enumeration value="urnnbn"/>
						<xs:enumeration value="uuid"/>							
  						</xs:restriction>
  					</xs:simpleType>
  				</xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
```
V Definicích metadatových formátů (např. pro perio 1.8) se však o užití identifikátoru UUID v elementu titleid nic nepíše. Povolenými elementy jsou zde pouze isbn, issn, ccnb, urnnbn (viz [DMF pro perio 1.8, s. 17.](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMFperiodika_18_final.pdf)). 

**Z hlediska DMF to tedy působí dojmem, že UUID není v titleid povoleno, z hlediska XSD však povoleno je.**

**Comment by vjirousek** [comment]
Nekonzistence bude vyřešena v další verzi DMF. UUID bude možné využívat v souladu s pokyny dnes uvedenými pouze v XSD.

**Comment by vjirousek** [comment]
Opraveno v:
- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022

![obrazek](https://user-images.githubusercontent.com/22765973/195877054-92330e30-97b0-40de-a1f7-c12a4b2ebbee.png)
