### ISSUE TITLE
originInfo/issuance u monografií

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#173]
Dobrý den,

při řešení stahování dat z katalogu do ProArcu (proarc/proarc#1427) jsme narazili na problém s tím, jak má být správně vyplňován element `<issuance>` v rámci `<originInfo>`

Pokud to správně chápu, pak DMF pro monografie dává tyto možnosti:
- Samostatný svazek monografie - `monographic` nebo `single unit`, z [MODS Guidelines](https://www.loc.gov/standards/mods/userguide/origininfo.html#issuance) mi pak přijde, že preferovanou hodnotou by mělo být `single unit`
- Svazek vícedílné monografie - `monographic` nebo `multipart monograph`, z [MODS Guidelines](https://www.loc.gov/standards/mods/userguide/origininfo.html#issuance) mi pak přijde, že preferovanou hodnotou by mělo být `multipart monograph`
- Titulní úroveň vícesvazkové monografie - `<issuance>` se nevyplňuje
- u periodik by se mělo vyplňovat `serial` v návaznosti na #148

Preference používání  `single unit` / `multipart monograph` před `monographic` mi pak vyplývá také ze vzorových SIP a transformační šablony z MARC21 do MODS verze 3.6, oboje odkazované z [webu pro standardy](https://standardy.ndk.cz/ndk/standardy-digitalizace/metadata)

**Mohl bych poprosit o potvrzení/doplnění/vyvrácení výše popsaného?**

Další otázkou je pak, zda dochází v rámci `<issuance>` v nové verzi DMF pro monografie k nějaké změně? Z toho, co jsem měl možnost vidět, mi přijde, že:
- na úrovni titulu vícesvazku `<issuance>` není (tedy je to stejné jako v současné verzi)
- na úrovni svazku vícedílné monografie je `monographic` nebo `multipart monograph`, ale ve verzi pro připomínkování byl komentář, že se uvažovalo o tom, že se hodnota` monographic` možná úplně vypustí.
- pro samostatný svazek monografie si nejsem jistý, jak to je, protože návrh jsem neviděl. Je tam stále varianta `single unit`? 

Mockrát děkuji za odpověď

**Comment by PavlinaKocisova** [comment]
Dobrý den,
nejdříve k nové verzi DMF:

- na úrovni titulu vícesvazku zůstává issuance beze změny, tj., není přítomno
- na úrovni svazku vícedílné monografie zůstanou obě hodnoty z důvodu kontinuity s předchozí digitalizací
- pro samostatný svazek monografie stále zůstává možnost single unit

- Co se týče hodnoty issuance single unit/ monograph, DMF předepisuje obojí z důvodu, že ne vždy je možné rozeznat, zda je dokument skutečně samostatným, nehledě na stále poměrně velké množství zvláště dříve zdigitalizovaných multipart monografií, které ovšem v katalogu nejsou zapsány na jednom záznamu, ale každá zvlášť. Z tohoto důvodu zatím neuvažujeme o změně předpisu. V případně bezpečných samostatných dokumentů doporučujeme využívat hodnotu "single unit".

- v případě vícedílné monografie, která je zkatalogizována na jeden záznam je preferovanou hodnotou "multipart monograph"

- ano, v případě periodik je vyplňování issuance vázáno na to, co bylo řečeno v #148

**Comment by kerschfilip** [comment]
Děkuji za vysvětlení :-), issue zavírám
