### ISSUE TITLE
ORCID iD a ROR ID

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#175]
Dobrý den,

u elektronických periodik bychom v KNAV rádi na úroveň článků přidávali k autorovi ORCID iD  a u korporací případně ROR identifikátor. Kam ho správně máme v metadatech umístit? Ve standardech jsem o tom zmínku nenašel. Jako nejlepší varianta se mi zdá v mods element `nameIdentifier`, ale ten je v současnosti vyhrazen pouze pro číslo národní autority. U ROR ID se potom nabízí `affiliation`. Jaký je, prosím, doporučený postup? 

Děkuji,
FK

**Comment by PavlinaKocisova** [comment]
Dobrý den,
v současné době na to není ve Standardu NDK konkrétní korektní způsob zápisu, ale po malé úpravě DMF to možné bude. 

1) ORCID ID, určitě je možné vepsat do nameIdentifier s atributem type="orcid". 

2) ROR, záleží, jak jste to myslel, v případě autora-organizace by mělo toto číslo být opět vepsáno do nameIdentifier a type="ror". Pokud by číslo ROR mělo být přiřazením autora-osoby k organizaci, nejspíš by byl vhodný element affiliation, bohužel ale v MODS 3.6 není možné vepsat atribut, pomocí kterého by se upřesnil druh identifikátoru (to bude možné snad v MODS 3.8). 

Úpravu popisu pole nameIdentifier bychom udělali s nejbližší aktualizací textových DMF.

**Comment by kerschfilip** [comment]
Děkuji za reakci, u ROR jsem měl na mysli přiřazení autora-osoby k organizaci, takže použijeme ten element `affiliation`

Ještě bych se rád ujistil ohledně podoby vyplňovaných hodnot - máme vyplňovat identifikátory ve formě URI, nebo pouze alfanumerických kódů? Jako lepší se mi zdají celé ty URI i proto, že k `affiliation` se tedy nedá přidat žádný atribut pro specifikaci

Je tento zápis, prosím, v pořádku?
```xml
<mods:nameIdentifier type="orcid">https://orcid.org/0000-0003-4649-6702</mods:nameIdentifier>
<mods:affiliation>https://ror.org/028sgmw18</mods:affiliation>
```

**Comment by PavlinaKocisova** [comment]
Pokud u nameIdentifier již máte typ identifikátoru uvedený v type, není potřeba používat jako hodnotu URI. Zvolila bych, stejně jako v současné době u čísla Národních autorit, pouze identifikátor samotný. 

![orcid](https://user-images.githubusercontent.com/26895177/191748727-551031b6-85c9-4ff1-b74a-a10227a2dd7b.png)

V případě affiliation bohužel v současné době není možnost, jak obsah pole přesně identifikovat, takže je podle mého názoru možné to řešit přímo vloženým URI.

**Comment by FilipPavcik** [comment]
Issue zatváram, keďže do najnovšie vydaných štandardov pre e-publikácie bol pridaný element `affiliation`, ktorý umožní zapísať názov inštitúcie, v ktorej daný autor pracuje. K elementu `nameIdentifier` bol zase pridaný atribút TYPE a hodnota "orcid". Viď nižšie: 

![affiliation](https://github.com/NLCR/Standard_NDK/assets/86611996/eaa31b75-9fc2-4733-af4e-ef756fddda42)
