### ISSUE TITLE
Pravidla popisu periodik v. 8.4 - typ strany advertisement

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#176]
Dobrý den,
všimnul jsem si, že v pravidlech popisu periodik je uveden typ strany advertisement zároveň pro 2 strany, a sice Inzerce a Reklama.
V Krameriovi se pak ale stránka přece může zobrazit jen pod jedním českým názvem. 
Chápu to správně, že Inzerce je např. nabídka zaměstnání, ubytování, inzerát převážně soukromé osoby nabízející koupi, prodej nějaké věci (např. pozůstalosti, knih, nábytku, ,...) apod.?

**Comment by luckajirku** [comment]
jen připojím issue, kde se to už řešilo: https://github.com/NLCR/Standard_NDK/issues/127

**Comment by Drahotussky** [comment]
Ještě dvě připomínky:
1) Typ strany Reklama je v Pravidech popisu periodik uveden jako typ strany pro vnitřní část dokumentu-article. Znamená to, že pro označení strany ve výtisku se použít nesmí?
2) V Pravidlech popisu pro monografie je jen typ strany Inzerce. Proč tam také není Reklama? V knihách bývají stránky, které přesně splnují definici Reklamy.

**Comment by Drahotussky** [comment]
Ad 1) prošel jsem si standardy periodik a tam u vnitřní části dokumentu není uveden typ strany Reklama (advertisements), jak je tomu v Pravidlech popisu pro periodika. V tom případě by mělo dojít k úpravě PPP a informace o typu strany Reklama by se přesunula z vnitřní části dokumentu na stejnou úroveň jako je Inzerce.

**Comment by vjirousek** [comment]
Dobrý den, obecně vidím jako příčinu problému zejména překryv mezi typy stran, typy stran vnitřních částí a typy vnitřních částí. Opodstatněnost vyčlenění zvláštní skupiny typů stran pro vnitřní části (případně zda se ve skutečnosti nejedná o typy vnitřních částí) navrhuji prodiskutoval na pracovní skupině.

**Comment by JezkovaV** [comment]
Zapracováno do Pravidel pro popis periodik (verze 8.6) a Pravidel pro popis monografií (verze 2.3)
