### ISSUE TITLE
Vícesvazková monografie pod jedním bibliografickým záznamem - popis názvů dílů

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#177]
Zdrvím, rád bych požádal o radu:
Vícesvazková monografie má v katalogu pro všechny díly jeden záznam. Každý díl tak bude mit svuj Volume pod urovni Title.
Pokud na titulních stránkách jednotlivých dílů není uveden název dílu, ale ten je uveden na samostatné stránce za titulkou (viz příloha),
![IMG_20220921_093750](https://user-images.githubusercontent.com/6399737/191681015-80720312-0ff5-4724-b8e7-d464e5bc713b.jpg)
![IMG_20220921_093804](https://user-images.githubusercontent.com/6399737/191681016-e2c67fea-d403-4ee5-b25b-c5599b102cba.jpg)
tak se v metadatech pro Volume uvede v partName nazev dilu nebo ne?  Pokud ano, tak v hranatych zavorkach nebo bez? Dival jsem se do digitalni knihovny na jina vydani stejne knihy a tam nekdy nazev dilu zapsan neni, jindy je v hranatych zavorkach nebo bez nich. Jednotlive dily jsou tam zpracovany samostatne a ne jako vicesvazkova monografie, i kdyz v SKC ma NK jen jeden zaznam pro vsechny dily (napr.  cnb002843507, cnb003050902)

**Comment by PavlinaKocisova** [comment]
Dobrý den, formálně nejlepší dle mého názoru zřejmě bude název dílu v partName uvést v hranatých závorkách. Dle mého názoru je to i varianta nejvíce užitečná z hlediska uživatele digitální knihovny. Věc ale ještě prodiskutujeme s kolegy, než dáme závazné stanovisko.

**Comment by PavlinaKocisova** [comment]
Zdravím, pokud odhlédneme od katalogizační praxe, je možné název dílu do <partName> uvést. Vzhledem k tomu, že se nenachází na stejné straně, jako zbytek zdrojových údajů, bych jej ale umístila do hranatých závorek. Myslíme si, že v tomto případě převažuje užitečnost údaje pro vyhledávání a pro uživatele.

**Comment by PavlinaKocisova** [comment]
Zdravím, chápu a děkuji za reakci. V tom případě můžete doplňovat bez nich.
