### ISSUE TITLE
Popis původce více křestními jmény 

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#178]
Dobrý den,
rád bych v rámci vnitřní části uvedl původce, který má autoritní formu, která vypadá např. takto:
https://aleph.nkp.cz/F/D5PHLEGNMU81XLVFTUSKVH59PAAX3D6IRMS8M5PVFQ1TFVSRC4-54467?func=full-set-set&set_number=137230&set_entry=000001&format=999

Přepíší se do křestní jména jen zkratky křestních jmen z podpole **a** nebo i rozepsaná křestní jména, která jsou v závorce v podpoli **q**?

Dekuji

**Comment by Drahotussky** [comment]
Jedná se o
Waddington, C. H. (Conrad Hal), 1905-1975

Dne po 3. 10. 2022 13:31 uživatel vjirousek ***@***.***>
napsal:

**Comment by vjirousek** [comment]
Standard přesný způsob mapování aktuálně nepředepisuje, doporučil bych se proto držet způsobu zápisu jmen, který využíváte na ostatních úrovních popisu (tam kde využíváte transformace z MARC do MODS). V rámci vlastní digitalizace vnitřní části nepopisujeme, z MARC bychom např. na úrovni titulu monografie převzali v podobě složené z podpolí a + q tedy:

`<mods:namePart>Waddington, C. H. (Conrad Hal)</mods:namePart>`

V případě rozepsání do více elementů <namePart> je možné zapsat např. následovně:

`<namePart type="family">Waddington</namePart>`
`<namePart type="given">C. H.</namePart>`
`<namePart type="given">(Conrad Hal)</namePart>`

**Comment by Drahotussky** [comment]
Takovy zpusob zapisu by byl predpokladam take mozny?:
<namePart type="family">Waddington</namePart>
<namePart type="given">C. H. (Conrad Hal)</namePart>

nebo pouzit jen obsah podpole **a**?
<namePart type="family">Waddington</namePart>
<namePart type="given">C. H.</namePart>

**Comment by vjirousek** [comment]
> Takovy zpusob zapisu by byl predpokladam take mozny?: 

`<namePart type="family">Waddington</namePart>` 
`<namePart type="given">C. H. (Conrad Hal)</namePart>`
> 
> nebo pouzit jen obsah podpole **a**?

 `<namePart type="family">Waddington</namePart>`
 `<namePart type="given">C. H. </namePart>`

Ano, tento způsob zápisu je také možný.
