### ISSUE TITLE
Hodnota <relatedItem> u předcházejícího a navazujícího periodika

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#179]
V metadatech TITLE u periodika máme po konverzi z MARC tato metadata u elementu `<relatedItem>`
`<mods:relatedItem` type="succeeding">
            `<mods:titleInfo>`
              `<mods:title>Ostravský` `večerník</mods:title>`
            `</mods:titleInfo>`
            `<mods:identifier` `type="issn">2788-1393</mods:identifier>`
          `</mods:relatedItem>`

Validátor nahlásil chybu, protože očekává jednu z hodnot: series, original, isReferencedBy.

Které hodnoty se vyplní pro titul, který je předcházející a následující popisovanému titulu?

Znamená to, že hodnoty, které se vyplní v záznamu MARC, je třeba vždy metadatech MODS opravit?

Děkuji

**Comment by vjirousek** [comment]
Dobrý den, toto je řešeno v rámci issue https://github.com/NLCR/Standard_NDK/issues/161. Hodnotu "succeeding" je možné ponechat.

**Comment by Drahotussky** [comment]
Dobrý den,
je možné ponechat u monografií u atributu  @type také hodnotu **constituent**?

**Comment by vjirousek** [comment]
Dobrý den, ano, jak bylo řečeno v #161 - hodnoty vzniklé v souladu s mapováním z MARC do MODS 3.6 lze ponechat. Doplnění do standardu vyšší verze bylo avizováno a proběhne při nejbližší možné příležitosti (součástí DMF pro periodika 1.9 a monografie 2.0 oprava nebyla, původní ticket proto zůstal otevřen a prosím o komunikaci v něm).

https://www.loc.gov/standards/mods/v3/mods-mapping-3-6.html
