### ISSUE TITLE
Jiné povolené hodnoty u <relatedItem> než jsou ve standardech

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#180]
Dobrý den,
v Issues https://github.com/NLCR/Standard_NDK/issues/161 se pise, ze v novych standardech budou pridany nove povolene hodnoty podle dostupnosti z mapovani MARC pro element <relatedItem>. Zadne jsem v novych standardech ale nenasel.
V tomto Issue https://github.com/NLCR/Standard_NDK/issues/179 se jiz jednu z hodnot resil.

Nam se v baliccich objevuji hodnoty např. constituent, preceding, succeeding. A pri validaci nam pote vyskakuje Error.
Preceding a succeeding byly alespon zde neoficialne schvaleny jako povolene. Plati totez i pro constituent a lze ji ponechat v baliccich 
 (i VISK 7)?

Dekuji

**Comment by vjirousek** [comment]
Dobrý den, ano, jak bylo řečeno v #161 - hodnoty vzniklé v souladu s mapováním z MARC do MODS 3.6 lze ponechat. Doplnění do standardu vyšší verze bylo avizováno a proběhne při nejbližší možné příležitosti (součástí DMF pro periodika 1.9 a monografie 2.0 oprava nebyla, původní ticket proto zůstal otevřen a prosím o komunikaci v něm).

https://www.loc.gov/standards/mods/v3/mods-mapping-3-6.html
