### ISSUE TITLE
U jména použitého jako věcné záhlaví se nestahuje kód autority

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#181]
Zdravím, 

Ve standardech se píše, že při použití jména jako věcného záhlaví (`/subject/name`) se použije struktura a atributy stejné jako pro údaje o
původcích – viz element `<name>`. 

Při přebírání dat z katalogizačního záznamu z pole `600` ale doporučovaná transformační šablona z MARC21 do MODS nepočítá s převedením čísla národní autority - v šabloně chybí v části pro převod `600` pravidlo pro zavolání template "nameIdentifier"

Doplněné by to, myslím, mělo vypadat takto:  
![image](https://user-images.githubusercontent.com/57805328/197527103-03372068-cf49-4e95-a7d8-54f3a882cda7.png)

**Comment by kerschfilip** [comment]
ano, konkrétně jsem koukal na "[transformační šablona](https://standardy.ndk.cz/ndk/standardy-digitalizace/MARC21slim2MODS36NDK.zip) z MARC21 do MODS verze 3.6"

**Comment by vjirousek** [comment]
Rozumím, díky za potvrzení. Tyto šablony byly v minulosti na žádost knihoven vystaveny, stále se nicméně jedná pouze o šablony používané v produkční lince NDK, nikoliv o šablony doporučované k přímému užití v jiných digitalizačních systémech. Více případně můžeme probrat v diskusi na zítřejším setkání pracovní skupiny pro textové dokumenty.

**Comment by zabak** [comment]
Přimlouvám se za zachovávání jakýchkoli identifikátorů autorit.

**Comment by vjirousek** [comment]
> Přimlouvám se za zachovávání jakýchkoli identifikátorů autorit.

Standardy využití identifikátorů podporují, nastavení digitalizační linky NDK prosím řešme na interním gitlabu.

**Comment by vjirousek** [comment]
> > Standardy využití identifikátorů podporují, nastavení digitalizační linky NDK prosím řešme na interním gitlabu.
> 
> prosím, kam se má zapsat kód věcné autority, respektive jak je to podporováno v digitalizační lince NDK? Abychom se mohli s ProArcem inspirovat. Nepřišli jsme totiž na to, kam ho zapsat - není to zmíněno ve standardu, ale i MODS snad podporuje jen přidání URL, kterou zase nevrací aleph NK

Přímo identifikátory záznamů u věcných autorit v rámci NDK digitalizační linky do metadat nezapisujeme. Pokud je poptávka po rozšíření standardu, prosím o samostatné issue a prověříme možnosti MODS v aktuální využívané verzi, případně v novějších verzích. Pokud už jste toto prověřili a MODS řešení nenabízí, pak zatím problém pravděpodobně také příliš neposuneme.

Zápis čísla jmenné národní autority ve smyslu tohoto ticketu je ve standardu konkrétně popsáno, předpokládám že se tedy dotaz týká ostatních typů věcných autorit.
