### ISSUE TITLE
mods/genre u elektronických publikací

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#182]
Zdravím,

u elektronických publikací je ve standardech nekonzistence v hodnotách vyplňovaných do elementu `<genre>`

- u periodik má mít hodnota podobu `electronic_title`, `electronic_volume` atd.
- u monografií je to ale `electronic title`, `electronic volume`... tedy bez toho podtržítka 

Dalo by se to, prosím, nějak sjednotit? 

Děkuji.

**Comment by vjirousek** [comment]
Dobrý den, určitě by byl žádoucí jednotný způsob zápisu v době vydání standardů, aktuálně již nicméně budeme muset volit mezi konzistentním zápisem ve dvou standardech na straně jedné a zachováním kontinuity způsobu zápisu v různých verzích jednoho standardu na straně druhé. Téma bude lepší projednat na plánované pracovní skupině k elektronickým dokumentům.

**Comment by FilipPavcik** [comment]
Dobrý deň, 

nekonzistentnost v standardech pre elektronické publikácie pri vyplňování elementu `genre` zjednotíme na verzi s podtržítkem.

Standard pre elektronické monografie tak upravíme pri najbližšej aktualizaci a závazná hodnota bude tedy `electronic_title`, resp. `electronic_volume` s podtržítkem, jak pre elektronické periodika (i skládaná periodika), tak pre elektronické monografie.

@kerschfilip  Vedeli by ste nám povedať, jestli by bola tahle úprava pre vás v poriadku? Vďaka.

**Comment by kerschfilip** [comment]
Dobrý den,

v KNAV máme v tuto chvíli zpracovaných přibližně 400 elektronických monografií. Protože jsme se drželi standardu, tak pro element `genre` používáme hodnoty bez podtržítka - tedy `electronic volume` a `electronic title`. Například [zde](https://kramerius.lib.cas.cz/uuid/uuid:8ad0227e-895c-465f-afc9-913a614f2402). 

Na druhou stranu elektronická periodika podle standardu zatím zpracovaná žádná nemáme - naše současné zpracování je postavené na modelu, který vznikl před standardem. Plánujeme takto zpracovaná periodika časem převést do struktury odpovídající standardu a zálohovat je v podobě NDK SIP a novou produkci již dělat podle standardu.

Z toho tedy vyplívá, že v tuto chvíli nemáme žádná data, která by byla vytvořená podle Standardů pro eperiodika a přikláněli bychom se tedy ke sjednocení na verzi s mezerou.

**Comment by FilipPavcik** [comment]
Nekonzistentnosť je upravená v najnovšie vydaných štandardoch pre e-publikácie. U elementu `mods:genre` je naprieč štandardmi predpísaná hodnota bez podtržítka, teda `electronic volume`, `electronic title`, atd. Issue teda zatváram.
