### ISSUE TITLE
Látková záložka (jako součást publikace?)

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#183]
Máme tu teď pár publikací k výročí střední školy, ve kterých jsou vloženy látkové záložky s výšivkou k tomu jubileu. Vypadá to, že byly součástí publikace už při vydání. Přijde nám škoda je při digi vynechat, ale jak takovou záložku popsat? Setkal se s tím už někdo? Pokud ano, jak jste to řešili? Popsat jako volný list?

**Comment by vjirousek** [comment]
Není to úplně ideální, ale lepší postup než popsat jako volný list mne osobně nenapadá. Informace, že dokument obsahuje vloženou textilní záložku, by se mohla doplnit i do poznámky o fyzickém stavu dokumentu (zejména pokud by z výsledného digitalizátu nebylo například jednoznačně poznat, že se jedná o volně vložený objekt z jiného materiálu).
