### ISSUE TITLE
Podelement <partName> v <titleInfo> u kapitoly monografie

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#185]
Dobrý den,
rád bych se zeptal, co patří do podelementu <`partName`> v <`titleInfo`> u kapitoly? Ve standardech ani pravidlech popisu to není specifikováno.
Př. obsahu:
I. Dějiny Evropy - do <`title`>?  
> A. Anglie - do <`partName`>?   
> 1. Wessex - do <`partName`> jako Anglie. Wessex? nebo uz se nepopisuje?     
> 2. Sussex - do <`partName`> jako Anglie. Sussex? nebo uz se nepopisuje?

>  B. Francie - <`partName`>?

II. Dějiny Afriky

Lze do  napsat název v jednom elementu takto <`title`> Dějiny Evropy. Anglie. Wessex </`titleInfo`>?

Jiný př. obsahu:
První jednání - do<`title`>?
   
> Skleník - do <`partName`>?
 
> Práce - do <`partName`>?

Druhé jednání - do<`title`>?
   
>  Objev- do <`partName`>?

> Konec- do <`partName`>?

Lze do  napsat název v jednom elementu takto <`title`>Prví jednání. Skleník</`titleInfo`>?
Děkuji

**Comment by Drahotussky** [comment]
Prosím o reakci
Děkuji

**Comment by PavlinaKocisova** [comment]
Dobrý den, můžete nám skeny obálek/ tiráží poslat emailem, aby to bylo možné lépe posoudit? Děkuji.

**Comment by PavlinaKocisova** [comment]
Dobrý den, na základě diskuse s kolegy doporučujeme popis kapitoly, které fungují jako oddíly v rámci úrovně CHAPTER popisovat v elementu <title> a název podřízené (vnořené) kapitoly do subelementu <partName>. Pro jedno ID CHAPTER doporučujeme zanořit pouze jeden subelement <partName>. Víceúrovňové zanořování podkapitol důrazně nedoporučujeme i vzhledem k možným komplikacím v Krameriu. 

Tento způsob zápisu momentálně považujeme za nejlepší řešení. 

![vnořené kapitoly](https://github.com/NLCR/Standard_NDK/assets/26895177/f2fc773e-4e84-41ab-8b90-1227dc57c1d3)
