### ISSUE TITLE
Technická metadata MIX - povinnost `ScannerCapture`

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#186]
Zdravím,

v současných standardech pro periodika a monografie je v části technických metadat MIX vyžadován povinně blok s údaji o skeneru `<ScannerCapture>`. Neměla by povinnost být spíš MA? Například v případě, kdy je jediným záznamovým zařízením fotoaparát, mi nedává vyplňování tohoto elementu smysl.

dotaz/návrh je původně odsud: https://github.com/proarc/proarc/issues/528

Děkuji

**Comment by vjirousek** [comment]
Omlouvám se za prodlevu v reakci a potvrzuji že by mělo být MA. V minulosti byla povinost již opravována v DMF pro zvukové dokumenty, nyní problém zůstává u DMF pro monografie a DMF pro periodika.

**Comment by JezkovaV** [comment]
Povinnost `ScannerCapture` bude snížena z M na MA u nadcházejících verzí DMF pro monografie i periodika, ve všech ostatních DMF je již opraveno.

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)
