### ISSUE TITLE
Nekonzistentnosť naprieč DMF u elementu `physicalLocation`

### ISSUE THREAD

**Issue by FilipPavcik** [NLCR/Standard_NDK#187]
Upozorňujem na nekonzistentnosť v štandardoch pre textové a elektronické dokumenty u elementu `physicalLocation`.

Pri textových dokumentoch je v DMF u daného elementu uvedený atribút Authority s predpísanou hodnotou „siglaADR“. (Rovnako je to aj u zvukových dokumentov.) Pri elektronických dokumentoch je ale predpísaný povinný atribút Type s hodnotou „sigla ADR“. 

Aby sa zachovala konzistentnosť naprieč DMF bude táto nekonzistentnosť napravená pri najbližšej aktualizácii štandardov pre elektronické dokumenty. U elementu `physicalLocation` tak bude predpísaný povinný atribút Authority, tak ako je to u textových dokumentov. Rovnako bude zmenená aj hodnota tohto atribútu, ktorá bude predpísaná bez medzery v tvare „siglaADR“.

**Comment by FilipPavcik** [comment]
@kerschfilip
Vedeli by ste nám povedať, jestli by táto zmena v standardu bola pre vás v poriadku? Prípadne, jestli vaše data v prípade elementu `physicalLocation` obsahujú hodnoty podľa DMF pro e-publikácie v. 2.3? Veľká vďaka.

**Comment by kerschfilip** [comment]
@FilipPavcik děkuji za upozornění. Změna je za nás v pořádku. Tuto nekonzistenci jsme patrně neřešili a napříč dokumenty máme `physicalLocation` zapsané včetně atributu Authority a ve tvaru siglaADR. Tedy takto:

```xml
<mods:physicalLocation authority="siglaADR">ABA007</mods:physicalLocation>
```

**Comment by FilipPavcik** [comment]
@kerschfilip Vďaka za potvrdenie.

**Comment by FilipPavcik** [comment]
Nekonzistentnosť v štandardoch je upravená v najnovšie vydaných DMF pre e-publikácie. U elementu `physicalLocation` je predpísaný povinný atribút Authority s hodnotou "siglaADR". Issue teda zatváram.
