### ISSUE TITLE
Skládačka - plánek města

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#188]
Aby se tu neřešila jen metadata, tak jedna věc pro zpestření. Lámeme si hlavu, jak nejlépe zpracovat toto. Kdo jste se s tím setkal, jak jste se s tím vypořádali?
Složený plánek, z jedné strany je plán města, z druhé je to takhle rozdělené. 
- Popsat to vcelku, jednu stranu a druhou stranu - přičemž tu první, kde vpravo dole je jakože titulka, popsat jako titulní stranu?
- Nebo to tam nechat vcelku plus ještě rozsekanou verzi na ty jednotlivé části? (Jen u té strany, která je dělená, nemyslím rozsekat i tu s plánkem:-))
![image (2)](https://user-images.githubusercontent.com/6359479/216313478-4358bafc-fd50-4550-99f8-8cfa2c5136f8.png)

**Comment by luckajirku** [comment]
@vjirousek @PavlinaKocisova můžu poprosit o nějaký názor? Díky:-)

**Comment by vjirousek** [comment]
Já bych šel spíš druhou cestou, tj. nechal vcelku pro zachycení autentické podoby dokumentu + rozsekal aby se to dalo rozumně zobrazovat uživatelům. Špatně ale není ani jeden z popsaných způsobů.

**Comment by PavlinaKocisova** [comment]
Dobrý den, přikláníme se spíše k druhé možnosti, kterou navrhujete, tzn. velké označit jako [1], [2] a pak za to ty rozsekané v podobě [1a], [1b], [1c] atd. Tento zápis považujeme za nejautentičtější vůči originálu.

**Comment by luckajirku** [comment]
Díky, uděláme to tak.
