### ISSUE TITLE
originInfo/issuance u monografií

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#195]
Dobrý den,
v nejnovějších standardech je u monografií v poli issuance povolena hodnota monographic nebo multipart monograph. V již uzavřeném issue https://github.com/NLCR/Standard_NDK/issues/173
se psalo, že zůstane zachována hodnota single unit. Tak tomu bylo ještě ve standardech 2.0. Ale ve změnovém listu ke standardům 2.1 jsem nenašel nic o vypuštění hodnoty single unit.

**Comment by fremrovaK** [comment]
Dobrý den,
v nové verzi DMF pro monografie (2.1) k žádným změnám v hodnotách pro element `<issuance>` nedošlo. 
Hodnoty, které uvádíte, tedy „monographic“ a „multipart monograph“, jsou povoleny pro svazek vícesvazkové monografie (viz s. 49 a 51 DMF). Pro jednosvazek je navíc zachována i hodnota „single unit“ (viz s. 62 a 64).
V obou případech jsou tedy hodnoty stanoveny stejně, jak tomu bylo v předchozí verzi DMF 2.0.

**Comment by Drahotussky** [comment]
Máte pravdu, špatně jsem se podíval. Omlouvám se :-(
