### ISSUE TITLE
Pravidla pro popis periodik - chybějící "p" v approximate

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#197]
V pravidlech pro popis periodik v příkladu na str. 18 nahoře chybí jedno p ve slově approximate 
<mods:originInfo>
 <mods:dateIssued qualifier=”aproximate”>11.05.1951</mods:dateIssued>
</mods:originInfo>

**Comment by JezkovaV** [comment]
Chybějící písmeno v příkladu bude v nejnovější verzi Pravidel pro popis periodik opraveno.

**Comment by JezkovaV** [comment]
Zapracováno do Pravidel pro popis periodik (verze 8.6)
