### ISSUE TITLE
Reference na copyrightMD.xsd

### ISSUE THREAD

**Issue by okaucky** [NLCR/Standard_NDK#199]
Dobry den, prosim o radu jak resit nasledujici problem.

V PSP uvadime referenci: http://www.cdlib.org/groups/rmg/docs/copyrightMD.xsd. 

Ta uz neni dostupna a je nahrazena odkazem ze ktereho je moznost stahnout .xsd... a vyuzivat lokalni referenci. Takovy soubor ale do balicku nemuzeme pridat. Existuje uz nejake pravidlo jak podobne situace resit prosim?

Nove url kde jsou copyright informace: https://cdlib.org/groups/rights-management-group-copyrightmd/
Dekuji za pomoc

S pozdravem OKaucky

**Comment by FilipPavcik** [comment]
Dobrý den,

ďakujeme za dotaz. Ako možné riešenie by som videl použiť element `xsi:schemaLocation` a ako hodnotu použiť danú webovú stránku na ktorej sa nachádza xml schéma. 

Teda vyzeralo by to takto: 

xsi:schemaLocation="https://cdlib.org/groups/rights-management-group-copyrightmd/"

**Comment by okaucky** [comment]
Dekujeme za odpoved. 
Pekny den

**Comment by FilipPavcik** [comment]
Dobrý den,

ospravedlňujem sa, že odpisujem neskoro, ale kolega ma upozornil na moju chybu v odpovedi na Váš tiket. Díval som sa teda ešte podrobnejšie do CopyrightMD User Guidelines (https://cdlib.org/wp-content/uploads/2019/01/copyrightMD_user_guidelines.pdf) a ak by ste chceli deklarovať namespace daného standardu, tak podle CopyrightMD User Guidelines (s.3) by sa mal na deklarovanie namespace použiť element `xmlns` a malo by to vyzerať takto: 

xmlns=“http://www.cdlib.org/inside/diglib/copyrightMD“

Súčasne by však v namespace mal byť deklarovaný aj element `xsi:schemaLocation`. Avšak keďže v súčasnosti daný URL link nie je dostupný, tak zatiaľ nemáme lepšie riešenie ako uviesť adresu z webového archivu, tj.: 

schemaLocation=“[https://web.archive.org/web/20120621222350/http://www.cdlib.org/groups/rmg/docs/copyrightMD.xsd](https://web.archive.org/web/20120621222350/http:/www.cdlib.org/groups/rmg/docs/copyrightMD.xsd)“

Zároveň som písal dotaz do California Digital Library, kde vyvinuli daný standard CopyrightMD, aké v tomto prípade pri nefunkčnosti URL linku navrhujú riešenie. Keď dostaneme od nich odpoveď, tak ju obratom zverejníme na Githube. Zatiaľ sa nám zdá tento spôsob, ako najlepšie riešenie.
