### ISSUE TITLE
Zapisování použité literatury k elektronickým článkům

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#201]
Zdravím,

v KNAV máme požadavek od ústavů AV ČR, pro které zpracováváme elektronická periodika (podle DMF pro skládaná periodika), zapisovat k článkům i seznam použité literatury. 

Hlavním důvodem je odeslat informace o použité literatuře do Crossrefu, kde pro každý článek registrujeme DOI. Schéma udávající, jak citace zapisovat pro potřeby Crossrefu je popsané [zde](https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/references/#00177). Možné je posílat citace ve strukturované i nestrukturované podobě.

Chtěli bychom ale, aby se kromě odesílání do Crossrefu tyto informace dostaly i do MODSu, odkud by se mohly vytáhnout do Krameria nebo na [weby časopisů](https://asjournals.lib.cas.cz/). Je ale potřeba vyřešit kam a jak seznam použité literatury zapsat.

Zkusili jsme navrhnout [mapovací tabulku crossref-mods](https://docs.google.com/spreadsheets/d/1_BGNMIfip6OIURfTt_iS1GbXQCDkTJ5TOLhUpYJ_2_w/edit?usp=sharing) a chtěli bychom poprosit o ověření, že to takhle je možné udělat. Pro každou položku seznamu literatury by se podle našeho návrhu použil element `relatedItem`, u kterého bude nutné stanovit vhodně atributy `type` a `id`. Jinak by to snad neměl být velký problém. Pro nestrukturovanou poznámku (viz poslední příklad) navrhujeme použít `relatedItem/note[@type="unstructured_citation"]`

Přikládám také příklady:

Příklad Crossref: https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/references/#00177 -->
```xml
<citation_list>
 	<citation key="ref1">
	  	<journal_title>Current Opinion in Oncology</journal_title>
	  	<author>Chauncey</author>
	  	<volume>13</volume>
	  	<first_page>21</first_page>
	  	<cYear>2001</cYear>
  	</citation>
 </citation_list>

<!-- alternativa v MODS-->
<relatedItem type="references" id="ref1">
	<name>Chauncey</name>
	<part>
		<extent unit="pages">
			<start>21></start>
		</extent>
	</part>
	<originInfo>
		<dateIssued>2001</dateIssued>
	</originInfo>
	<relatedItem type="host">
		<titleInfo>
			<title>Current Opinion in Oncology</title>
			<part>
				<detail type="volume">
					<number>13</number>
				</detail>
			</part>
		</titleInfo>
	</relatedItem>
</relatedItem>
```

Příklad pro článek v časopisu Česká literatura: https://kramerius.lib.cas.cz/uuid/uuid:b612e67b-a757-494c-9091-9274229e0958, str. 620-->

```xml
<citation key="ref2">
	<issn>1213-2144</issn>
	<journal_title>Bohemica litteraria</journal_title>
	<volume>XXV</volume>
	<issue>1</issue>
	<first_page>76</first_page>
	<cYear>2022</cYear>
	<article_title>Styl v literárním překladu prizmatem Karla Hausenblase</article_title>
        <author>GETTA, Jelizaveta</author>
	<doi>https://doi.org/10.5817/BL2022-1-5</doi>
</citation>

<!-- alternativa v MODS-->
<relatedItem type="references" id="ref2">
	<name>GETTA, Jelizaveta</name>
	<part>
		<extent unit="pages">
			<start>76</start>
		</extent>
	</part>
	<originInfo>
		<dateIssued>2022</dateIssued>
	</originInfo>
	<relatedItem type="host">
		<titleInfo>
			<title>Bohemica litteraria</title>
			<part>
				<detail type="volume">
					<number>XXV</number>
				</detail>
				<detail type="issue">
					<number>1</number>
				</detail>
			</part>
		</titleInfo>
		<identifier type="issn">1213-2144</identifier>
	</relatedItem>
	<titleInfo>
		<title>Styl v literárním překladu prizmatem Karla Hausenblase</title>
	</titleInfo>
	<identifier type="DOI">10.5817/BL2022-1-5</identifier>
</relatedItem>
```

Příklad Crossref, nestrukturovaná poznámka
```xml
<citation key="ref3">
	<unstructured_citation>Clow GD, McKay CP, Simmons Jr. GM, and Wharton RA, Jr. 1988. Climatological observations and predicted sublimation rates at Lake Hoare, Antarctica. Journal of Climate 1:715-728.</unstructured_citation>
</citation>

<!-- alternativa v MODS-->
<relatedItem type="references" id="ref3">
	<note type="unstructured_citation">Clow GD, McKay CP, Simmons Jr. GM, and Wharton RA, Jr. 1988. Climatological observations and predicted sublimation rates at Lake Hoare, Antarctica. Journal of Climate 1:715-728.</note>
</relatedItem>
```

**Comment by fremrovaK** [comment]
Dobrý den,
děkujeme za návrh. Zatím k němu přidávám několik poznámek:
•	Souhlasíme s použitím elementů `<relatedItem type=“references“>` pro jednotlivé položky ze seznamu citované literatury. Při tvorbě jejich identifikátoru bude třeba zohlednit i předpokládané množství citované literatury, tj. číslo, které je součástí identifikátoru by mělo být vícemístné, doplněné o nuly, např. „ref001“, příp. „ref0001“. Máte prosím představu, kolik citovaných položek bývá?
•	Pro nestrukturovanou citaci je možné použít `<note>`, jak navrhujete, ale hodnota jejího atributu type by měla vycházet z [toho seznamu](https://www.loc.gov/standards/mods/mods-notes.html), přikláníme se k `<note type=“source note“>`.
•	Jméno autora je třeba zaznamenat do subelementu `<namePart>` vnořeného do elementu `<name>`:
```
<name>
<namePart>Chauncey</namePart>
</name>
```
•	Element <part> nemůže být vnořený do `<titleInfo>`, jde o element stejné úrovně jako `<titleInfo>`.
•	Typ identifikátoru DOI zapisovat kvůli konzistenci s ostatními typy identifikátorů malými písmeny: `<identifier type=“doi“>`.
•	V přiložené tabulce s mapování jsem si dále všimla mapování ISBN přímo do `<identifier type=“isbn“>`. To řeší situaci, kdy je v seznamu citované literatury zapsaná kniha jako celek. Bude zřejmě třeba doplnit i mapování ISBN pro případy, kdy se odkazuje na příspěvek/kapitolu v knize, pak by dle mého názoru měl být `<identifier type=“isbn“>` až u druhého, vnořeného elementu `<relatedItem>`:
```
<relatedItem type="references" id="ref001">
	…
	<relatedItem type="host">
		<identifier type="isbn">978-80-7505-795-2</identifier>
		…
	</relatedItem>
</relatedItem>
```
S Vaším návrhem budeme ještě dále pracovat, s kolegy ještě zvažujeme další možnosti zápisu ročníku a čísla a rozhodujeme se, na jakou úroveň by bylo nejlepší zanášet rok vydání, ale chtěli jsme Vám zatím dát aspoň toto dílčí stanovisko.

**Comment by fremrovaK** [comment]
Dobrý den,

s kolegy jsme dotvořili návrh na zápis citované literatury. Je k nahlédnutí na [tomto odkazu](https://docs.google.com/document/d/1iNAxAr8xHHHRfRS9h1kCsqYCSZvyEZpv/edit?usp=sharing&ouid=110039785906477896208&rtpof=true&sd=true), budeme rádi za případné komentáře.

Příklady zápisu (viz výše) by podle něj vypadaly takto:

Příklad Crossref:
`<relatedItem type="references" id="ref0001">
	<titleInfo>
		<title>Název článku</title>
	</titleInfo>
    <name>
        <namePart type="family">Chauncey</namePart>
    </name> 
	<part>
		<extent unit="pages">
			<start>21></start>
		</extent>
	</part>
    <relatedItem type="host">
		<titleInfo>
			<title>Current Opinion in Oncology</title>            			
		</titleInfo>
        <originInfo>
		  <dateIssued>2001</dateIssued>
	    </originInfo>
        <part>
		  <detail type="volume">
			<number>13></number>
		  </detail>
	    </part>         
	</relatedItem>    	
</relatedItem>`

Příklad Česká literatura:

`<relatedItem type="references" id="ref0002"> 
	<titleInfo>
		<title>Styl v literárním překladu prizmatem Karla Hausenblase</title>
	</titleInfo>
    <name>
        <namePart type="family">Getta</namePart>
        <namePart type="given">Jelizaveta</namePart>
    </name> 
	<identifier type="doi">10.5817/BL2022-1-5</identifier>
    <part>
		<extent unit="pages">
			<start>76></start>
		</extent>
	</part>
    <relatedItem type="host">
		<titleInfo>
			<title>Bohemica litteraria</title>			
		</titleInfo>         
	    <originInfo>
		  <dateIssued>2022</dateIssued>
	    </originInfo>
        <identifier type="issn">1213-2144</identifier>
        <part>        
            <detail type="volume">
                <number>XXV</number>
            </detail> 
            <detail type="issue">
                <number>1</number>
            </detail>            
        </part>
    </relatedItem>    	
</relatedItem>`

Nestrukturovaná poznámka:
`<relatedItem type="references" id="ref0003">
	<note type="source note">Clow GD, McKay CP, Simmons Jr. GM, and Wharton RA, Jr. 1988. Climatological observations and predicted sublimation rates at Lake Hoare, Antarctica. Journal of Climate 1:715-728.</note>
</relatedItem> `

Návrh by měl být součástí připravované verze DMF pro skládaná periodika, kterou plánujeme odeslat ke schvalování v nejbližších týdnech.

**Comment by kerschfilip** [comment]
Dobrý den, moc díky za návrh a že jste se tomu takhle pečlivě věnovali! Nemám k tomu v podstatě žádné připomínky.

Citovaných položek bývají většinou vyšší desítky. Určitě se ale vyskytnou extrémy na obě strany, takže použití ref0001 je určitě dobrý nápad. V dokumentu s návrhem mi jen připadá, že od `<relatedItem type="host">` je špatně zanoření - v režimu úprav jsem to doplnil, tak na to mrkněte, jestli se nepletu.

Ještě jednou díky!

**Comment by fremrovaK** [comment]
Dobrý den,

děkujeme za zpětnou vazbu i za upozornění. Máte pravdu – zanoření ještě upravíme.
Možnost zapsat použitou literaturu přidáme i do DMF pro e-periodika.

**Comment by FilipPavcik** [comment]
Možnost zapisovať použitú literaturu bola doplnená do[ DMF pro e-periodika 2.5](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornperiodika_2.5_final.pdf) i do [DMF pro skládaná periodika 1.2.](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_eborn_skladana_periodika_1.2.pdf) 
Issue zavírám. 

![image](https://github.com/user-attachments/assets/7c8c4b59-da1d-4cc7-b60d-3251d844839a)
