### ISSUE TITLE
Zápis jména autora ve vnitřní části- autoritní forma vs. zápis v knize

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#203]
Dobrý den,
mám dotaz k zápisu jména autora v kapitole. V jednotlivých ročnících almanachů literárních prací máme příspěvky od jedné autorky, které jsou ale v jednotlivých letech podepsány různým jménem, jednou rodným, podruhé jménem získaným svatbou.
Máme vždy použít to jméno, které je natištěno v obsahu nebo se řídit Autoritami NK, kde je autorita pro jen pro jedno jméno (získané svatbou)?
Přijde mi lepší druhá varianta, aby nedošlo k duplikaci jedné osoby v Krameriovi. Do pozn. vnitřní části je pak třeba dát údaj o rodném jménu?

Př. Augustinová Růžena (rodné), Písková Růžena (**xx0185657**, získané svatbou) - toto jméno mělo donedávna i autoritu pro rodné jméno. Po upozornění NK došlo k sloučení.

Pokud by se mělo napsat vždy to, co je vytištěno, tak rodné jméno by se uvedlo s datem narození, ale bez identifikátoru Autority?

Děkuji

**Comment by Drahotussky** [comment]
Sborníky mají katalogizační záznamy v SKC, např. cnb000168834, cnb000980196, cnb002129526.

**Comment by Drahotussky** [comment]
Prosím o odpověď. Děkuji

**Comment by fremrovaK** [comment]
Dobrý den,
jak je napsáno již výše, pokud má jméno autoritní záznam, doporučujeme řídit se jím. Pokud se vytištěné jméno liší od autoritní formy, lze je zanést do poznámky.
Není ale třeba do poznámky přidávat navíc další formy jména nebo pseudonymy, které vyčtete z autoritního záznamu.

**Comment by JezkovaV** [comment]
V souvislosti s přechodem na verzi MODS 3.8 bude v Definicích metadatových formátů doplněn element <alternativeName> pro zápis alternativního jména (pseudonym, přezdívka, rodné jméno atp.).

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)
