### ISSUE TITLE
Popis monografie_typ strany ilustrace/normální strana

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#204]
Zdravím,
rád bych se zeptal na názor, zda přiložené strany (a jim podobné) označit jako normální strany nebo ilustrace?
Jedná se o xerokopie/fotokopie různých novinových článku, dokumentů k soutěž Hlavnice A.C. Nora (stanovy, zápisy, úřední listiny,...), dopisů, pozvánek k soutěži, programy atd. 

![Hlavnice_ilustrace (1)](https://github.com/NLCR/Standard_NDK/assets/6399737/93ef0367-e9c5-4ad8-9f3b-1e513783397a)
![Hlavnice_ilustrace (2)](https://github.com/NLCR/Standard_NDK/assets/6399737/0ea7e998-5e9e-4d33-9b73-e92a9fb3f9a7)
![Hlavnice_ilustrace (4)](https://github.com/NLCR/Standard_NDK/assets/6399737/e5648406-bc05-44c1-90e0-bbb805473818)
![Hlavnice_ilustrace (5)](https://github.com/NLCR/Standard_NDK/assets/6399737/7c0516d6-c2fe-417b-aab7-b1a4c247afb2)
![Hlavnice_ilustrace (6)](https://github.com/NLCR/Standard_NDK/assets/6399737/f503419a-ece9-495b-b147-0cf1e35018dd)
![Hlavnice_ilustrace (7)](https://github.com/NLCR/Standard_NDK/assets/6399737/8146c8b9-10fe-4704-ad59-d0515a87ebfe)
![Hlavnice_ilustrace (8)](https://github.com/NLCR/Standard_NDK/assets/6399737/0b812f9f-dc3c-4751-89ed-04ae68b71813)
![Hlavnice_ilustrace (9)](https://github.com/NLCR/Standard_NDK/assets/6399737/47cf2053-a6f2-40ff-b1ad-4d213ece5960)

Děkuji

**Comment by PavlinaKocisova** [comment]
Dobrý den, a to je samostatná kopie originálu, nebo tyto xerokopie jsou součástí jiného dokumentu? Děkuji.

**Comment by Drahotussky** [comment]
Tyto a jiné xerokopie jsou součástí knih Hlavnice A.C. Nora (SYSNO 007884596, 007620497, 007884593,...). V knihách je popsán průběh soutěže v jednotlivých letech, informace o soutěžících, vítězích, organizátorech, doprovodných akcích, vydaných almanaších s vítěznými pracemi, jsou tam projevy členů poroty, dokumenty k soutě

 Přikládám vybrané obsahy

Děkuji

![Hlavnice_obsah (1)](https://github.com/NLCR/Standard_NDK/assets/6399737/db5e51d0-bf8f-48ae-8be9-bc73ae79f0c2)
![Hlavnice_obsah (2)](https://github.com/NLCR/Standard_NDK/assets/6399737/56493fcf-a7cf-4eda-b947-cb5096effba7)
![Hlavnice_obsah (3)](https://github.com/NLCR/Standard_NDK/assets/6399737/439601f2-8bd3-49ec-918f-c6a08b1bd6e8)
![Hlavnice_obsah (4)](https://github.com/NLCR/Standard_NDK/assets/6399737/48f7cccf-2c75-4013-9eaa-b461acde46cf)
ži atd.

**Comment by Drahotussky** [comment]
Prosím o odpověď. Děkuji

**Comment by JezkovaV** [comment]
Dobrý den,

pokud by byly fotokopie článků, dopisů a dalších typů dokumentů součástí knihy pouze v menší míře, mohly by být strany označeny jako ilustrace. Pokud však fotokopie tvoří podstatnou část celého dokumentu oproti ostatnímu textu, označují se jako normální strany.

Zdraví V. Ježková
odd. standardů digitálních sbírek
