### ISSUE TITLE
Element <note> - nejednotnost zápisu v Pravidlech popisu monografií a periodik a Standardech

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#205]
Zdravím,
v pravidlech pro popis se uvádí, že v jednom elementu <note> v <physicalDescription> jsou jednotlivé zápisy odděleny středníkem. 
Podle aktuálních standardů ale má mít každý zápis vlastní element <note>.

**Comment by Drahotussky** [comment]
Ano, mám na mysli tuto poznámku.

**Comment by Drahotussky** [comment]
Prosím o odpověď. Děkuji

**Comment by JezkovaV** [comment]
Dobrý den,

děkujeme za upozornění, platí znění v DMF, tedy že pro každou poznámku je nutno vytvořit nový element.

Varianta sdruženého zápisu byla v Pravidlech pro popis nejspíše uvedena pro případ, že by systém neumožňoval vícečetný zápis poznámky. V tom případě je však potřeba přizpůsobit nastavení systému. Formulace v Pravidlech pro popis bude v další aktualizaci upravena.

Zdraví V. Ježková
Odd. standardů digitálních sbírek NK ČR

**Comment by JezkovaV** [comment]
Zapracováno do Pravidel pro popis periodik (verze 8.6) a Pravidel pro popis monografií (verze 2.3)

**Comment by Drahotussky** [comment]
Dobrý den,
ještě bych se rád zeptal, zda vytváření nového elementu pro každou poznámku platí na všech úrovních (číslo, ročník i titul)? V Pravidlech pro periodika je zmínka jen u čísla.

**Comment by JezkovaV** [comment]
Dobrý den, ano platí. V Definicích metadatových formátů je na každé úrovni uvedeno, že pro každou poznámku je nutno vytvořit nový element `<note>`. V případě mapování polí bibliografického záznamu by mělo platit, že každému jednomu samostatnému poznámkovému poli by měl odpovídat jeden element `<note>`.

**Comment by Drahotussky** [comment]
Když např. doskenuji u novin jednu stranku z archivu a jednu z muzea, tak se vytvoří dvě poznámky? Nebo, když bude chybet v knize obalka i desky, tak taky budou dve poznamky?

Děkuji

**Comment by JezkovaV** [comment]
Postup by měl být obdobný, jako při zápisu poznámek v bibliografickém záznamu. Je potřeba uvážit, které informace spolu logicky souvisí.

Tedy pokud budu zapisovat informaci o chybějících částech, nabízí se zapsat společnou poznámku, např. "Chybějící obálka a desky". U doskenů např. "Zápůjčky: archiv (str. 5, 40, 42); muzeum (str. 50-60)".
