### ISSUE TITLE
Popis periodika - typ strany volný list vs. errata

### ISSUE THREAD

**Issue by kotulanovaz** [NLCR/Standard_NDK#206]
Dobrý den,

pokud mám u periodika volný list a na něm jsou vytištěna errata, jaký typ strany mám z těchto dvou (volný list, errata) zvolit u popisu?

Děkuji.

**Comment by JezkovaV** [comment]
Dobrý den,

přednost má specifičtější typ strany, použijte tedy pro zápis typ strany errata.

V. Ježková
odd. standardů digitálních sbírek
