### ISSUE TITLE
Atribut type u top elementu note

### ISSUE THREAD

**Issue by pepinovimr** [NLCR/Standard_NDK#208]
Dobrý den,
máme několik nejasností ohledně top elementu note, který se přebírá z 245, $c a z polí 5XX.

V popisu tohoto elementu je v závorkách hodnota „statement of responsibility“ a zároveň pro tento existuje atribut „type“, který se ale vyskytuje pouze v Titulu pro periodika (V Title vícesvazkové monografie  a Volume klasické i vícesvazkové vícesvazkové monografie není).

1. Pro které typy MODS se má vyplňovat atribut type? Je to opravdu pouze pro titul periodik?
2. Jakých hodnot může atribut type nabývat? Momentálně do něj vyplňujeme pouze hodnotu „statement of responsibility“ pokud je zdroj poznámky 245, $c. V ostatních případech atribut type nevyplňujeme, ale podle mapování z MARC do MODS může být hodnot těchto atributů více (Nebo je někde ještě jiný výčet možných hodnot pro tento atribut?):
![image](https://github.com/NLCR/Standard_NDK/assets/101387485/db7de98c-60f6-4365-a717-8badc42b67f4)

Předem děkuji za odpovědi, 
Josef Vimr

**Comment by JezkovaV** [comment]
Dobrý den,

1. Pokud není v DMF možnost použití atributu výslovně uvedena, neznamená to, že využít nelze, určující je, co umožňují specifikace MODS. Atribut „type“ je tedy možné vyplňovat u poznámek v rámci periodik i monografií.

2. Pro zápis hodnoty atributu „type“ je doporučeno využít seznam používaných hodnot dostupný na webu MODS (viz https://www.loc.gov/standards/mods/mods-notes.html)

Formulace v definicích metadatových záznamů bude v další aktualizaci upravena.

Zdraví V. Ježková
odd. standardů digitálních sbírek

**Comment by pepinovimr** [comment]
Dobrý den,
děkujeme za odpověď.
