### ISSUE TITLE
typ strany příloha

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#209]
Narážíme u monografií na strany označené jako příloha, u kterých si myslíme, že by je bylo dobré je i popsat jako přílohu (ne vyčlenit jako přílohu monografie, ale popsat tak ty jednotlivé strany). Dávám k diskusi.

**Comment by JezkovaV** [comment]
Dobrý den, na základě společné diskuze v rámci jednání Pracovní skupiny pro digitalizaci textových dokumentů 11. 6. 2024 bylo dohodnuto nezavádět přílohu jako nový typ strany.
