### ISSUE TITLE
originInfo/dateIssued - Copyright

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#211]
Dobrý den,

prosím o radu, jak správně zapisovat do `originInfo` datum ze záznamu AACR z pole `260 $c` v případě, že je datum nečíselné - obsahuje například hodnotu c (©), např. "c1999". Řešíme to v rámci stahování záznamů do [ProArcu](https://github.com/proarc/proarc/issues/1648)

U této publikace: https://katalog.lib.cas.cz/KNAV/Record/001824180?sid=20783502#details máme

- v poli 008 zapsán rok 2014:  `141008s2014 xr e ||| ||cze d`
- ale v v poli `260 $c` je zapsáno `c2014`

V tuto chvíli nám vznikají dvě `originInfo`, jedno z hodnotou z pole `008`, druhé s hodnotou z pole `260`:
```xml
<mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xr</mods:placeTerm>
        </mods:place>
        <mods:publisher>Historický ústav AV ČR, v.v.i.</mods:publisher>
        <mods:dateIssued encoding="marc">2014</mods:dateIssued>
        <mods:edition>Vyd. 1.</mods:edition>
        <mods:issuance>single unit</mods:issuance>
</mods:originInfo>

<mods:originInfo>
        <mods:place>
            <mods:placeTerm type="text">Praha</mods:placeTerm>
        </mods:place>
        <mods:publisher>Historický ústav AV ČR, v.v.i.</mods:publisher>
        <mods:dateIssued>c2014</mods:dateIssued>
        <mods:issuance>single unit</mods:issuance>
</mods:originInfo>
```

V pravidlech pro popis monografií je napsané, že 
![image](https://github.com/NLCR/Standard_NDK/assets/57805328/90da62da-065a-417d-b02f-f844070161b1)

A také jsem koukal, že v NDK se v obdobných případech používá asi jen ta hodnota z `260`. Např. tady: https://ndk.cz/uuid/uuid:f2fd6f90-5b68-11e5-bf4b-005056827e51

Z toho mi vychází, že bychom měli z katalogizačního záznamu vytvořit jen jedno `originInfo` a to s `<mods:dateIssued>c2014</mods:dateIssued>`. Prosím o potvrzení/vyvrácení, než si to do ProArcu takto zamontujeme. 

Díky :-)

**Comment by JezkovaV** [comment]
Dobrý den,

zápis data copyrightu ve formátu „c2014“ je z hlediska stávajících Pravidel pro popis v pořádku.

Element originInfo by se měl v metadatech opakovat pouze v případě, že záznam obsahuje více polí 260, tedy v případě údajů v polích 260 a 008 se jedná o duplicitní údaj, ze kterého se vytváří pouze jedno dateIssued. Pokud vycházíme z mapování MODS (https://www.loc.gov/standards/mods/v3/mods-mapping-3-7.html#publication), do dateIssued by se měl převést údaj z pole 260 $c a pro případ copyrightu je třeba nastavit podmínku, že pokud je v poli 008/06 hodnota „t“, vždy se přebírá hodnota z pole 008/11-14 do elementu copyrightDate.

V DMF bude doplněna možnost zápisu <copyrightDate> pro AACR, jako je tomu u RDA a opraveno mapování. Stejně tak bude pro AACR doplněn element dateOther, do kterého je mapováno pole 260 $g.

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)
