### ISSUE TITLE
dateIssued vs. dateOther

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/Standard_NDK#213]
Zdravím,

ze standardu (alespoň podle mě) není úplně jasné, jestli stačí v rámci `originInfo` vyplnit pouze element `dateOther`, protože `dateIssued ` je označený jako povinný.

V DMF pro monografie je to uvedeno takto:
![image](https://github.com/NLCR/Standard_NDK/assets/57805328/f43783bd-1627-4931-895b-041020584a99)

Vyplývá mi z toho, že v případě titulu jako je [tento](https://katalog.lib.cas.cz/AV/Record/001185611#details), kde je v poli `264`:
![image](https://github.com/NLCR/Standard_NDK/assets/57805328/c6be347f-73f9-4626-a185-267e74e43734)
by v originInfo mělo být pouze `dateOther`. Je to prosím správně?

```xml
<mods:originInfo eventType="production">
      <mods:place>
        <mods:placeTerm type="text">Praha</mods:placeTerm>
      </mods:place>
      <mods:dateOther type="production">1989</mods:dateOther>
      <mods:issuance>single unit</mods:issuance>
</mods:originInfo>
```
Validátor mi v tomto případě nehlásí, že by `dateIssued` chybělo, ale protože u `dateOther` není mapování do DC, tak hlásí, že chybí `dc:date`:
```
mets_abb060-000003.xml: DCMD_VOLUME_0001: /oai_dc:dc: nenalezen očekávaný povinný element 'dc:date': Očekáván alespoň jeden povinný element dc:date obsahující datum vydání předlohy, nebo datum vydání copyrightu.
```

Díky!

**Comment by FilipPavcik** [comment]
Ahoj, 

áno, je to správne tak, ako si uviedol v príklade vyššie. Aby som to ešte dovysvetlil: element `<dateIssued>` je povinný iba v prípade výskytu **pola 264_1 $c**, tj. iba v prípade použitia `<originInfo evenType="publication">`. 

V prípade výskytu ďalších hodnôt v druhom indikátore v **poli 264 $c**, ako sú: **264_0, 264_2, 264_3** nie je `<dateIssued>` povinné, ale má sa využiť `<dateOther>`. Prípadne, pri výskyte **264_4** sa má využiť `<copyrightDate>`. 

Ohľadom mapovania do DC máš pravdu, že to v DMF na niektorých miestach chýba. Do DMF pro eborny to bude doplnené ešte pri súčasnej aktualizácii.

**Comment by FilipPavcik** [comment]
Mapovanie elementu `mods:dateOther` do DC je doplnené do [DMF pro e-monografie 3.0](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornmonografie_3.0_final.pdf), [DMF e-periodika 2.5 ](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornperiodika_2.5_final.pdf)i [DMF pro skládaná periodika 2.1](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_eborn_skladana_periodika_1.2.pdf). 
Issue zatváram.

**Comment by JezkovaV** [comment]
Zkontrolováno a doplněno chybějící mapování `mods:dateOther` do DC u textových DMF a gramodesek.

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)
