### ISSUE TITLE
NDK Periodikum 2.0

### ISSUE THREAD

**Issue by SykoraLukas** [NLCR/Standard_NDK#215]
V sekci metadatového popisu NDK čísla pro MODS a DC je špatně zanořen atribut mods:titleInfo:title type u mutačních vydání.  Správně by měl být na úrovni mods:titleInfo.

**Comment by JezkovaV** [comment]
Dobrý den,

děkujeme za upozornění, atribut _type_ bude v nejnovější verzi DMF pro periodika přesunut správně pod topelement <titleInfo>.

V. Ježková
odd. standardů digitálních sbírek

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1)
