### ISSUE TITLE
návrh přejmenování mastercopy

### ISSUE THREAD

**Issue by bezverec** [NLCR/Standard_NDK#216]
Do některé z budoucích verzí standardů navrhuji v SIP změnit adresář `mastercopy` na `archivalcopy` nebo `archivecopy`, u soborů jp2 uvnitř změnit `mc` na `ac`. Ve standardu pro obrazová data se výraz archival copy dokonce vyskytuje přednostně. Můj argument není politická korektnost, ale podle mého názoru větší srozumitelnost.

Jedná se o návrh, nikoliv o požadavek. Dovedu si představit více komplikací než užitku.

**Comment by vjirousek** [comment]
Já bych takové změny velmi nedoporučoval, pokud k nim není opravdu vážný důvod. Náklady, které jsou s podobnými změnami spojené, téměř jistě značně převáží nad mírou užitku.

**Comment by bezverec** [comment]
Každopádně kdyby se někdy o větších změnách uvažovalo, chtěl jsem, aby to zaznělo.
Já to tedy prozatím uzavřu jako _not planned_ :)
