### ISSUE TITLE
Převod polí 490 a 830 do elementu relatedItem

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#219]
Dobrý den,
rád bych se zeptal, jak by měl správně vypadat převod polí 490 a 830 (údaje o edicích) do elementu relatedItem.

Pole 490:
`<datafield` `tag="490">`
        `<subfield` code="a">Novinky `;</subfield>`
         `<subfield` code="v">sv. `258</subfield>`
      `</datafield>`

`<datafield` `tag="490">`
        `<subfield` code="a">České. Řada II `;</subfield>`
         `<subfield` code="v">sv. `8</subfield>`
      `</datafield>`

 Převod:
 `<relatedItem` `type="series">`
    `<titleInfo>`
      `<title>Novinky ;` sv. `258</title>`
    `</titleInfo>`
  `</relatedItem>`

  `<relatedItem` `type="series">`
    `<titleInfo>`
      `<title>České.` Řada II ; sv. `8</title>`
    `</titleInfo>`
  `</relatedItem>`

Pole 830:
`<datafield` `tag="830">`
        `<subfield` code="a">Novinky `;</subfield>`
         `<subfield` code="v">`258</subfield>`
      `</datafield>`

`<datafield` `tag="830">`
        `<subfield` code="a">České (Melantrich). `;</subfield>`
       `<subfield` code="p">Kolo `;</subfield>`
      `<subfield` code="n">II. řada `;</subfield>`
         `<subfield` code="v">`8</subfield>`
      `</datafield>`

Převod:
 `<relatedItem` `type="series">`
    `<titleInfo>`
      `<title>Novinky ;` `258</title>`
    `</titleInfo>`
  `</relatedItem>`

 `<relatedItem` `type="series">`
    `<titleInfo>`
      `<title>České (Melantrich). `8</title>`
      <partName>Kolo</partName>
     <partNumber>II.  řada</partNumber>`
    `</titleInfo>`
  `</relatedItem>`

U polí 490 a 830 se podpole **v** převádí do elementu title?
podpole **n** do elementu partNumber?
podpole **p** do elementu partName?

Děkuji

**Comment by JezkovaV** [comment]
Dobrý den,

mapování polí bibliografického záznamu by podle MODS mělo vypadat takto:

**pole 490**
$a Údaj o edici: `<partName>`
$v Označení svazku/pořadí: `<partNumber>`

**pole 830**
$a Unifikovaný název: `<title>`
$n Číslo části/sekce díla: `<partNumber>`
$p Název části/sekce díla: `<partName>`
$v Označení svazku/pořadí: `<partNumber>`

Podle MODS by se měly objevit pod společným `<relatedItem type="series">` samostatné elementy `<titleInfo>` pro každé pole bibliografického záznamu, zapsalo by se tedy takto:

**Pole 490:**
`<relatedItem type="series">`
     `<titleInfo>`
                `<partName>`Novinky ;`</partName>`
                `<partNumber>`sv. 258`</partNumber>`
     `</titleInfo>`
     `<titleInfo>`
                `<partName>`České. ; Řada II ;`</partName>`
                `<partNumber>`sv. 8`</partNumber>`
     `</titleInfo>`
`</relatedItem>`

**Pole 830:**
`<relatedItem type="series">`
     `<titleInfo>`
                `<partName>`Novinky ;`</partName>`
                `<partNumber>`258`</partNumber>`
     `</titleInfo>`
     `<titleInfo>`
                `<title>`České (Melantrich). ;`</title>`
                `<partNumber>`8`</partNumber>`
                `<partName>`Kolo ;`</partName>`
                `<partNumber>`II. řada ;`</partNumber>`
     `</titleInfo>`
`</relatedItem>`

Mapování polí MODS je dostupné na odkazu [](https://www.loc.gov/standards/mods/v3/mods-mapping-3-7.html#relateditem)

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)

**Comment by JezkovaV** [comment]
Dobrý den, z nepřehledného mapování MODS jsme chybně vyčetli mapování hodnoty z pole 490 $a (Údaj o edici). Správně by se měla mapovat do elementu <title>, nikoliv <partName>. Omlouváme se za zmatení, opravu provedeme hned v další verzi DMF. Správně je tedy:

**pole 490**
**$a Údaj o edici: `<title>`**
$v Označení svazku/pořadí: `<partNumber>`

**pole 830**
$a Unifikovaný název: `<title>`
$n Číslo části/sekce díla: `<partNumber>`
$p Název části/sekce díla: `<partName>`
$v Označení svazku/pořadí: `<partNumber>`
