### ISSUE TITLE
periodika - rozsah dokumentu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#31]
```
Jaký máte problém?
Jaký údaj vyplňovat do rozsahu dokumentu u periodik? Poslední tištěný 
údaj nebo poslední dopočítané číslo stránky?

Jak to je nyní?
Podle pravidel by se mělo zadávat poslední tištěné

Jaké by podle vás bylo ideální řešení?
Vzhledem k tomu, že paginace v periodikách je velmi pestře nesourodá, 
navrhuji zadávat poslední dopočítané. Případně zanechat tuto možnost 
do určitého rozsahu (např 50 stran).

Napište příklad.




```

Original issue reported on code.google.com by `jelenna...@gmail.com` on 15 Mar 2013 at 1:57

**Comment by PavlinaKocisova** [comment]
Standard pro periodika v. 1.6 se odkazuje na pravidla RDA, kde je řečeno:

	a) vždy se používá poslední číslovaná strana, sloupec, list
	b) nečíslované stránky nepodstatné povahy se nedopočítávají (volné či s reklamami)
	c) při zápisu se používá typ písma shodný s publikací
	d) uvádí se číslované i nečíslované sekvence, pokud je stránkování příliš komplikované, zapíše se celkový počet stran s výrazem "v různém stránkování"
	e) pokud stránky nejsou číslovány vůbec, spočítáme je a napíšeme s výrazem "nečíslovaných stran"

	Číslování je pak řešeno i v rámci současných pravidel pro popis.
