### ISSUE TITLE
Jakým způsobem by měli být zapsány změny v PSP balíku

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#33]
```
Jaký máte problém?
1. Z standardu není přesně zřejmé, jak se mají zapsat změny v popisu ať 
už MODSu nebo přímo hlavního METSu.
2. Dále je otázkou zda a jakým způsobem se má zachovávat historie změn. 
Jestli např. u MOdsu opakovat celé recordInfo pro každou změnu nebo jenom 
do něj přidat další recordChangeDate.





```

Original issue reported on code.google.com by `ludane...@gmail.com` on 4 Jul 2013 at 2:24

**Comment by PavlinaKocisova** [comment]
Současný standard ke změnám v metsu používá atribut LASTMODDATE v hlavičce. Ke změnám v jednotlivých úrovních zápisu pak zmiňovaný element <recordChangeDate>, který se nijak nezdvojuje, ani se nezdvojuje celá sekce <recordInfo>, při aktualizaci se jen vloží nové datum.

Jiná situace nastane při naprosto zásadních změnách v zápisu (změna názvu dokumentu, jména autora a podobné zásadní změny), v tom případě doporučujeme udělat komplet nový mets.
