### ISSUE TITLE
Deníky Bohemia a jejich přílohy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#37]
```
Chceme zdigitalizovat některé z Deníků Bohemia. A narážíme na problém, 
co s přílohami. 

1. Pravidelné přílohy, které mají svoje číslování, stránkování, 
mají vlastní záznam => zdigitalizují se zvlášť, tam je to jasné.

2. Jednorázové přílohy u čísla, nemají vlastní záznam => 
zdigitalizujeme s číslem a popíšeme jako přílohu čísla, taky jasné.

PROBLÉM 3. Pravidelné přílohy, které jsou v per. tak porůznu - mají 
vlastní záznam, takže by se daly udělat zvlášť, ale: někdy jsou na 
konci čísla, jindy uprostřed - a tady třeba má číslo stránky 1-8, 
následují strany přílohy I-VIII a pak zas stránky čísla, ale od str. 17. 
Co s tím? (teda kromě nejjednoduššího řešení nepouštět se do Deníků 
Bohemia vůbec:-)).




```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 8 Jul 2014 at 11:53

**Comment by PavlinaKocisova** [comment]
Asi bych to řešila poznámkou na úrovni čísla, která by upřesnila, že se nejedná o chybu číslování, a samostatně zpracovanou přílohu pak nalinkovala přes element <relatedItem>, který  v sobě může nést většinu ostatních elementů. Lepší řešení mě nenapadá. 

Systémově se přílohy upřesňovaly v pravidlech pro popis periodik, verze 8 (v současné době na stránkách NDK), ale obávám se, že takovýto příklad zatím systémové řešení nemá.
