### ISSUE TITLE
povinnost pro element <role>

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#39]
mods:role - povinnost elementu (M) v DMF pro monografie (ve všech verzích) neodpovídá požadavkům na minimální ani doporučený záznam RDA/MARC21 pro textové monografické zdroje. Úpravu povinnosti je též potřeba vyřešit na straně validátoru. V rámci DMF by bylo také vhodné opravit formátování aby byl element mods:role správně zanořen pod element mods:name.

**Comment by PavlinaKocisova** [comment]
Máte pravdu, <role> byl špatně zanořen, opravili jsme to. Co se týče povinnosti oproti minimálnímu záznamu, provedeme úpravu a při nejbližší aktualizaci též přenastavíme validátor.

**Comment by PavlinaKocisova** [comment]
Oprava je součástí verze standardu vyvěšené k 26.1. 2018.

**Comment by PavlinaKocisova** [comment]
spojeno s issue https://github.com/NLCR/komplexni-validator/issues/58
