### ISSUE TITLE
více čnb pro jeden dokument

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#4]
```
Některým dokumentům bylo přiděleno více čnb.

Na základě upozornění následně NK upřesní, které z nich je platné a 
které nikoliv.

Je třeba/vhodné následně při indexaci uvést obě čnb? Pokud ano jak 
rozlišit, které z nich je platné a které ne?





```

Original issue reported on code.google.com by `jelenna...@gmail.com` on 16 Nov 2012 at 2:05

**Comment by PavlinaKocisova** [comment]
Tuto problematiku řeší pravidla registru digitalizace, uvedené například na stránkách Caslinu:

http://www.caslin.cz/caslin/spoluprace/sluzby-souborneho-katalogu-cr/jak-spravne-postupovat-nez-zacne-knihovna-digitalizovat-dokument

http://www.registrdigitalizace.cz/rdcz/uzivatele/ccnb.htm
