### ISSUE TITLE
Pravidla pro popis periodik - více verzí v jednom dokumentu

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#40]
Pravidla pro popis periodik obsahují v jednom dokumentu verzi 8 i 8.2 (pod verzí 8.2 následuje starší 8). Při práci s dokumentem může uživatel snadno zabrousit do staré verze Pravidel aniž by si uvědomil že pracuje se starou verzí.

https://docs.google.com/document/d/1zSriHPdnUY5d_tKv0M8a6nEym560DKh2H6XZ24tGAEw/edit?usp=sharing

**Comment by PavlinaKocisova** [comment]
V současnosti na webu NDK visí Pravidla popisu v pdf dokumentech, přičemž verze byly odděleny. Děkujeme za upozornění.
