### ISSUE TITLE
neschválená změna názvové konvence pro soubor hlavní METS

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#41]
DMF na webu NDK ve verzi 1.7 s 1.3 (aktualizované 25. 1. 2018) obsahují změny neprojednané a neschválené ze strany formátového výboru. Oproti odhlasované verzi DMF došlo ke změně názvové konvence, konkrétně pojmenování hlavního mets souboru. Změny jsou v kapitole 6) Názvová konvence složek a souborů, podkapitola Pojmenování souborů:

schválené znění:
hlavní METS musí obsahovat předponu "mets" a příponu .xml
(např. mets_nk-00027x.xml)

uveřejněné znění:
hlavní METS musí obsahovat předponu "hlavni_mets" a příponu .xml
(např. mets_nk-00027x.xml)

Vzhledem k neproběhnuvšímu projednání změny a výrazným negativním dopadům na infrastrukturu NDK žádám o odstranění této neschválené změny.

**Comment by PavlinaKocisova** [comment]
Ano, jednalo se o nedorozumění, které je nyní opraveno a aktuálně již na webu NDK visí verze bez této neschválené změny. Děkujeme za upozornění.
