### ISSUE TITLE
mapování <dateCreated> pro rukopisy

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#42]
Na straně 34 DMF 1.3 pro monografie (s. 30 DMF 1.7 pro periodika) je u elementu <dateCreated> předepsáno přebírání z katalogu z pole:

264_1$c pokud je LDR/06="d","f","t"

Myšleno je zřejmě 264_0$c.

**Comment by PavlinaKocisova** [comment]
Tato chyba bude opravena ve verzi 7.3.1 pro periodika a 1.3.1 pro monografie, která vyjde během následujích pár dní.
