### ISSUE TITLE
MODS stránky

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#43]
Bylo by možné změnit MODS pro jednotlivou stránku tak, aby byla celá tato úroveň povinná? Bylo by to potřeba třeba kvůli tomu, aby se v Krameriovi neměnila uuid stran.

**Comment by PavlinaKocisova** [comment]
Dobrý den, pro tento rok jsme slíbili dobrovolnost, ale pro příští již počítáme se změnou na povinnost i pro tuto úroveň.

**Comment by krizovj** [comment]
Mohlo by to issue prosím zůstat otevřené, dokud to nebude skutečně zahrnuto ve standardu? 
Díky

**Comment by MirkaBenackova** [comment]
Úroveň strany je povinná od verzie DMF 1.4 pre monografie a verzie 1.8 pre periodiká (obe vydané 30. 11. 2019).
