### ISSUE TITLE
Povinnost u elementu mods:partNumber pro výtisk periodika

### ISSUE THREAD

**Issue by vjirousek** [NLCR/Standard_NDK#44]
Definice metadatových formátů pro periodika se rozcházejí s Pravidly pro popis periodik ve věci povinnosti u elementu <mods:partNumber> pro výtisk periodika:

**Pravidla pro popis periodik (v8.2.1), kapitola 2.3 - Číslo vydání, odst. Chybné číslování výtisku, bod c)**
_"c. Číslo výtisku není uvedeno a pokud nelze dopočítat,​ číslo výtisku se nevyplní. V případě ročenek se uvede číslo výtisku 1 nebo logicky tak, aby byla doplněna řada."_
viz: http://www.ndk.cz/standardy-digitalizace/pravidla_pro_popis_periodik_v8-2-1 (strana 8)

vs.

**DMF pro digitalizaci periodik (v 1.7), kapitola 7.3.1.3 - MODS a DC pro číslo periodika**
![obrazek](https://user-images.githubusercontent.com/22765973/36537878-bb19cf74-17d1-11e8-92f6-53f7fcb2292e.png)
viz: http://www.ndk.cz/standardy-digitalizace/dmf_perio_17 (strana 37)

**Comment by vjirousek** [comment]
Již došlo k aktualizaci jak PPPP (11.4.2018) tak i DMF (23. 3. 2018/17.10.2018), byla tedy prosím tato věc vyřešena?

**Comment by krizovj** [comment]
Teď jsem na to koukala a je to tam vlastně pořád stejně. 
V pravidlech je tohle:
![partnumber](https://user-images.githubusercontent.com/21309201/49357091-73206980-f6ce-11e8-8115-7205bf00fbff.jpg)

A je tam pořád uvedeno, že když to nejde dopočítat ani nijak zjistit, tak se to nemusí vyplnit. Ale v DMF je povinnost M. Což si odporuje.

Je to problém kvůli ProArcu, nevím, jestli tam půjde nastavit u pole, kde je povinnost M, že to vlastně za určitých okolností M není. Zjistím a dám vědět.

**Comment by PavlinaKocisova** [comment]
Dobrý den, bohužel jsme při aktualizaci specifikací tento problém zapomněli odstranit. Prozatím tedy prosím o vyplňování podle doporučení Pravidel pro popis periodik, které v tomto případě jsou nadřazené tomu, co je uvedeno v DMF. Aktuálně se další verze DMF neplánuje, nicméně píšeme to na seznam oprav.

**Comment by PavlinaKocisova** [comment]
Tato oprava vyjde v aktualizaci DMF periodika verze 1.8.
