### ISSUE TITLE
ččnb u vícesvazkové monografie

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#45]
Setkáváme se s tím, že u vícedílné monografie byla původně ččnb přidělena několika/všem svazkům jednotlivě, pak jsou sloučeny na jeden záznam vícedílky a ta "jednotlivá" ččnb byla zneplatněna. V bib záznamu pak je jedno platné a zbylá neplatná. Co s tím teď v MODS - na úrovni vícedílky mít to platné + všechna neplatná, jasné. Pokud víme, ke kterému svazku patřilo které zneplatněné, tak je to asi taky jasné, že v každém svazku by pak bylo to jeho původní jako neplatné. Ale když už nejsme schopni zjistit, ke kterému svazku bylo původně které ččnb?

**Comment by luckajirku** [comment]
Za nás je možné issue zavřít, jen by se to asi mělo objevit jako doporučení v pravidlech popisu.

**Comment by MirkaBenackova** [comment]
Poznámka vysvetľujúca túto situáciu bola zahrnutá do pravidiel pre popis monografii (zverejnených 20.12.2019).
