### ISSUE TITLE
Elektronické publikace - rozdělení PDF x intelektuální entita

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#47]
Potřebovali bychom, aby bylo možné rozdělit PDF na menší části. U periodik na články a u monografií na kapitoly. V současném standardu je to tak, že jedno PDF je buď celá monografie nebo číslo u periodika. Když ale máme zpracovaná metadata pro jednotlivé články (kapitoly), jak by se to zobrazovalo třeba v Krameriovi, když to PDF není rozdělené? 

Klidně by to šlo udělat tak, že v balíčku bude PDF celého čísla/monografie, ale zároveň by mělo být možné, aby tam byla také PDF pro jednotlivé články/kapitoly. Nevím, jak by to bylo nejlepší z hlediska struktury balíčku. Takže by mohla být složka [original] a v ní by byly soubory jak pro celou intelektuální entitu, tak pro jednotlivé části a nebo by v této složce mohla být ještě jedna podsložka, kde by byly ty jednotlivé části. 

Hodilo by se toto rozdělení ještě někomu dalšímu?

**Comment by zabak** [comment]
Je to nezbytné, mít všechno duplicitně? V novém klientu je řešeno takto:
http://knav.kramerius.rychtar.cloud/view/uuid:d118a57e-8d42-4744-9b2b-e76484f4df16?article=uuid:089eaf3b-753e-44f6-adbc-32ea0f13fe10
Pokud by uživatel chtěl stáhnout konkrétní článek, tak vyjmout jednotlivé stránky z pdf čísla a udělat z nich pdf ke stažení není problém.

**Comment by zabak** [comment]
Pokud to už vzniká takhle rozdělené, dá se zase naopak z těch dílčích pdf poskládat celé číslo. Nebo ne?

**Comment by krizovj** [comment]
To nevím, asi by to šlo, ale my to potřebujeme mít i v Krameriovi rozdělené na ty články.

**Comment by zabak** [comment]
No právě, že by v případě potřeby poskládalo uměle z těch dílčích pdf a nebylo součástí balíčku.

**Comment by zabak** [comment]
Bylo by dobré, aby nebylo nutné držet více verzí téhož dokumentu, protože to jednak zbytečně zabírá místo a jednak pokud by se dělaly s dokumentem nějaké úpravy, musely by se dělat na obou verzích. Z toho hlediska buď můžu mít jedno pdf pro čísla nebo víc pdf pro články, ze kterých to číslo poskládám (ale pak musím dělat "články" i z nedůležitých stránek). Podobně v Krameriu můžu to číslo poskládat z více pdf do jednoho virtuálního čísla, nebo mohou být stejně zobrazena metadata článků k jednomu pdf čísla. 
Myslím si, že obojí by mělo být možné a uživatel nemusí poznat, jak je to vevnitř udělané (tak jak mi na první pohled nedošlo, že u toho příkladu jde o sadu více pdf). Snažil bych se ale vyhnout tomu, aby se uchovávala stejná data dvojmo, spíš by bylo dobré naučit krameria aby se uměl vypořádat s jednou nebo druhou variantou tak, že by to splnilo uživatelské požadavky ať už jsou jakékoli (nezasahovat kvůli tomu do podoby dat).

**Comment by krizovj** [comment]
Souhlasím, bude nám stačit když bude možné obojí: buď mít jedno PDF pro číslo nebo více PDF pro články.

**Comment by vjirousek** [comment]
Domnívám se že bylo vyřešeno vydáním standardu pro skládaná periodika, případně prosím o znovuotevření. 
https://standardy.ndk.cz/ndk/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf
