### ISSUE TITLE
Vícesvazková mon. - rozšířit popis na úrovni vícesvazku, aby odpovídal bib záznamu

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#48]
U vícesvazkových monografií jde popis na úrovni vícesvazku proti bib záznamu.
Bib záznam: úplný popis je na úrovni vícesvazku x popis dle NDK standardu: na úrovni vícesvazku je popis osekaný na pár údajů a všechny údaje jsou až na úrovni popisu jednotlivých svazků.
Kromě toho, že to je nelogické a uživatel by tyto údaje uvítal, by tato změna byla zjednodušením i pro samotnou produkci.

**Comment by krizovj** [comment]
Souhlasím, určitě by to bylo lepší i pro nás. Dá se pak stáhnout záznam z katalogu a nemusí se vytvářet ručně.

**Comment by nezbedova** [comment]
Také by se nám to velmi hodilo.

**Comment by luckajirku** [comment]
Můžu se zeptat, kdy na tento problém přijde řada? Díky.

**Comment by godnat** [comment]
Dobrý den,

aktuálně se tím zabýváme, změna se projeví v nejbližší větší úpravě standardu NDK (zřejmě verze 1.4 nebo 2.0)

**Comment by PavlinaKocisova** [comment]
Zdravím a oznamuji, že byl vytvořen návrh nové podoby popisu vícesvazku na úrovních TITLE a VOLUME, který přenese většinu povinných informací na titulovou vrstvu. V současné době je tento návrh v rukách členů Pracovní skupiny pro digitalizaci textových dokumentů pro projednání připomínek.

**Comment by vjirousek** [comment]
K rozšíření popisu na úrovni vícesvazku došlo v DMF pro monografie ve verzi 2.0 z 10. 10. 2022
