### ISSUE TITLE
NDK standard pro STT

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#49]
Uvítali bychom vznik NDK standardu pro staré tisky (s nepovinným OCR a ALTO).

**Comment by PavlinaKocisova** [comment]
Potřebou vzniku případných nových standardů se nově bude zabývat Pracovní skupina pro textové dokumenty pod Formátovým výborem.

**Comment by PavlinaKocisova** [comment]
K digitalizaci starých tisků v prostředí linek pro digitalizaci novodobých dokumentů KNAV a Pracovní skupina pro staré tisky vydaly následující metodický pokyn (verze 1 z května 2020) https://standardy.ndk.cz/ndk/standardy-digitalizace/Metodikapropopisstarchtisk1.pdf.
