### ISSUE TITLE
dlouhodobě udržitelné pojmenování PSP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#5]
```
Nejistoty s ČCNB (duplicitní, vícesvazková díla, díla nebohemikální, 
přesto se vztahem k regionu ap.), přidělení URN:NBN před začátkem tvorby 
PSP (ale obvykle ne dříve, digitalizovaná entita obecně nemusí být v RD 
evidována) vedou k vyslovení hypotézy, že by nejvhodnějším 
pojmenováním z hlediska automatizace (už ne tak jednoznačně z hlediska 
lidské kontroly) bylo použití UUID, využitelné dále jako identifikátor 
pro K4. Standardy z dubna 2012 v tomto směru nehovoří jednoznačně.

1. používáme ččnb, nicméně aktuálně se stalo, že bylo doporučeno 
kvůli neshodě v počtu stran v alephu použít jiné

2. předávaná struktura PSP je vázána opět na ččnb, pro periodika je to 
ovšem vázáno na extenzi jednotlivých vydání, protože ččnb je shodné 
pro všechny ročníky; u UUID naproti tomu k podobnému problému nemůže 
dojít, je vázáno na číslo

3.protiváhou jeho univerzálnosti je chybějící vazba na cokoliv ;), takže 
z jeho obsahu nelze dohledat informace přímo, nemá své pole v Alephovi.
Jeho obraz v prostoru 1D čárových kódů je poměrně monstrózní (délka), 
některé muzejní tiskoviny je nevhodné čárovým kódem opatřit...

Existují nějaké Best Practices pro nasazení jednotného pojmenování bez 
závislosti na typu a výbavě digitalizující instituce? Výčet možností z 
definice digitalizace je spíše doporučením než normou. (handle, uuid, 
urn:nbn, ccnb).

Po zvážení dostupných alternativ považuji UUID s možností doplnění do 
Alephu "ex post" jako nejméně náchylné k chybám. 

(podle záznamů z Aleph NK se handle objevuje v MARC21 - 856 pod indikátorem 
41, předpokládám, že do stejného pole může být vepsán libovolný 
použitý identifikátor obdobného určení)




```

Original issue reported on code.google.com by `miroslav...@gmail.com` on 19 Nov 2012 at 11:45

**Comment by PavlinaKocisova** [comment]
K tomu bych dodala, že čČNB se může generovat pro různé úrovně, takže pokud máte čČNB pro titul, použijte ho pro titul, pokud pro svazek, použijte to. Číslo České národní bibliografie se vždy dá použít v úrovni, pro které jej máte.

**Comment by svetlym** [comment]
Dobrý den,

kdybych měl za úkol udělat obecnou analýzu digitalizace a návrh architektury softwarového řešení, tak bych se držel jednoduchého pravidla, že primárním identifikátorem libovolného digitálního objektu je UUID - k tomu je totiž přesně určené. Stejně tak libovolné vazby nebo vztahy mezi digitálními objekty by byly "adresovány" pomocí UUID. Ostatní identifikátory bych použil pouze pro vazby nebo vztahy k nedigitálním objektům (například pro identifikaci fyzického výtisku, z nějž byl digitální dokument vytvořen).

Obdobně bych použil UUID k pojmenování všech souborů představujích nebo popisujících digitální objekty. Důvod je ten, že některé koncové formáty, například ocr (txt) nebo jpg, neumožňují zapsat žádná dodatečná metadata, případně není zaručeno, že budou tato metadata zachována při editaci. To znamená, že jediné místo, kam lze třeba u jpegu nebo obecně u libovolného souboru spolehlivě zapsat primární identifáktor (tedy UUID), je právě jméno souboru. Z praktických důvodů bych povolil přípony, tj. jpg soubor by se mohl jmenovat "UUID.jpg".

Použití UUID pro jména souborů má ještě dva dobré důvody:
1) Zajišťuje, že se jmény souborů nenastanou žádné problémy (protože uuid nemůže obsahovat diakritiku, ani jiné potenciálně zlobivé znaky a mají pevně stanovený počet znaků, takže nemůže vzniknout ani příliš dlouhý název souboru).
2) Soubor je jednoznačně identifikován sám o sobě, nikoliv pouze odkazem z jiného souboru. Pokud mám například někde soubor "obalka_001.jpg", tak z toho sice jde odhadnout, co to asi obsahuje, ale velmi snadno může v nějakém jiném balíku existovat jiný soubor se stejným názvem. Použití UUID tomuto problému předejde.

**Comment by vjirousek** [comment]
Jelikož je vlákno staršího data, raději připomínám, že od verzí DMF 1.1 pro monografie (z 6.11.2013) a DMF 1.5 pro periodika (z 20.5.2014) jsou pro pojmenování názvů souborů v rámci balíčků přípustné pouze URN:NBN nebo UUID. V rámci NDK digitalizace využíváme UUID, zdá se být k tomuto účelu skutečně o něco praktičtější.
