### ISSUE TITLE
Jak vyplňovat technická metadata u born digital dokumentů

### ISSUE THREAD

**Issue by black23** [NLCR/Standard_NDK#50]
Existují nějaká doporučení, jak vyplňovat technická metadata v případě, že se dokumenty neskenuje, ale vzniká například z podkladů pro tisk. Tedy v nějakém DTP aplikaci typu Adobe InDesign případně konverzí z PDF do TIF nebo JPEG(2000)?

**Comment by godnat** [comment]
V ideálním případě by se do metadat mělo zaznamenat vše, co předcházelo aktuální podobě elektronického dokumentu. Asi nejlepší je zapsat vše do metadat PREMIS a to do částí agent a event (přes identifikátory se spojí s konkrétním objektem), lze pak poměrně dobře z metadat vyčíst, jak události za sebou probíhaly a jaké aplikace se na nich podílely.  
V případě zmíněné konverze z PDF do TIFF, by v metadatech existovaly dva premis:object- jeden pro PDF, druhý pro TIFF- oba by zde byly popsány a přes identifikátory by se spojily z událostmi a agenty (podobně jako ve vzorovém balíčku je spojen TIFF s JP2).
