### ISSUE TITLE
povinnost atributu "type" u elementu namePart 

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#51]
Bylo by možné povinnost tohoto atributu změnit na MA? U uvedených hodnot tohoto atributu je u každé hodnoty zvlášť ještě povinnost. A navíc když bude například korporativní jméno, tak k němu nelze vybrat žádnou hodnotu atributu partName (date, family, given, termsOfAdress), ale přitom je ten atribut type povinný. 
![namepart](https://user-images.githubusercontent.com/21309201/38658588-17aeea88-3e26-11e8-9ad4-7f83f4327bce.jpg)

**Comment by krizovj** [comment]
Je to standardu pro svazek monografie a kartografické dokumenty, nikde jinde, kde je element name tato povinnost u atributu type není.

**Comment by PavlinaKocisova** [comment]
Díky za připomínku, v příští setinkové úpravě se podíváme, zda to jde sjednotit.

**Comment by PavlinaKocisova** [comment]
do příští verze dáme do příslušného pole vysvětlující poznámku.

**Comment by volodymyrdn** [comment]
Dobrý den, 
neměl by v tom případě element namePart být MA místo M?

**Comment by MirkaBenackova** [comment]
Dobrý deň, áno, so zmenou povinnosti celého elementu tak, aby to nekolidovalo s povinosťami jednotlivých hodnôt (family, given, date, termsOfAddress) pri úprave počítame.

**Comment by PavlinaKocisova** [comment]
Povinnost elementu bude u verze 1.4 DMF pro monografie změněna z M na MA.
