### ISSUE TITLE
šablona - neodmazání interpunkce u RDA záznamů, pole 264

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#54]
U RDA záznamů se při převodu z pole 264 (narozdíl od 260 u AACRkových) automaticky neodmaže interpunkce z place/placeTerm, publisher.

**Comment by luckajirku** [comment]
Můžu se zeptat, zda se tento problém řeší (nebo už vyřešil)? Má label bug, a přesto tu visí od dubna. Díky.

**Comment by FilipPavcik** [comment]
Dobrý deň, 

overoval som problém so súčasnou transformačnou šablonou na niekoľkých RDA záznamoch a problém s neodmazáváním interpunkcie by už mal byť vyriešený.
