### ISSUE TITLE
Dotaz více dílů v jednom svazku

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#55]
Omlouvám se, jestli už se to někde řešilo, myslím, že určitě ano, ale nějak to nemůžu najít. Jak je to s vícedílnými monografiemi, kdy například 1. svazek= 1. díl, 2. svazek= 2. díl, ale pak 3. svazek= 3. a 4 díl. 
Měl by být záznam pro každý díl monografie nebo pro každý svazek?

**Comment by MirkaBenackova** [comment]
Dobrý den, 
DMF stanovuje, že základní intelektuální entitou pro monografie je jeden svazek.  Proto ve Vámi jmenovaném případě by vznikli tři záznamy: jeden pro 1. díl, druhý pro 2. díl a třetí pro 3. a 4. díl. Úroveň TITLE bude ve všech záznamech obsahovat informace o vícedílné monografické publikaci jakožto celku a konkrétní svazek bude popsán až na úrovni VOLUME.

**Comment by krizovj** [comment]
Díky za vysvětlení

**Comment by PavlinaKocisova** [comment]
V tom třetím svazku je 3. a 4. díl vydaný souborně (tj. na titulním listu jsou vypsané oba díly), nebo je to k sobě jenom přivázané? Pokud by k sobě byly jenom přivázané, měly by se každý popsat zvlášť.

**Comment by Drahotussky** [comment]
Všimnul jsem si uzavření Issues a zrovna tento problém ted řešíme.
Pokud mají 1. a 2. díl svou titulní stránku a jsou svázány v jednom svazku, kdy na deskách je vyraženo, že svazek obsahuje dva díly, tak by měly být oba díly popsány jen v rámci jednoho svazku. je to tak?
Dekuji

**Comment by PavlinaKocisova** [comment]
Dobrý den,
pokud se jedná o dva díly, které jsou společně svázané v jednom svazku, a zároveň každý díl má ještě svoji samostatnou titulní stránku, nejspíš bychom je doporučovali popsat každý zvlášť. Pokud je titulní strana jedna pro oba svazky, viděli bychom to spíš na popsání dohromady ve stylu díl 1-2.

**Comment by Drahotussky** [comment]
Já se na tento problém ptal pan Lehra a odpověděl mi,že by popsal oba díly
v jednom svazku.
Nepsal jsem mu ale, že oba díly mají svou titulní stranu.

Děkuji

S pozdravem

Aleš Drahotusdky

Dne út 20. 9. 2022 15:45 uživatel PavlinaKocisova ***@***.***>
napsal:

**Comment by luckajirku** [comment]
Z popisu není jasné, jestli ty dva díly byly už vydány v jednom svazku jako 1.-2. díl, nebo dodatečně svázány. Jsou desky původní?
Z naší praxe - pokud je svazek vydaný jako 1.-2. díl a má jednu titulku, tak popisujeme dohromady. Pokud má každý díl svou titulku, popisujeme každý zvlášť.

**Comment by Drahotussky** [comment]
Ano, desky jsou puvodni. Na hřbetu je uvedeno I-II.
Pokud by se to popisovalo zvlast, u ktereho svazku by se popisovaly desky?

**Comment by luckajirku** [comment]
Ono to ještě někdy je tak, že díly (nebo třeba v případě sešitových vydání) jsou vydány postupně (mají ty vaše stejný rok atd.?) a pak k nim dodavatel vydal samostatně ještě desky.
Máte asi dvě možnosti:
1. popsat dohromady jako 1.-2. díl a pak jednotlivé díly v tom popsat jako kapitoly (není to úplně čisté, ale z pohledu uživatele celkem rozumné)
2. popsat každý díl zvlášť - a tam mi přijde nejpraktičtější přidat ty desky k oběma dílům. Zase to není úplně čisté - ale z pohledu uživatele přehledné...

**Comment by Drahotussky** [comment]
Roky vydani jsou stejne. Uprava desek je stejna i pro dalsi autorovy knihy.

**Comment by vjirousek** [comment]
U popsaného příkladu bych se přikláněl k popsání obou dílů v jednom svazku (desky naznačují že díly takto společně vyšly, není důvod to nerespektovat). Do dělení na kapitoly bych se osobně nepouštěl.

**Comment by Drahotussky** [comment]
Ještě bych doplnil, že 1. a 2. díl nemají stránku s tiráží. ta je až u 3. dílu.
