### ISSUE TITLE
Elementy Name a Subject - odlišnost povinností a (ne)přítomnosti elementů a atributů

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#57]
Name
V rámci elementu name se mění povinnosti jeho jednotlivých částí a některé v některých případech chybí. Chápu samozřejmě, že se mění povinnost celého elementu, ale moc nerozumím, proč se mění třeba povinnosti atributů "type" nebo proč element <affiliation> někde je a někde není, stejně jako třeba atribut "usage". V některých případech také povinnost není vůbec uvedena. 
Bylo by možné to třeba sjednotit, případně uvést, proč je to třeba u svazku monografie jinak než u čísla periodika? Ono nám to zatím v ničem nějak zásadně nevadilo (vím, že pokud je element v MODSu, tak ho lze stejně uvést, i když není ve standardu), ale je to trochu matoucí.

![name](https://user-images.githubusercontent.com/21309201/39918671-82cbe058-5511-11e8-9ab1-54f095683a99.jpg)

Subject
V elementu <subject> je samozřejmě jasné, že některé elementy jsou použitelné jen pro geografické dokumenty a mapy (<cartographics>, <coordinates>, <scale>), spíš jsem si všimla, že různé atributy "authority" někde jsou a někde zase chybí. Podobně u <name> je element <nameIdentifier> pouze u čísla periodika, nikde jinde. 
Chápu, že zcela sjednotit to nejde, spíš by mě zajímalo, jestli to má nějaký důvod, třeba když je v elementu <subject> element <name>. Tak ten další element <namePart> má někde povinnost M a někde R. 
 
![subject](https://user-images.githubusercontent.com/21309201/39918923-53b2efea-5512-11e8-8445-4fa1f38adb8b.jpg)

**Comment by JezkovaV** [comment]
V nadcházejících verzích textových DMF byla u elementů `<name>` a `<subject>` provedena revize dceřiných elementů, atributů a povinností. Soupis jednotlivých změn bude obsažen v příslušných změnových listech k aktualizovaným DMF, v následujících přehledových tabulkách jsou změny vyznačeny žlutě:

**Přehled změn v elementu `<name>`**
![image](https://github.com/user-attachments/assets/709e6b0d-649a-4ea9-85e6-1df96808a381)

**Přehled změn v elementu `<subject>`** 
![image](https://github.com/user-attachments/assets/9ad972cf-2c82-4f7f-8a63-fc284b01bd2f)

**Comment by JezkovaV** [comment]
Zapracováno do DMF periodik (verze 2.1) a DMF monografií (verze 2.2)
