### ISSUE TITLE
Nejednoznačnost standardu ohledně zdroje pro OCR

### ISSUE THREAD

**Issue by godnat** [NLCR/Standard_NDK#58]
DMF 1.7.1  pro periodika (platí i pro 1.3.1 a starší DMF) na s. 10 se uvádí, že OCR (tj. ALTO XML) bude vznikat z uživatelské kopie (tj, ztrátově komprimovaný JP2), důvodem jsou lepší výsledky OCR z obrazů komprimovaných ztrátově. 
Na s. 63 téhož DMF u elementu relationshipType je ale jako příklad uváděný vztah mezi dokumentem ALTO a TIFFem ze kterého vzniká-tj. předpokládá se vazba na původní sken. 

A Komplexní validátor 1.7.1 nově očekává vazbu na archivní bezeztrátový JP2 (původně byla na primární sken viz: https://github.com/NLCR/komplexni-validator/issues/56). 

Do metadat nelze aktuálně zaznamenat vazbu OCR na uživatelskou kopii a kdyby se dělalo OCR z původního skenu nemusely by hodnoty v ALTO odpovídat archivovaným obrazům, proto je aktuálně preferovaná vazba ALTO na archivní JP2. 

Proto je zřejmě třeba revize doporučení a metadat v DMF pro textové i zvukové dokumenty. 
Je otevřeno k diskuzi.

**Comment by vjirousek** [comment]
Doporučení pro vytváření OCR z uživatelské kopie bude v nových verzích DMF postupně odstraňováno. V praxi se OCR vytváří skutečně z nekomprimovaných obrazových souborů a úváděný důvod (méně šumu u ztrátově komprimovaných souborů) se již nejeví jako relevantní.

**Comment by vjirousek** [comment]
Doporučení na vytváření OCR z uživatelských kopií obrazových souborů bylo odstraněno z:

- DMF pro monografie ve verzi 2.0 z 10. 10. 2022
- DMF pro periodika ve verzi 1.9 z 10. 10. 2022
- DMF pro gramofonové desky ve verzi 0.5 z 10. 10. 2022
- DMF pro fonografické válečky ve verzi 0.3 z 10. 10. 2022

Vztah mezi objekty v PREMIS je možné popisovat dle skutečnosti mezi objektem pro ALTO XML a objektem, který nejblíže popisuje soubor, ze kterého bylo OCR reálně vytvořeno (MC i ALTO XML mají zpravidla stejného rodiče v podobě souboru TIFF).
