### ISSUE TITLE
info.xml - element mainmets v případě SIP balíčku

### ISSUE THREAD

**Issue by MartinRumanek** [NLCR/Standard_NDK#60]
Viz např. specifikace http://www.ndk.cz/standardy-digitalizace/E_born_MONO_NDK_22.pdf

SIP balíček obsahuje soubor info.xml, který má povinný element mainmets (je to vynucené i XML schématem). Nicméně SIP balíček obsahuje pouze metadata ve formátu MODS. 

Čím se má tento element plnit? Vydá se nová verze info.xsd, kde bude tento element nepovinný?

**Comment by PavlinaKocisova** [comment]
Dobrý den, nejsem si jistá, zda jsme na oddělení přesně pochopily Váš dotaz, každopádně tento element odkazuje na hlavní mets, obsažený v balíčku. V tomto hlavním metsu jsou pak data v MODS a DC uzavřena v kontejneru z METS. Takže plní se vlastně název hlavního metsu včetně přípony, např.: "mets_nk-00027x_0001".

**Comment by MartinRumanek** [comment]
Kapitola `2.2.2 složka [metadata] pro SIP balíček` z dokumentu http://www.ndk.cz/standardy-digitalizace/E_born_MONO_NDK_22.pdf

```
Složka s popisnými metadaty ve formátu XML. XML soubor obsahuje metadata ve standardu MODS. 
Pro každou úroveň metadat se vytvoří nový soubor (např. mods_title.xml, mods_volume.xml atd.)
```

Pochopil jsem to tak, že SIP balíček kontejner METS neobsahuje. Mýlím se?

**Comment by PavlinaKocisova** [comment]
Máte pravdu, v této části je DMF nekonzistentní. V úvahu je třeba brát to, co je v tabulce pro AIP balíček. V příští verzi DMF to opravíme. Děkujeme za upozornění.

**Comment by MartinRumanek** [comment]
> V úvahu je třeba brát to, co je v tabulce pro AIP balíček.
Asi si nerozumíme, já mám implementovat SIP balíček. Tabulka pro AIP je správná, ale nepomůže mi to. 

Jakým způsobem to opravíte? Bude mít SIP balíček jednodušší info.xml?

Další problematický element je checksum - SIP balíček soubor md5 neobsahuje.

**Comment by PavlinaKocisova** [comment]
To, co je popsáno pro AIP, platí pro organizace mimo NK jako SIP. Bohužel je tato část v DMF chybná, a budeme ji muset v rámci revize na podzim opravit. To znamená, že md5 ve Vašem SIP bude, jelikož je popsána jako obsah AIP.

**Comment by MirkaBenackova** [comment]
V novej aktualizácii DMF pre e-monografie a e-periodiká, verzia 2.2.1 bolo odstránené mätúce používanie SIP a AIP balíčku v rámci DMF; a taktiež súbor md5 je už obsiahnutý v SIP balíčku.
