### ISSUE TITLE
Kapitola a článek - rozsah stran

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#61]
Do elementu <part><extent><start><end> u kapitol se teď píše první a poslední stránka kapitoly. Ale aby Kramerius pochopil, na kterých stránkách ta kapitola je, tak se tam píše index první a poslední strany. Bude něčemu vadit, když se bude element <extent> opakovat? Jednou by to bylo číslo první a poslední stránky a podruhé index první a poslední stránky třeba s atributem "type=pageIndex". 
Šlo by to? 
Hodilo by se, aby tam mohly být obě možnosti, číslo stránky v reprezentaci hlavně kvůli uživatelům a ten index kvůli Krameriovi. Stejná možnost by měla být i pro elektronické dokumenty.

**Comment by vjirousek** [comment]
Vazby mezi vnitřními součástmi a stránkami se nyní řeší v <mets:structMap> a <mets:structLink>, odtamtud je Kramerius nechápe?

**Comment by krizovj** [comment]
No, to nevím, jen jsem si všimla, že se tam píše index a ne číslo stránky. Třeba tady:
http://kramerius4.mlp.cz/search/handle/uuid:c7ab4f0a-2152-4d08-8b82-342072d4054b
nebo taky tady:
http://kramerius.svkhk.cz/search/handle/uuid:5f661ed4-da22-476b-97c1-d5f37ea286f5

**Comment by vjirousek** [comment]
To je spíš asi věcí produkčního nástroje, předpokládám že jak ukázka ze SVKHK tak z MLP byla vytvořena v ProArcu. Nic to neříká o tom že tento způsob zápisu je požadován. Viz např. http://kramerius4.nkp.cz/search/handle/uuid:c939d6e0-ec51-11dd-b763-000d606f5dc6 - nejedná se o ukázku jak metadata vypadat mají, pouze ukázku, že ani takto zapsaný rozsah stran Krameriovi nebrání v korektním zobrazení kapitoly.

**Comment by luckajirku** [comment]
Požadován nevím, ale ProArc to má podle NDK standardu (part / extent - start, end).  Pravda je, že formulace ve standardu je nejednoznačná (zda použít číslo strany nebo index strany): "první stránka, na které vnitřní část začíná"/"poslední stránka, na které vnitřní část končí".

**Comment by krizovj** [comment]
Já jsem právě zkoušela v proArcu zapsat tam čísla stran v reprezentaci a v tom případě to nedovolilo export. Až když jsem to přepsala na index stran tak to teprve šlo vyexportovat. 
Ale myslím, že v tom elementu part / extent -start, end by určitě mělo být číslo strany v reprezentaci, ptž to se pak zobrazí v Krameriovi a uživatel z toho bude zmatený, proč je tam jiné číslo než na tom skenu.

**Comment by luckajirku** [comment]
Tak ale podle čeho on by poznal, kde má kapitola začínat a končit? Dát tam index je jediná možnost, nevím, jak to dělat teď jiným způsobem. Btw otevřete si ty tituly v digitalniknihovna.cz. Mně to tam přijde ok...

**Comment by vjirousek** [comment]
Požadavek ze strany standardu nejednoznačný je, taky si myslím že umožňuje oba výklady. Pokud proArc neumožní export pak se zřejmě přihlédlo k jednomu z výkladů, to je ale spíš věcí proArcu než standardu (ten by měl být pravda jednoznačnější). V rámci struktury METS je příslušnost stránek k vnitřním součástem definována v části <mets:structLink>.

**Comment by krizovj** [comment]
V digitalniknihovna.cz je to zobrazené fakt dobře, fakt se mi to líbí. Tam třeba nejsou metadata ke kapitolám uvedena, takže tam nejsou vidět ty indexy stránek, to je pravda.
No, když se ty záznamy kapitol zařadí mezi ty záznamy stran, kdy když třeba kapitola začíná na straně 2, tak se dá záznam kapitoly před stranu 2, tak z toho pořadí by měl ProArc odvodit, které stránky patří do které kapitoly a vyrobit z toho tu část mets:structLink, jak je uvedeno výše. 
![kapitoly](https://user-images.githubusercontent.com/21309201/41465208-6ecef8e0-709d-11e8-9952-126e081b3a08.jpg)

Nebo by se to mohlo doplnit jinam, ale přijde mi logičtější, že v metadatech, která vidí uživatel, by mělo být skutečné číslo stránky a ne index.

**Comment by krizovj** [comment]
Jaké číslo je tím tedy v tom standardu myšleno? Index nebo číslo strany v reprezentaci? Není to jednoznačně napsáno, ale jaký byl záměr?

**Comment by vjirousek** [comment]
Je to už dost velká myšlenková archeologie, ale téměř jistě bylo původně myšleno skutečné číslo stránky. Vzhledem k tomu, že ke skutečné provazbě mezi stránkami a vnitřními součástmi pole nebylo zamýšleno, nebyl důvodu zde požadovat index stran.

**Comment by krizovj** [comment]
Bylo by možné přidat do standardu možnost, aby se element "part" opakoval? S možností přidat buď atribut pagenNumber nebo pageIndex? Aby bylo možné přidat jak rozsah čísel stran pro uživatele a zároveň rozsah indexů pro Krameria? 

Jinak už jsme zjistili, podle čeho rovná stránky do článků Kramerius. Je mu jedno, jestli je to index nebo číslo. Vezme to, co je uvedeno v záznamu jako první. Takže když je v záznamu článku uveden rozsah čísel stran jako první a potom až rozsah indexů stran, tak Kramerius složí články špatně, ptž si myslí, že je to index.

**Comment by zabak** [comment]
@krizovj vznikne z toho bug na Krameria?

**Comment by krizovj** [comment]
@zabak ano, chystám se na to

Stejně to mimochodem funguje u kapitol v monografiích.

**Comment by PavlinaKocisova** [comment]
Dobrý den, děkuji za tento poznatek! Možnost opakování elementu part prověříme.

**Comment by PavlinaKocisova** [comment]
Opakování elementu <part> je možné, proto jsme příslušnou úpravu provedly jak na úrovni vnitřní části v periodicích verze 1.8, tak na stejné úrovni v monografiích verze 1.4
