### ISSUE TITLE
Eborn monografie - kapitola, namePart@type

### ISSUE THREAD

**Issue by MartinRumanek** [NLCR/Standard_NDK#63]
Atribut type, který je nyní pod elementem role ve skutečnosti patří pod opakovatelný namePart. Je to tak?

![namepart](https://user-images.githubusercontent.com/1872729/42203273-8ade0620-7e9e-11e8-8ceb-79d7e7f22354.PNG)
(https://www.ndk.cz/standardy-digitalizace/E_born_MONO_NDK_22.pdf#page=27)

**Comment by PavlinaKocisova** [comment]
Ano, patří pod namePart. Jedná se o překlep.

**Comment by MartinRumanek** [comment]
Ze specifikace mi není jasné, co mám vyplňovat do atributu genre@type.
![genretype](https://user-images.githubusercontent.com/1872729/42421490-ab675d24-82d6-11e8-877e-25304ccd5efb.PNG)

Patří electronic_article do tohoto atributu? Neměla by to být hodnota přímo genre, tak jak je to v obyčejném NDK article?:
![periodikagenretype](https://user-images.githubusercontent.com/1872729/42421491-ac7e39bc-82d6-11e8-9c6d-3eb44490c067.PNG)

**Comment by krizovj** [comment]
No, já jsem to z toho pochopila tak, že je to vlastně v těch elektronických publikacích opačně než v těch klasických. 

Tištěné:
mods:genre type="editorsNote">article</mods:genre

Elektronické:
mods:genre type="electronic_article">editorsNote</mods:genre

**Comment by MartinRumanek** [comment]
Jj, chápu to stejně. Ale než to předělám (vycházím z tištěných formulářů), tak jsem se chtěl ubezpečit, že je to záměr a ne chyba. Mohl by mi to potvrdit/vyvrátit někdo z @NLCR?

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za upozornenia. V oboch prípadoch sa jedná o chyby.

**Comment by MirkaBenackova** [comment]
Tieto chyby boli odstránené v aktualizácii DMF pre e-monografie a e-periodiká, verzia 2.2.1.
