### ISSUE TITLE
Vnitřní část periodického dokumentu (obrázek, článek, mapa, apod.) - relatedItem

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#64]
Bylo by možné do MODSu vnitřní části periodického dokumentu přidat element relatedItem? Ve standardu pro elektronické dokumenty je.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za podnet! Pripomienku sme si zapísali na zoznam budúcich úprav a pri najbližšej aktualizácii štandardu bude doňho zapracovaná.

**Comment by krizovj** [comment]
Děkuji

**Comment by PavlinaKocisova** [comment]
Tato úprava bude implementována v DMF periodika 1.8.
