### ISSUE TITLE
hodnota <mods:typeOfResource> na úrovni PAGE

### ISSUE THREAD

**Issue by MirkaBenackova** [NLCR/Standard_NDK#66]
V aktuálnom DMF 1.3.1 a 1.7.1 predpísaná hodnota poľa <mods:typeOfResource> na úrovni PAGE „image“ nezodpovedá schéme MODS 3.6, kde sa naopak povoľuje hodnota „still image“.  
Úprava nezrovnalosti je v štádiu riešenia.

**Comment by MirkaBenackova** [comment]
riešenie: Pri príjme dát budú akceptované obe hodnoty ("image" aj "still image"), pričom hodnotou, ktorá je preferovaná v rámci NDK je "still image".

**Comment by godnat** [comment]
Budou také opraveny DMF 1.3.1 a 1.7.1, které budou v elementu mods:typeOfResource na úrovni PAGE předepisovat i hodnotu "still image", hodnota "image" bude pro tyto specifikace i nadále povolená, preferovaná je ovšem hodnota "still image". Tyto specifikace si ponechají označení 1.3.1 (pro monografie) a 1.7.1 (pro periodika). (Kompletní nahrazení hodnoty "image" hodnotou "still image" je provedeno v DMF 1.3.2 pro monografie z 8.10.2018 a bude provedeno v dalším vydání DMF pro periodika)

**Comment by vjirousek** [comment]
Vyřešeno v rámci opravných verzí DMF pro monografie 1.3.1 a DMF pro periodika 1.7.1 z října 2018.
