### ISSUE TITLE
Načítání pole 264 v součinnosti s polem 008 - RDA záznamy

### ISSUE THREAD

**Issue by PavlinaKocisova** [NLCR/Standard_NDK#67]
Zdravím, jeden z producentů má problém s převáděním pole 008 přes transformační šablonu, v případě, že je v záznamu dostupný údaj z pole 264. Konkrétně se jedná o problém s načítáním údajů "start" a "end" v datu a rozsahu let.  

Zatím jsme podobný problém nezaznamenali,  setkal se s tím někdo z vás? Díky.

**Comment by luckajirku** [comment]
My jsme se tady s problémem nesetkali, převádí se nám to jak má. Bylo by dobré dát sem konkrétní příklady nebo odkazy na použité katalogizační záznamy, které dělají problém.

**Comment by PavlinaKocisova** [comment]
Děkuji za rychlou odpověď! Katal. záznamy zatím nemám k dispozici, až je získám, samozřejmě je přidám.
