### ISSUE TITLE
Příloha ročníku - dotaz

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#69]
Nevím, jestli už se někde řešilo, ale v issues jsem to nenašla. Jak je to v případě, že mám přílohu, ale jde o přílohu ročníku a NE přílohu čísla? V balíčku jsou tři povinné úrovně: Title, Volume a Issue. Ale když jde o přílohu ročníku, tak je vlastně na úrovni čísla, takže by v balíčku chyběla úroveň Issue a místo ní by byla úroveň Supplement. Jde to? 
Díky

**Comment by luckajirku** [comment]
My to děláme běžně, takže doufám, že to jde:-))).

**Comment by vjirousek** [comment]
Digitalizace NDK je takto od počátku rovněž nastavena - při vytvoření přílohy ročníku je tato řazena přímo pod ročník.

**Comment by godnat** [comment]
Dobrý den,

ano jde to, v případě, že se jedná o přílohu ročníku je možné aby balíček obsahoval úroveň Supplement namísto úrovně Issue. Taková data budou do úložiště NK přijata, nejedná se o chybu.
Pro nás (NK) to znamená úpravu DMF, které nyní tento postup nepovolují, přestože se jedná o schválenou praxi.

**Comment by PavlinaKocisova** [comment]
Tato praxe nakládání s ročníkovými přílohami bude formálně zapsána do DMF periodika 1.8.

**Comment by isenkyr** [comment]
Dobrý den,
my v takových připadech dáváme přílohu k prvnímu nebo poslednímu výtisku, záleží kde je příloha vyvázána anebo podle požadavku zákazníka. Takto vzniklou přílohu označíme v genre[@type='volume_supplement']. Chci se zeptat zda v nových standardech bude tato možnost zpracování příloh k ročníku zachována? Ptám se, protože změna by nám způsobila problémy v našem systému. Dále se chci zeptat na nový způsob zápisu přílohy periodika.. Pokud v psp balíku bude pouze záznam pro přílohu, tak urnnbn bude přidělováno příloze?

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
áno, možnosť označenia prílohy spôsobom, aký zmieňujete, zostane v nadchádzajúcej DMF zachovaný. Čo sa týka prideľovania urn:nbnb, tak uvažujete správne; pokiaľ je v balíku popisovaná samostatná príloha ročníku, urn:nbn sa pridelí jej.
