### ISSUE TITLE
Elektronické publikace - physicalLocation

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#70]
Bylo by možné do příští verze standardů pro elektronické monografie a periodika přidat element "location-physicalLocation" se siglou a případně signaturou (nepovinně)? 
Sice jde o elektronické publikace, ale například v ČDK by mělo být poznat, odkud ten dokument je, ptž když bude nepřístupný, tak by měl uživatel mít možnost vědět, kde to najde. 
Signatura by se vyplnila jen v případě, že ta elektronická publikace má také tištěnou verzi.
Viz. https://github.com/proarc/proarc/issues/851

**Comment by MirkaBenackova** [comment]
Dobrý deň, myslíme si, že so zahrnutím zmieneného elementu by v ďalšej desatinkovej úprave nemal byť problém, zapísali sme to na zoznam úprav.  
V drafte štandardu pre e-články to bude zahrnuté tiež.

**Comment by MirkaBenackova** [comment]
Elementy physcialLocation a shelfLocator boli pridané do DMF pre elektronické monografie verzie 2.3 a DMF pre elektronické periodiká verzie 2.3 (obe vydané 17. 12. 2019) s povinnosťou RA.
