### ISSUE TITLE
Termíny v name/namepart/type

### ISSUE THREAD

**Issue by luckajirku** [NLCR/Standard_NDK#71]
Snažíme se rozdělit správně jména v name/namepart/type a narážím na určitou nelogičnost v anglických termínech. Byl nějaký důvod, proč nepřevzít termíny z MARCu a místo toho použít v namepart: "family" pro příjmení a "given" pro rodné/křestní jméno? Takhle je to trochu matoucí, bylo by přehlednější nechat Family jen u name ve významu jména rodu, a v namepart používat u ind1 0 Forname, ind1 1 Surname podle MARCu.  
100a/700a
name type ind1 0 a 1 = personal
name type ind1 3 = family
MARC21:
ind1 0 = Forname
ind1 1 = Surname
ind1 3 = Family name

**Comment by MirkaBenackova** [comment]
Dobrý deň, s termínami family/given/date/termsOfAddress v atribúte type u subelementu namePart pracuje štandard ako pre monografie, tak aj pre periodiká už od svojich najranejších verzii. Je to dané tým, že tieto termíny v príslušnom subelemente predpisuje štandard MODS a jeho xsd schéma vydávané Library of Congress a teda ak by sa použili hodnoty ako navrhujete, výsledný záznam by nebol valídny voči štandardu MODS. Čo ale byť musí – my si síce môžeme vyberať, ktoré elementy z MODS použijeme, ale iba v rámci predpísaných hodnôt a na predpísaných miestach/zanoreniach.

**Comment by luckajirku** [comment]
Děkuju za rychlou reakci, moje chyba, toho jsem si nevšimla. Teď se dívám na stránky LoC, že tam přímo upozorňují "Note that "family" and "given" are not used in MARC 21."
Ono je na první pohled matoucí, jak jednou je family pro jméno rodu, podruhé pro příjmení - tak by možná nebylo špatné, kdyby i u toho name bylo ve standardu rozepsáno, odkud se údaje berou, resp. za jakých podmínek (jaké pole/podpole, indikátor). U některých elementů tyhle věci rozepsané jsou dopodrobna (např. origininfo/eventtype), tady je jen "– údaje o odpovědnosti nutno přebírat z polí 1XX a 7XX MARCu21".

**Comment by MirkaBenackova** [comment]
Ďakujeme za podnet, možné pridanie dovysvetľujúcej poznámky pri najbližšej úprave zvážime.

**Comment by luckajirku** [comment]
Bylo by to fajn, vzhledem k tomu, že je tam dost možností a není to prosté překlopení jednoho podpole do elementu, ale je třeba brát v potaz indikátory + podpole a dál rozdělit (pokud to lze) údaje z podpole do dvou subelementů, přičemž v šabloně LoC to vytváření namepart/family a given dělením údajů z jednoho MARCového podpole zřejmě není, takže se není o co opřít...

**Comment by PavlinaKocisova** [comment]
Doplněno ve verzích DMF periodika 1.9 a monografie 2.0.
