### ISSUE TITLE
České názvy typů stran

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#72]
Dobry den,
v Pravidlech popisu pro periodika je u typu strany cover uveden jako cesky ekvivalent Obalka, u Jacket zase jako Prebal.
V Pravidlech pro monografie je u typu strany cover jako cesky ekvivalent Desky, u Jacket jako Obalka.
Prijde mi to matouci v souvislosti se zobrazovanim v Krameriovi. Nám se Cover zobrazuje jako desky a jacket jako obalka

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za upozornenie, preklady sú skutočne nekonzistentné, myslím ale, že je to sčasti dané aj typom dokumentu. Každopádne celý problém ohľadom prekladov typov strán  a možné riešenie skonzultujem s kolegami a dám vedieť stanovisko čo najskôr.

**Comment by luckajirku** [comment]
Jen poznámka - k tomu zvláštně používanému popisu Obálka bylo kdysi tohle issue... https://github.com/NLCR/Standard_NDK/issues/36

**Comment by krizovj** [comment]
Dobrý den, 
jak to prosím vypadá s tímhle problémem?

**Comment by MirkaBenackova** [comment]
Dobrý deň, na odstránení problému sa pracuje. Problematické názvy typov strán u periodík budú pravdepodobne zmenené a zjednotené s monografiami, v Krameriovi sa to všetko zobrazuje pod rovnakým termínom. Čakám ale ešte sa schválenie. Zmeny sa premietnu do najnovšej verzie Pravidiel pre popis, v rámci ktorej budú ostránené aj iné nezrovnalosti.

**Comment by Drahotussky** [comment]
Nam se to v Krameriovi prave zobrazuje ruzne. Jacket jako obalka, Cover jako desky. Budeme si to muset predelat.
Ještě do toho vstupuje další nejasnost. V pravidlech popisu monografií je uvedena Obálka (Jacket)  - papírový přebal focený vcelku z přední strany (zadní strana bývá bílá bez
informace
V pravidlech pro popis periodik je ale zase uveden Přebal periodika (Jacket) - - papírový přebal focený vcelku z přední strany (zadní strana bývá bílá bez informace.
Nevím,zda je možné, aby Kramerius zobrazoval Jacket se dvěma českými výrazy.

**Comment by MirkaBenackova** [comment]
Podľa toho, čo sa mi podarilo zistiť, sa v našom Krameriovi (NK) zobrazuje jacket ako Obálka; a cover ako Desky a to ako v prípade monografii, tak periodík. Teda používajú sa hodnoty ako sú uvedené v Pravidlách pre popis monografii. 
V rámci prebiehajúcej aktualizácie pravidiel pre popis budú v Pravidlách pre popis periodík opravené problematické názvy podľa Pravidiel pre popis monografii (tj. bude odstránené chybné obálka=cover a přebal periodika=jacket a po "novom" sa bude označovať jacket ako Obálka a cover ako Desky) a budú k nim pripojené vysvetlivky, aby bolo jasné, čo sa pod daným pojmom myslí. Takže zmena nastane len v pravidlách pre periodiká, nikde inde. 
Takto budú rovnaké hodnoty používané ako v Pravidlách pre popis monografii; periodík, tak aj v Krameriu a nemalo by to už byť zavádzajúce.

**Comment by MirkaBenackova** [comment]
České názvy typov strán boli opravené podľa môjho komentára vyššie, a to v aktualizovanej verzii Pravidiel pre popis periodík zverejnenej 20.12.2019. Zároveň je ku každému typu strany pridaná krátka charakteristika.
