### ISSUE TITLE
Aktualizace pravidel popisu periodik

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/Standard_NDK#73]
Dobry den,
Na strankach NDK je u Pravidel popisu periodik zpristupnena verze 8.2.1, v konferenci  ceska expedice/kramerius je ale odkazovano na vysi verzi Pravidel (https://github.com/ceskaexpedice/kramerius/issues/635)
Lze to opravit?
Rad bych se jeste zeptal na opravu,ktera je uvedena ve vyse uvedenych novych Pravidlech, a sice v bode 4.1, kde se resi cislovani vice rocniku v jednom svazku (v popisu rocniku ma byt uvedeno napr. 50-52).  Znamena to, ze budou vsechny rocniky zpracovany v ramci jednoho rocniku? Nebo zustava v platnosti, ze kazdy rocnik se zpracuje samostatne?

Dekuji

**Comment by MirkaBenackova** [comment]
Čo sa týka Vášej druhej otázky, je to tak, ako píšete. Po novom sa takéto "viaczväzky" spracovávajú v jednom ako rozpätie tých, ktoré sú zviazané spolu. Teda už nespracovávate každý ročník v danom zväzku samostatne.

**Comment by luckajirku** [comment]
Mně to přijde nepřesně napsané. Je rozdíl, zda mám svazek, kde to již vyšlo jako rozsah ročníků (nevycházel každý rok jeden ročník, ale vyšlo (třeba po válce, kdy jednotlivé svazky vyjít nemohly) naráz více ročníků), nebo jestli jednotlivě vydané ročníky dodatečně svážu. V prvním případě by měly být popsané dohromady, v druhém případě každý zvlášť.

**Comment by MirkaBenackova** [comment]
Zmienená problematika bola zahrnutá už do Pravidiel pre popis periodík verzie 8.3.1 a toto zostalo zachované aj v vo verzii 8.4 vydanej 20.12.2019.
