### ISSUE TITLE
Číslování ročníků - dotaz

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#74]
Mám dotaz na číslování ročníků u jednoho periodika, kde jsou čísla zvláštně označená. 
Přehled čísel:

- 1973 / Číslo 1
- 1973 / Číslo 2: Procesy poznání a učení
- 1973 / Číslo 3: Cognitive processes and learning
- 1974 / Číslo 4: K analýze skupinových problémových situací
- Rok neuveden / Číslo 5
- 1975 / Číslo 6: Evolution of learning
- 1975 / Číslo 7
- 1975 / Číslo 8
- 1975 / Číslo 9: Model aktivního sociálního učení
- Rok neuveden / Číslo 10
- Rok neuveden / Číslo 11
- 1976 / Číslo 12
- 1976 / Číslo 13
- 1976 / Číslo 14
- 1977 / Číslo 15: Sborník statí věnovaný k šedesátinám člena korespondenta ČSAV Josefa Linharta
- 1976 / Číslo 16
- 1979 (Bez čísla) Soupis publikační činnosti pracovníků psychologického ústavu ČSAV za rok 1979
- 1980 (Bez čísla) Vývojový princip v psychologii, jeho teoreticko-metodologické základy a jeho aplikace v praxi
- 1981 / Číslo 2
- 1981 / Číslo 3: Soupis publikační činnosti pracovníků Psychologického ústavu ČSAV za rok 1980
- 1981 / Číslo 4
- 1981 / Číslo 5: Soupis publikační činnosti pracovníků Psychologického ústavu ČSAV za rok 1981
- 1982 / Číslo 6: Conception of the Principal Assignment of the State Plan of Basic Research VIII-6-5

Osobně bych to udělala tak, že čísla z let 1973-1979 včetně by představovala první ročník a od roku 1980 do 1982 druhý ročník.

Mohla bych požádat o radu, jak by byl zápis čísel ročníků nesprávnější?

Díky

**Comment by luckajirku** [comment]
"Nejsprávnější" je to po konzultaci s katalogizátory:-). Toho se držíme, všechno musí jít před digi na RK a jak řekne katalogizátor, tak to popíšeme. Tohle by mělo co nejvíc sedět s bib popisem. Jak to máš popsané v jednotkách, tam přeci musí být číslo ročníku.

**Comment by krizovj** [comment]
Zeptám se ještě katalogizátorů, díky :)
Číslo ročníku tam bohužel není, to je právě ten problém. Jsou tam jen čísla a rok...

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
veľmi sa ospravedlňujem, že sa ozývam až teraz. Podľa pravidiel pre popis je možné v prípade, keď nie je uvedené číslo ročníku a ani ho nie je možné dopočítať, zapísať namiesto neho rok vydania. Ale ako už bolo zmienené vyššie, najlepšie by bolo poradiť sa v tomto konrétnom prípade s katalogizátormi.

**Comment by krizovj** [comment]
Děkuji, už jsme to vyřešili. 
Udělali jsme z toho dva ročníky, podle těch čísel. 
V prvním ročníku jsou čísla 1-17 (kdy číslo 17 není na dokumentu uvedeno, takže je dopočítané) a v druhém jsou čísla 1-6 (číslo 1 je opět dopočítané).
