### ISSUE TITLE
Zápis typu vazby v metadatech

### ISSUE THREAD

**Issue by PavlinaKocisova** [NLCR/Standard_NDK#75]
Dobrý den všem,
zapisujete do popisných metadat, zda je dokument v brožované/ tvrdé vazbě? Případně, kam? Aktuálně hledáme možnost zápisu, a zajímala by nás praxe z jiných knihoven. 

Díky za pomoc!

**Comment by vjirousek** [comment]
Měla by to být informace vztahující se ke konkrétnímu exempláři (kde mohlo dojít k převazbě) nebo obecně k vydání? V obou případech se mi to jeví jako informace maximálně do poznámky.

**Comment by PavlinaKocisova** [comment]
Konkrétně k vydání, protože v některých případech se jedná o jediné rozlišení mezi vydáními. Příklad: knihy, podle kterých byl natočen film, obvykle po premiéře vycházejí znovu s filmovou obálkou, a obvykle jsou dvě verze - dražší vázaná a paperback. 

V katalogu je druh vazby většinou uvedený v závorce u ISBN, což mi přijde dost nešťastné.

**Comment by luckajirku** [comment]
Tohle jsme neřešili, hodně toho máme převázáno a hlavně jedeme spíš věci, které půjdou zpřístupnit, než tu novou produkci, v jejíž digitalizaci smysl teď nevidíme.
Ale jen pár poznámek k tomu katalogu. Jde i o to, jak to tam chcete dostávat automaticky, ručně to asi nikdo vypisovat chtít nebude. Číslo z 020 $a překlápíme jednoduše do mods:identifier type="isbn". Ale v 020 $q, kde jsou ty údaje o vazbě, toho může být víc. Navíc se bude lišit znění, ale asi to budete chtít mít jednotně, ne? U aacr záznamů se psalo váz., brož., v rda se to rozepisuje na vázáno, brožováno. (Pak jsou samozřejmě další typy - kroužková vazba, portfolio, skládanka...) Pak jsou tam ty závorky - pokud bude jen jeden výskyt podpole q, budou závorky na začátku i konci, pokud bude víc výskytů (např. je tam uvedeno i číslo svazku), bude závorkou jen končit, takže na to se pak taky nesmí zapomenout v šablonách. Pak jde o to, jestli ve všech těch zdrojových záznamech ten údaj bude překlopený z tuším 020 $c, kam se psal u aacr záznamů, do  020 $q. Mělo by to být, minimálně alephí knihovny to budou mít upravené, ale...

**Comment by luckajirku** [comment]
Ale hlavně nevím, jak pak rozlišit, které údaje z toho podpole q se tam mají stahovat, pokud teda nebudete mít v šabloně natvrdo vyjmenované typy vazeb, které se mají převést, zatímco např. svazek 1, dotisk a další údaje, které se v tom podpoli mohou vyskytnout, to bude ignorovat.

**Comment by PavlinaKocisova** [comment]
Dobrý den, chtěli bychom toto téma znovu otevřít na schůzce Pracovní skupiny pro digitalizované textové dokumenty, abychom zjistili, zda je o danou úpravu zájem, a jestli je ji eventuálně možné zapsat do DMF.

**Comment by ZdenekVasek** [comment]
V návaznosti na schůzku skupiny pro textové dokumenty doplňuji, že pro identifikaci archivu lze využít jejich rejstřík na Archivním portálu https://portal.nacr.cz/aron. Archiv je označen názvem a číselným kódem.

**Comment by vjirousek** [comment]
V návaznosti na projednání na PS skupině pro textové dokumenty issue uzavírám, úprava v tuto chvíli není poptávána. V případě potřeby lze znovuotevřít.
