### ISSUE TITLE
chybná hodnota Copyrighted v DMF Periodika 1.6

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#77]
Minimálně pro [DMF Periodika 1.6 ](https://www.ndk.cz/standardy-digitalizace/DMFperiodika_16.pdf) se na straně 97 uvádí povolená hodnota "Copyrighted", kterou ale obecnější CopyrightMD formát neumožňuje a má tam být "copyrighted". 
Pro Validátor se řešilo zde:
https://github.com/NLCR/komplexni-validator/issues/73

**Comment by PavlinaKocisova** [comment]
Opraveno ve verzi 1.8 pro periodika a 1.4 pro monografie. Děkujeme za upozornění.

**Comment by MirkaBenackova** [comment]
Rovnako opravené v DMF pre elektronické monografie verzie 2.3 a DMF pre elektronické periodiká verzie 2.3 (obe zverejnené 17.12.2019).
