### ISSUE TITLE
DMF - sekce "změny pro záznamy zpracované podle RDA"

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#79]
Např. u DMF Monografie 1.3 na stranách 25 a 26 není zřejmé, jestli pro záznam zpracovaný podle RDA má originInfo obsahovat nepovinný element edition. To barevné kódování červenou barvou taky moc nepomáhá. 
Navrhuji to dělat tak, že pokud něco předefinuji (zde originInfo), tak bude vždy celá sekce nahrazena kompletně (zde požadavky na element originInfo a vše v něm). 
Tady mám opravdu pocit, že se tím myslí, že mám nějak spojit text "před červenou čarou" a po, přičemž nějak je barevně znázorněno, co se změnilo, ale pořád nekonzistentně (třeba eventType červený je (asi protože má změny v popisu obsahu), ale proč potom není červený publisher?

**Comment by fremrovaK** [comment]
V DMF pro periodika 2.0 a v DMF pro monografie 2.1 došlo ke kontrole a revizi rozlišení pokynů pro elementy, jejichž plnění se liší v závislosti na použitých katalogizačních pravidlech. V takovém případě je celý element je zopakován, přičemž jeho první výskyt se vztahuje na pravidla AACR2 a název elementu je psaný černě; druhé v pořadí jsou uvedeny pokyny pro záznam podle RDA a název elementu je psaný červeně.
V případě rozsáhlého top elementu <originInfo> mají pro lepší orientaci navíc všechny řádky s pokyny pro RDA červený levý okraj.
Obě DMF byly také doplněny o vysvětlivky o barevném kódování.
