### ISSUE TITLE
DMF - udávané atributy pro relatedItem nejsou platné pro MODS

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#80]
Např. DMF Monografie 1.3, strana 37:
Element relatedItem může mít v MODS 3.6 atributy otherTypeAuth a otherTypeAuthURI, ne otherTypeAuthority a otherTypeAuthorityURI.

**Comment by rzeh4n** [comment]
na straně 47 stejného dokumentu je zase špatná hodnota _**O**therTyapuAuthURI_, zajímavé je, že tam přibyla i správná _**o**therTypeAuthURI_, tentokrát z neznámého důvodů bez žlutého podbarvení, textového popisu a informace o povinnosti.

**Comment by rzeh4n** [comment]
na straně 56 opět špatně, tentokrát otherTypeAuthority

**Comment by PavlinaKocisova** [comment]
Dobrý den, děkuji za upozornění. V nadcházející verzi 1.4 tyto chyby budou upraveny.
