### ISSUE TITLE
DMF Monografie 1.3 - page extent

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#82]
Strana 72:
1. element extent je odsazen tak, že to vypadá, že je hned pod top-level elementem mods, přičemž to MODS nedovoluje a jediný smysl dává, že patří pod part.
2. obecně to odsazení je podivné, už na straně 71 je top-level element odsazen stejně, jako jeho potomci (titleInfo, identifier, part, extent, ...)
3. není jasné, jestli je extent povinný, nebo ne. Atribut "unit" by měl být na novém řádku, takhle není jasné, jestli povinnost "O" patří k elementu extent, nebo k jeho atributu unit.
4. celá tabulka na straně 72 vypadá "uřezaně" a působí to, že část chybí. Jde to vidět třeba v porovnání s tabulkou na straně 71.

**Comment by PavlinaKocisova** [comment]
Děkujeme za upozornění. Všechny Vámi zmíněné problémy odstraníme v DMF monografie verze 1.4.
