### ISSUE TITLE
DMF - nekonzistence povinnosti a informaci o povoleném počtu výskytů

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#83]
Ve specifikacích PREMIS a MIX je obrovské množství nekonzistencí mezi počtem opakování (0-1, 0-n, 1-n) a informací ze sloupce povinnost.
Např. v DMF Monografie 1.3 na straně 83 úplně nahoře:
byteOrder má povinnost M (mandatory), zároveň opakovatelnost 0-1. Takže je povinný (M), ale zároveň se může vyskytovat 0-krát, tedy není povinný.
Podobně hned pod ním Compression, který se liší pouze v tom, že je opakovatelný (0-**n**). Stále je ale povinný (**M**) a zároveň nepovinný (**0**-n).

**Comment by rzeh4n** [comment]
Problém přetrvává. Přece není řešením to rozhodnout nějak ve Validátoru, ale dále zachovat nejednoznačnost v textu DMF. Např. pro Periodika 1.6 byly tyto sporné věci upraveny na MANDATORY třeba zde:
https://github.com/NLCR/komplexni-validator/commit/cb022bc475bc22655bd60d5b4aac391ca07c4f00#diff-54bfae94b003a2870c5e0d7910335666
Ale když se podívám do textu DMF Periodika 1.7, třeba na stranu 58 a element preservationLevel, tak stále má "0-n" a povinnost "M". Takže podle specifikace/standardu DMF, která má větší slovo, než nástroj, jenž ji interpretuje a formalizuje, je element opakovatelný, **nepovinný** a zároveň **povinný**.

Samozřejmě nelze již měnit jednou vydanou specifikaci/standard, zde DMF Periodika 1.7, je v pořádku, že nejednoznačnosti vyjasňuje oficiální interpretace (třeba i v podobě pravidel Validátoru). Ale v nových verzích DMF by se přece známé problémy opravovat měly.

**Comment by vjirousek** [comment]
@rzeh4n Každá hodnota uvádí něco jiného, nejedná se tedy o nekonzistenci. V nových verzích DMF postupně přidáváme ještě další doplňující vysvětlení, aby to bylo jednoznačné a nedocházelo ke zmatkům.

Počet opakování uvedený ve sloupci "Popis" (0-1, 0-n, 1-n...) se vztahuje k XSD použitého metadatového schématu (např. PREMIS), ve sloupci "Povinnost" je oproti tomu uvedena povinnost v rámci konkrétní DMF. 

Pokud je tedy například opakovatelnost dle PREMIS "0-n" a povinnost v rámci DMF je "M" pak je element povinný a opakovatelný.
