### ISSUE TITLE
DMF Monografie 1.3.2 - povolene hodnoty metadataversion v souboru info neobsahuje 1.3.2

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#85]
Na straně 15. ve specifikaci DMF Monografie 1.3.2 je popis souboru info. A u elementu metadata version je uvedeno:
verze metadatové specifikace, podle které byl balíček zpracován
Povolené hodnoty pro monografie: 1.1; 1.1.1; 1.1.2; 1.1.3; 1.2; 1.3;
1.3.1
Evidentně tam chybí hodnota 1.3.2.
Tady jde mimochodem vidět, jak je koncepčně je špatně, že soubor info je pro každou novou verzi DMF specifikován znova. 
Namísto toho by měl být tento manifest definován a verzován mimo samotné DMF. DMF by se měl odkazovat na konkrétní verzi manifestu info a používat xsd pro tu konkrétní verzi.

**Comment by PavlinaKocisova** [comment]
Děkujeme za upozornění na chybu, v budoucí verzi bude opraveno.

**Comment by MirkaBenackova** [comment]
Opravené v DMF pre monografie verzie 1.4 a DMF pre periodiká verzie 1.8 (obe zverejnené 30.11.2019).
