### ISSUE TITLE
DMF Periodika 1.7 - mods:recordChangeDate/@encoding na urovni titulu

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#86]
DMF Periodika 1.7 na straně 34 je pro element recordCreationDate uveden nepovinný atribut encoding s povolenou hodnotou iso8601. Pro recordChangeDate tento atributu uveden není, ale Validátor jej očekává (stále jako nepovinný) a pokud je nalezen, kontroluje, zda obsahuje hodnotu "iso8601".
Striktně podle specifikace DMF by se tam encoding tedy očekávat neměl, ve dotčeném metadatovém profilu to ale vypadá následovně:
```
<element name="mods:recordChangeDate" mandatory="false">
 <!-- V DMF 1.7 není atribut encoding definován, 
         ale logicky by měl být stejný zápis jako u recordCreationDate.  
         Zde ale atribut definován nepovinný, protože není ve specifikaci DMF -->
   <expectedAttributes>
       <attribute name="encoding" mandatory="false">
              <expectedContent>
                 <value>iso8601</value>
               </expectedContent>
        </attribute>
    </expectedAttributes>
    <expectedContent/>
</element>
```
Takže podle mě se má stát jedna z následujících možností:
1. v profilu pro DMF 1.7 komentář upravím ve smyslu "není striktně podle specifikace DMF" a v příští verzi DMF Periodika bude encoding pro recordChangeDate uveden
2. nechám komentář, jak je a z profilu odstraním očekáváný atribut encoding pro recordChangeDate. 

Předpokládám, že spíše první verze. Tuším, že ta specifikace byla doplněna později, než komentář a i v ukázkových datech se mods:recordChangeDate/@encoding objevuje.

**Comment by PavlinaKocisova** [comment]
Dobrý den, toto issue bude opraveno ve verzi 1.8 pro periodika.

**Comment by MirkaBenackova** [comment]
Opraveno rovnako aj v DMF pre monografie verzie 2.3 (zverejnené 30.11.2019).
