### ISSUE TITLE
DMF Periodika 1.7 - povolené hodnoty pro preservationLevelDateAssigned

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#87]
Souvisí s  https://github.com/NLCR/Standard_NDK/issues/83. 
V metadatovém profilu pro DMF Periodika 1.6 byly doplněny možné hodnoty pro element premis:preservationLevelDateAssigned (regulérním výrazem):
https://github.com/NLCR/komplexni-validator/commit/f7648988a0cdb66557c2562ee9c763f45a96560d#diff-54bfae94b003a2870c5e0d7910335666

DMF Perioidka 1.6 byla vydána v září 2015. Odkazovaný commit je z května 2017. DMF Periodika 1.7 byla vydána v prosinci 2017, navíc údajně upravena (sic!) v lednu 2018. No a v DMF Periodika 1.7 je beze změny stále uvedeno:
> datum, kdy byla přiřazena hodnota úrovně ochrany, zápis v
ISO 8601, na úroveň dne (RRRR-MM- DD)

Takže když to shrnu:
- Rozšíření (povolen i čas) bylo doplněno do metadatového profilu zpětně pro standard, který je dva roky zveřejněn. 
- Nejde o interpretaci standardu, ale o změnu chování Validátoru v rozporu se standardem (Validátor povoluje něco, co standard neumožňuje). 
- V nové verzi DMF o 9 měsíců později ale tato změna stále není! I když to je přesně to místo, kam změna patří a Validátor ji má až tehdy reflektovat.

Podle mě by se neměla takto rozcházet specifikace DMF a to, co kontroluje Validátor.

**Comment by rzeh4n** [comment]
Na druhou stranu se některé dřívější změny v profilech Validátoru nakonec promítly do změn v DMF.

**Comment by fremrovaK** [comment]
V DMF pro periodika 2.0 a DMF pro monografie 2.1 byly zkontrolovány popisy pro jednotlivé elementy a atributy. Došlo k odstranění zdvojených hodnot (např. "eczenas" viz výše), sjednocení využívání anglických a českých uvozovek a odstranění opakovaných názvů atributů (např. authority, type a další) ve sloupci pro popis.
