### ISSUE TITLE
DMF Periodika 1.7 - nejasná povinnost

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#88]
Např. v DMF Periodika 1.7 na straně 30, atribut physicalDescription/form/@authority. U povinnosti je uvedeno "M/MA". Není jasné, co to znamená. Nejspíš to nějak souvisí s nejasným označením, co platí pro RDA a co pro AACR2. 
Pokud je to tak, tak navruhuji, aby buď byly vyloženě celé tabulky ve dvou verzích (AACR2, RDA), nebo alespoň celé úrovně (typicky elementy), kde se cokoliv liší. A barevné kódování třeba: černá - platí pro všechno, červená - platí pro RDA, modrá - platí pro AACR2. A nemíchal bych barvy napříč řádky.

**Comment by rzeh4n** [comment]
Souvisí s https://github.com/NLCR/Standard_NDK/issues/79, kde taky řeším nejasnosti v tom, co platí pro RDA a co pro AACR2.

**Comment by MirkaBenackova** [comment]
Dobrý deň, je to tak ako hovoríte, povinnosť M platí pre hodnoty ktoré sú čiernou farbou a povinnosť MA len pre tie, ktoré platia pre RDA záznamy, tj. tie ktoré sú červenou. Došlo tam k nejasnému zlúčeniu.

**Comment by vjirousek** [comment]
Opraveno v DMF pro periodika ve verzi 1.9 z 10. 10. 2022
![obrazek](https://user-images.githubusercontent.com/22765973/196238998-29618905-a4e4-4f27-99ef-d199b8ee0edc.png)
