### ISSUE TITLE
Zápis lokace pro titul periodika

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NLCR/Standard_NDK#9]
```
Jaký máte problém?
1. Při zápisu lokace u titulu je povinná siglnatura. Ta je ale typicky pro 
každý ročník jiná. 
2. Což bude znamenat, že v závislosti na postupu zpracování tam budou 
přibývat údaje (viz příklad).

Jak to je nyní?
Popisovat budeme do titulových elementů. 
V případě použití souborného katalogu, smažeme údaje z něj natažené.
Doplníme aktuálně známé údaje z digitalizovaných dokumentů.

Jaké by podle vás bylo ideální řešení?
Zavést možnost popisu lokace do úrovně ročníku.

Napište příklad.

Pokud budeme v prosinci 2012 zpracovávat 1 až 3 ročník titulu budou u něj 
příslušné siglnatury např. A1,A2,A3.
V lednu provdeme export  a ten v každém výtisku bude mít u titulových 
biblo signatury A1,A2,A3.
V únoru zahájíme zpracování 4 ročníku a doplníme tedy siglnaturu A4.
Následné exporty budou mít signatury A1,A2,A3,A4.

```

Original issue reported on code.google.com by `ludane...@gmail.com` on 26 Nov 2012 at 1:12

**Comment by vjirousek** [comment]
S ohledem na stáří požadavku a nulovou aktivitu v diskusi během posledních deseti let navrhuji k uzavření.

Možnost zápisu signatury konkrétního zdrojového svazku existuje na úrovni jednotlivého čísla. Vzhledem k tomu, že jeden ročník periodika je často svázán ve více fyzických svazcích, zápis signatury u čísla se zdá dávat větší smysl.

**Comment by vjirousek** [comment]
V návaznosti na projednání na PS skupině pro textové dokumenty issue uzavírám jako v tuto chvíli nepotřebné. V případě potřeby je možné znovuotevřít.
