### ISSUE TITLE
DMF monografie i periodika, atribut "authority" elementu form- zpřesnění instrukcí u rda záznamů 

### ISSUE THREAD

**Issue by godnat** [NLCR/Standard_NDK#91]
Z DMF (například DMF mono 1.3.2, s. 36) není úplně zřejmé, jaké hodnoty se mohou vyskytovat v atributu "authority" elementu form v případě záznamů zpracovaných dle pravidel RDA. Uvádí se, že element se plní hodnotami z pole 008/23 a z polí 337 a 338, což je správně--výsledkem pak jsou atributy v authority: marcform, rdamedia, rdacarrier.
Ale z informace u atributu "authority" je možné vyvodit , že pro záznamy v RDA jsou platné jen rdamedia a rdacarierr. Je však možné vyvodit i že tam mají být všechny uvedené hodnoty. 

Mapování Kongresové knihovny obsahuje i převod polí 007/00 a 007/01 do elementu form s hodnotami v atributu "authority": marcsmd a marccategory. Tyto atributy DMF povoluje, ale chybí zde informace o převodu hodnot z pole 007 pozic 00 a 01.

(viz také https://github.com/NLCR/komplexni-validator/issues/84)

**Comment by PavlinaKocisova** [comment]
Dobrý den, děkujeme za upozornění. Přidáme to do seznamu budoucích úprav.

**Comment by FilipPavcik** [comment]
Zapracované u všech DMF, proto zavírám.
