### ISSUE TITLE
DMF Zvuk 0.3 atribut Type

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#92]
DMF Zvuk 0.3 požaduje na více místech atribut "Type" tam, kde má být podle MODS atribut "type". Např. u elementu titleInfo, note.

**Comment by PavlinaKocisova** [comment]
děkujeme za poznámku, v příští verzi opravíme.

**Comment by vjirousek** [comment]
Vyřešeno ve verzi standardu 0.4.
https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_zvuk_gramo_0.4_final.pdf
