### ISSUE TITLE
mods:namePart pro více křestních jmen

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#93]
Navrhuji v DMF/pravidlech pro popis určit/doporučit, jak  zapisovat více křestních jmen v mods:namePart, aby se předešlo problémům jako v https://github.com/ceskaexpedice/kramerius-web-client/issues/185
Asi největší smysl dává jeden namePart pro obě křestní jména dohromady, tedy:
```
<mods:name type="personal">
    <mods:namePart type="given">Jan Amos</mods:namePart>
    <mods:namePart type="family">Komenský</mods:namePart>
</mods:name>
```

**Comment by rzeh4n** [comment]
(Protože třeba v DMF Monografie 1.3.1, ani v Pravidlech pro popis monografií 2.1.2 to není)

**Comment by godnat** [comment]
Díky, souhlasím, doporučení přidáme.

**Comment by PavlinaKocisova** [comment]
Dobrý den, tato změna bude implementována ve všech aktualizovaných verzích DMF, nejblíže v DMF pro periodika 1.8 a DMF monografie 1.4.

**Comment by MirkaBenackova** [comment]
Zmena bola implementovaná rovnako do DMF pre elektronické monografie verzie 2.3 a DMF pre elektronické periodiká verzie 2.3 (obe vydané 17.12.2019).
