### ISSUE TITLE
Neplatný identifikátor z MODS metadat by se neměl objevit v DC metadatech

### ISSUE THREAD

**Issue by godnat** [NLCR/Standard_NDK#95]
Metadatové standardy NDK umožňují do metadat zapsat i neplatný (např. zrušený) identifikátor (např. DMF monografie 1.3.2, s. 28).  Například v případě Rudého práva pak zápis neplatného identifikátoru v metadatech MODS vypadá takto:
_<mods:identifier type="ccnb">cnb000529747</mods:identifier>  
<mods:identifier invalid="yes" type="ccnb">cnb000390254</mods:identifier>_  

Dobrou praxí je, aby se neplatný identifikátor z metadat MODS nepřenášel do metadat v DC (zde není možné rozlišit platné a neplatné identifikátory)- standard toto aktuálně nepředepisuje, bude doplněno do další verze standardu. 

Komplexní validátor upozorní varováním, je-li v metadatech DC identifikátor, který je v metadatech MODS označen jako neplatný (invalid).

**Comment by PavlinaKocisova** [comment]
Tato praxe bude formálně implementována do DMF monografie verze 1.4 a DMF periodika verze 1.8.
