### ISSUE TITLE
typ strany anotation

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/Standard_NDK#97]
V poslední verzi [Pravidel pro popis periodik](https://www.ndk.cz/standardy-digitalizace/Pravidla_pro_popis_periodik_verze8.3.1.pdf) je nová hodnota pro typ strany "anotation". Správný anglický překlad anotace je "annotation".

**Comment by MirkaBenackova** [comment]
Zmieňovaná zmena nebola do najnovšej aktualizácie pravidiel pre popis z 20.12.2019 zahrnutá, nakoľko sa hodnota "anotation" v tomto tvare používa aj v DMF, Krameriu a validátore. Hodnota nebude v budúcnosti menená.
