### ISSUE TITLE
Popis stran dotaz

### ISSUE THREAD

**Issue by krizovj** [NLCR/Standard_NDK#99]
Dobrý den, 
mám dotaz na popis stran, který nám nebyl podle pravidel pro popis úplně jasný. 
Jde o knihu, která je na volných listech, na kterých jsou obrázky. Listy nejsou očíslované, ale jsou očíslované ty obrázky. 
Problém je, že na některých listech je samozřejmě obrázků více, třeba čtyři. 
Jak postupovat při popisu stran? Má být číslo strany=číslo obrázku? A co pak v případě, že tam budou ty obrázky čtyři? Napsat do čísla strany všechna čtyři čísla? 
Děkuji za odpověď

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
po porade s kolegami sme dospeli k názoru, že najlepšie bude, ak celú monografiu očíslujete od 1 v hranatých zátvorkách. Čísla obrázkov by sme v súvislosti s číslovaním stránok neriešili.

**Comment by krizovj** [comment]
Děkuji za odpověď
